version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "00:00"
  cooldown:
    default-days: 7
  open-pull-requests-limit: 20
  versioning-strategy: increase
  groups:
    storybook:
      patterns:
        - "@storybook/*"
        - "storybook"
        - "eslint-plugin-storybook"
    react:
      patterns:
      - "react"
      - "react-dom"
      - "@types/react"
      - "@types/react-dom"
    linters:
      patterns:
        - "eslint*"
        - "@eslint*"
        - "@types/eslint*"
        - "typescript-eslint"
        - "lint-staged"
        - "prettier"
        - "stylelint*"
      exclude-patterns:
        - "eslint-plugin-storybook"
    test-suites:
      patterns:
        - "jest*"
        - "vitest*"
        - "@vitejs/*"
        - "@vitest/*"
        - "@testing-library/"
        - "chai-as-promised"
        - "chai-dom"
        - "@types/chai-as-promised"
        - "@types/chai-dom"
        - "html-reporter"
        - "testplane"
    jetbrains-icons:
      patterns:
        - "@jetbrains/icons"
    minor-and-patch:
      update-types:
        - "patch"
        - "minor"
      exclude-patterns:
        - "@storybook/*"
        - "storybook"
        - "eslint-plugin-storybook"
        - "react"
        - "react-dom"
        - "@types/react"
        - "@types/react-dom"
        - "eslint*"
        - "@eslint*"
        - "@types/eslint*"
        - "typescript-eslint"
        - "lint-staged"
        - "prettier"
        - "stylelint*"
        - "jest*"
        - "vitest*"
        - "@vitejs/*"
        - "@vitest/*"
        - "@testing-library/"
        - "chai-as-promised"
        - "chai-dom"
        - "@types/chai-as-promised"
        - "@types/chai-dom"
        - "html-reporter"
        - "testplane"
        - "@jetbrains/icons"
