version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 20
  versioning-strategy: increase
  ignore:
    - dependency-name: html-reporter
      versions:
        - ">= 9.15.0"
