rootUrl: http://localhost:9999
gridUrl: ***REMOVED***
windowSize: 1024x800

browsers:
  chrome:
    browserName: chrome
    platform: WINDOWS
  firefox:
    browserName: firefox
    platform: WINDOWS
