rootUrl: http://localhost:9999
gridUrl: ***REMOVED***

browsers:
  chrome:
    windowSize: 1024x800
    desiredCapabilities:
      browserName: chrome
      platform: WINDOWS
  firefox:
    windowSize: 1024x800
    desiredCapabilities:
      browserName: firefox
      platform: WINDOWS
