package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildFeatures.AutoMerge
import jetbrains.buildServer.configs.kotlin.v2018_2.buildFeatures.merge
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'AllChecks'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("AllChecks")) {
    features {
        val feature1 = find<AutoMerge> {
            merge {
                branchFilter = "+:dependencies.io-*"
                destinationBranch = "master"
            }
        }
        feature1.apply {
            branchFilter = "+:dependabot/*"
            mergePolicy = AutoMerge.MergePolicy.FAST_FORWARD
        }
    }
}
