package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Deploy'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Deploy")) {
    expectSteps {
        script {
            name = "Build for production"
            scriptContent = """
                #!/bin/bash
                set -e -x
                
                node -v
                npm -v
                
                # To prevent lerna's "cannot run in wd" failure
                npm config set unsafe-perm true
                
                npm install
                npm run bootstrap
                npm run build
            """.trimIndent()
            dockerImage = "node:latest"
            dockerRunParameters = "-v %teamcity.build.workingDir%/npmlogs:/root/.npm/_logs"
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            clearConditions()
            dockerImage = "node:12"
        }
    }
}
