package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'GeminiTests'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("GeminiTests")) {
    check(maxRunningBuilds == 2) {
        "Unexpected option value: maxRunningBuilds = $maxRunningBuilds"
    }
    maxRunningBuilds = 1

    params {
        expect {
            password("env.BROWSERSTACK_KEY", "credentialsJSON:af3ef3c7-cc5c-4703-bdfa-76073b0dac40", display = ParameterDisplay.HIDDEN)
        }
        update {
            password("env.BROWSERSTACK_KEY", "credentialsJSON:080a4e07-08b0-4450-8347-ddd8760b4f42", display = ParameterDisplay.HIDDEN)
        }
        expect {
            param("env.BROWSERSTACK_NAME", "jetbrainsuiteam1")
        }
        update {
            param("env.BROWSERSTACK_NAME", "sadf7")
        }
    }
}
