package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'PublishNext'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("PublishNext")) {
    params {
        expect {
            param("vcs.branch.spec", "+:refs/heads/(develop-2.0)")
        }
        update {
            param("vcs.branch.spec", "+:refs/heads/(develop-4.0)")
        }
    }
}
