package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.triggers.RetryBuildTrigger
import jetbrains.buildServer.configs.kotlin.v2018_2.triggers.retryBuild
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Publish'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Publish")) {
    check(artifactRules == "") {
        "Unexpected option value: artifactRules = $artifactRules"
    }
    artifactRules = """
        %teamcity.build.workingDir%/npmlogs/*.log=>npmlogs
        dist=>dist.zip
    """.trimIndent()

    triggers {
        val trigger1 = find<RetryBuildTrigger> {
            retryBuild {
                id = "retryBuildTrigger"
                delaySeconds = 60
            }
        }
        trigger1.apply {
            enabled = false

        }
    }
}
