package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'PublishCanary'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("PublishCanary")) {
    params {
        expect {
            param("vcs.branch.spec", """
                -:refs/heads/(master)
                +:refs/heads/(develop-*)
            """.trimIndent())
        }
        update {
            param("vcs.branch.spec", """
                -:refs/heads/(master)
                +:refs/heads/(develop-*)
                +:refs/heads/(deprecate-moment)
            """.trimIndent())
        }
    }
}
