// flow-typed signature: 58ba6694259c7676c9cb174983ab69c8
// flow-typed version: <<STUB>>/angular_v1.6.3/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'angular'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'angular' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'angular/angular' {
  declare module.exports: any;
}

declare module 'angular/angular.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'angular/angular.js' {
  declare module.exports: $Exports<'angular/angular'>;
}
declare module 'angular/angular.min.js' {
  declare module.exports: $Exports<'angular/angular.min'>;
}
declare module 'angular/index' {
  declare module.exports: $Exports<'angular'>;
}
declare module 'angular/index.js' {
  declare module.exports: $Exports<'angular'>;
}
