// flow-typed signature: b10b6b97981304ab0298844b16c41843
// flow-typed version: <<STUB>>/angular-elastic_v2.5.1-jb/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'angular-elastic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'angular-elastic' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'angular-elastic/elastic' {
  declare module.exports: any;
}

// Filename aliases
declare module 'angular-elastic/elastic.js' {
  declare module.exports: $Exports<'angular-elastic/elastic'>;
}
