// flow-typed signature: 1cf7a6423bdeb76a92956d68d8e05089
// flow-typed version: <<STUB>>/angular-route_v1.6.3/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'angular-route'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'angular-route' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'angular-route/angular-route' {
  declare module.exports: any;
}

declare module 'angular-route/angular-route.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'angular-route/angular-route.js' {
  declare module.exports: $Exports<'angular-route/angular-route'>;
}
declare module 'angular-route/angular-route.min.js' {
  declare module.exports: $Exports<'angular-route/angular-route.min'>;
}
declare module 'angular-route/index' {
  declare module.exports: $Exports<'angular-route'>;
}
declare module 'angular-route/index.js' {
  declare module.exports: $Exports<'angular-route'>;
}
