// flow-typed signature: a9b2f34df01f6a4aed2b774930a0d2c5
// flow-typed version: <<STUB>>/angular-mocks_v1.6.3/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'angular-mocks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'angular-mocks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'angular-mocks/angular-mocks' {
  declare module.exports: any;
}

declare module 'angular-mocks/ngAnimateMock' {
  declare module.exports: any;
}

declare module 'angular-mocks/ngMock' {
  declare module.exports: any;
}

declare module 'angular-mocks/ngMockE2E' {
  declare module.exports: any;
}

// Filename aliases
declare module 'angular-mocks/angular-mocks.js' {
  declare module.exports: $Exports<'angular-mocks/angular-mocks'>;
}
declare module 'angular-mocks/ngAnimateMock.js' {
  declare module.exports: $Exports<'angular-mocks/ngAnimateMock'>;
}
declare module 'angular-mocks/ngMock.js' {
  declare module.exports: $Exports<'angular-mocks/ngMock'>;
}
declare module 'angular-mocks/ngMockE2E.js' {
  declare module.exports: $Exports<'angular-mocks/ngMockE2E'>;
}
