// flow-typed signature: cf22c2a0b3db53c08ff6336c3e6f83f7
// flow-typed version: <<STUB>>/babel-preset-jetbrains_v1.0.11/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-jetbrains'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-jetbrains' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-jetbrains/index' {
  declare module.exports: $Exports<'babel-preset-jetbrains'>;
}
declare module 'babel-preset-jetbrains/index.js' {
  declare module.exports: $Exports<'babel-preset-jetbrains'>;
}
