// flow-typed signature: db594fd87e450c9eaa7ca0f75f1bd193
// flow-typed version: <<STUB>>/combokeys_v2.4.6/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'combokeys'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'combokeys' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'combokeys/Combokeys/index' {
  declare module.exports: any;
}

declare module 'combokeys/Combokeys/prototype/addEvents' {
  declare module.exports: any;
}

declare module 'combokeys/Combokeys/prototype/bind' {
  declare module.exports: any;
}

declare module 'combokeys/Combokeys/prototype/bindMultiple' {
  declare module.exports: any;
}

declare module 'combokeys/Combokeys/prototype/bindSequence' {
  declare module.exports: any;
}

declare module 'combokeys/Combokeys/prototype/bindSingle' {
  declare module.exports: any;
}

declare module 'combokeys/Combokeys/prototype/detach' {
  declare module.exports: any;
}

declare module 'combokeys/Combokeys/prototype/dom-event' {
  declare module.exports: any;
}

declare module 'combokeys/Combokeys/prototype/fireCallback' {
  declare module.exports: any;
}

declare module 'combokeys/Combokeys/prototype/getKeyInfo' {
  declare module.exports: any;
}

declare module 'combokeys/Combokeys/prototype/getMatches' {
  declare module.exports: any;
}

declare module 'combokeys/Combokeys/prototype/getReverseMap' {
  declare module.exports: any;
}

declare module 'combokeys/Combokeys/prototype/handleKey' {
  declare module.exports: any;
}

declare module 'combokeys/Combokeys/prototype/handleKeyEvent' {
  declare module.exports: any;
}

declare module 'combokeys/Combokeys/prototype/modifiersMatch' {
  declare module.exports: any;
}

declare module 'combokeys/Combokeys/prototype/pickBestAction' {
  declare module.exports: any;
}

declare module 'combokeys/Combokeys/prototype/reset' {
  declare module.exports: any;
}

declare module 'combokeys/Combokeys/prototype/resetSequenceTimer' {
  declare module.exports: any;
}

declare module 'combokeys/Combokeys/prototype/resetSequences' {
  declare module.exports: any;
}

declare module 'combokeys/Combokeys/prototype/stopCallback' {
  declare module.exports: any;
}

declare module 'combokeys/Combokeys/prototype/trigger' {
  declare module.exports: any;
}

declare module 'combokeys/Combokeys/prototype/unbind' {
  declare module.exports: any;
}

declare module 'combokeys/Combokeys/reset' {
  declare module.exports: any;
}

declare module 'combokeys/helpers/characterFromEvent' {
  declare module.exports: any;
}

declare module 'combokeys/helpers/eventModifiers' {
  declare module.exports: any;
}

declare module 'combokeys/helpers/isModifier' {
  declare module.exports: any;
}

declare module 'combokeys/helpers/keysFromString' {
  declare module.exports: any;
}

declare module 'combokeys/helpers/preventDefault' {
  declare module.exports: any;
}

declare module 'combokeys/helpers/shift-map' {
  declare module.exports: any;
}

declare module 'combokeys/helpers/special-aliases' {
  declare module.exports: any;
}

declare module 'combokeys/helpers/special-characters-map' {
  declare module.exports: any;
}

declare module 'combokeys/helpers/special-keys-map' {
  declare module.exports: any;
}

declare module 'combokeys/helpers/stopPropagation' {
  declare module.exports: any;
}

declare module 'combokeys/plugins/bind-dictionary/index' {
  declare module.exports: any;
}

declare module 'combokeys/plugins/global-bind/index' {
  declare module.exports: any;
}

declare module 'combokeys/plugins/pause/index' {
  declare module.exports: any;
}

declare module 'combokeys/plugins/record/index' {
  declare module.exports: any;
}

declare module 'combokeys/test/bind' {
  declare module.exports: any;
}

declare module 'combokeys/test/detach' {
  declare module.exports: any;
}

declare module 'combokeys/test/helpers/make-element' {
  declare module.exports: any;
}

declare module 'combokeys/test/index' {
  declare module.exports: any;
}

declare module 'combokeys/test/initialization' {
  declare module.exports: any;
}

declare module 'combokeys/test/lib/key-event' {
  declare module.exports: any;
}

declare module 'combokeys/test/plugins/bind-dictionary' {
  declare module.exports: any;
}

declare module 'combokeys/test/plugins/global-bind' {
  declare module.exports: any;
}

declare module 'combokeys/test/plugins/pause' {
  declare module.exports: any;
}

declare module 'combokeys/test/plugins/record' {
  declare module.exports: any;
}

declare module 'combokeys/test/unbind' {
  declare module.exports: any;
}

// Filename aliases
declare module 'combokeys/Combokeys/index.js' {
  declare module.exports: $Exports<'combokeys/Combokeys/index'>;
}
declare module 'combokeys/Combokeys/prototype/addEvents.js' {
  declare module.exports: $Exports<'combokeys/Combokeys/prototype/addEvents'>;
}
declare module 'combokeys/Combokeys/prototype/bind.js' {
  declare module.exports: $Exports<'combokeys/Combokeys/prototype/bind'>;
}
declare module 'combokeys/Combokeys/prototype/bindMultiple.js' {
  declare module.exports: $Exports<'combokeys/Combokeys/prototype/bindMultiple'>;
}
declare module 'combokeys/Combokeys/prototype/bindSequence.js' {
  declare module.exports: $Exports<'combokeys/Combokeys/prototype/bindSequence'>;
}
declare module 'combokeys/Combokeys/prototype/bindSingle.js' {
  declare module.exports: $Exports<'combokeys/Combokeys/prototype/bindSingle'>;
}
declare module 'combokeys/Combokeys/prototype/detach.js' {
  declare module.exports: $Exports<'combokeys/Combokeys/prototype/detach'>;
}
declare module 'combokeys/Combokeys/prototype/dom-event.js' {
  declare module.exports: $Exports<'combokeys/Combokeys/prototype/dom-event'>;
}
declare module 'combokeys/Combokeys/prototype/fireCallback.js' {
  declare module.exports: $Exports<'combokeys/Combokeys/prototype/fireCallback'>;
}
declare module 'combokeys/Combokeys/prototype/getKeyInfo.js' {
  declare module.exports: $Exports<'combokeys/Combokeys/prototype/getKeyInfo'>;
}
declare module 'combokeys/Combokeys/prototype/getMatches.js' {
  declare module.exports: $Exports<'combokeys/Combokeys/prototype/getMatches'>;
}
declare module 'combokeys/Combokeys/prototype/getReverseMap.js' {
  declare module.exports: $Exports<'combokeys/Combokeys/prototype/getReverseMap'>;
}
declare module 'combokeys/Combokeys/prototype/handleKey.js' {
  declare module.exports: $Exports<'combokeys/Combokeys/prototype/handleKey'>;
}
declare module 'combokeys/Combokeys/prototype/handleKeyEvent.js' {
  declare module.exports: $Exports<'combokeys/Combokeys/prototype/handleKeyEvent'>;
}
declare module 'combokeys/Combokeys/prototype/modifiersMatch.js' {
  declare module.exports: $Exports<'combokeys/Combokeys/prototype/modifiersMatch'>;
}
declare module 'combokeys/Combokeys/prototype/pickBestAction.js' {
  declare module.exports: $Exports<'combokeys/Combokeys/prototype/pickBestAction'>;
}
declare module 'combokeys/Combokeys/prototype/reset.js' {
  declare module.exports: $Exports<'combokeys/Combokeys/prototype/reset'>;
}
declare module 'combokeys/Combokeys/prototype/resetSequenceTimer.js' {
  declare module.exports: $Exports<'combokeys/Combokeys/prototype/resetSequenceTimer'>;
}
declare module 'combokeys/Combokeys/prototype/resetSequences.js' {
  declare module.exports: $Exports<'combokeys/Combokeys/prototype/resetSequences'>;
}
declare module 'combokeys/Combokeys/prototype/stopCallback.js' {
  declare module.exports: $Exports<'combokeys/Combokeys/prototype/stopCallback'>;
}
declare module 'combokeys/Combokeys/prototype/trigger.js' {
  declare module.exports: $Exports<'combokeys/Combokeys/prototype/trigger'>;
}
declare module 'combokeys/Combokeys/prototype/unbind.js' {
  declare module.exports: $Exports<'combokeys/Combokeys/prototype/unbind'>;
}
declare module 'combokeys/Combokeys/reset.js' {
  declare module.exports: $Exports<'combokeys/Combokeys/reset'>;
}
declare module 'combokeys/helpers/characterFromEvent.js' {
  declare module.exports: $Exports<'combokeys/helpers/characterFromEvent'>;
}
declare module 'combokeys/helpers/eventModifiers.js' {
  declare module.exports: $Exports<'combokeys/helpers/eventModifiers'>;
}
declare module 'combokeys/helpers/isModifier.js' {
  declare module.exports: $Exports<'combokeys/helpers/isModifier'>;
}
declare module 'combokeys/helpers/keysFromString.js' {
  declare module.exports: $Exports<'combokeys/helpers/keysFromString'>;
}
declare module 'combokeys/helpers/preventDefault.js' {
  declare module.exports: $Exports<'combokeys/helpers/preventDefault'>;
}
declare module 'combokeys/helpers/shift-map.js' {
  declare module.exports: $Exports<'combokeys/helpers/shift-map'>;
}
declare module 'combokeys/helpers/special-aliases.js' {
  declare module.exports: $Exports<'combokeys/helpers/special-aliases'>;
}
declare module 'combokeys/helpers/special-characters-map.js' {
  declare module.exports: $Exports<'combokeys/helpers/special-characters-map'>;
}
declare module 'combokeys/helpers/special-keys-map.js' {
  declare module.exports: $Exports<'combokeys/helpers/special-keys-map'>;
}
declare module 'combokeys/helpers/stopPropagation.js' {
  declare module.exports: $Exports<'combokeys/helpers/stopPropagation'>;
}
declare module 'combokeys/plugins/bind-dictionary/index.js' {
  declare module.exports: $Exports<'combokeys/plugins/bind-dictionary/index'>;
}
declare module 'combokeys/plugins/global-bind/index.js' {
  declare module.exports: $Exports<'combokeys/plugins/global-bind/index'>;
}
declare module 'combokeys/plugins/pause/index.js' {
  declare module.exports: $Exports<'combokeys/plugins/pause/index'>;
}
declare module 'combokeys/plugins/record/index.js' {
  declare module.exports: $Exports<'combokeys/plugins/record/index'>;
}
declare module 'combokeys/test/bind.js' {
  declare module.exports: $Exports<'combokeys/test/bind'>;
}
declare module 'combokeys/test/detach.js' {
  declare module.exports: $Exports<'combokeys/test/detach'>;
}
declare module 'combokeys/test/helpers/make-element.js' {
  declare module.exports: $Exports<'combokeys/test/helpers/make-element'>;
}
declare module 'combokeys/test/index.js' {
  declare module.exports: $Exports<'combokeys/test/index'>;
}
declare module 'combokeys/test/initialization.js' {
  declare module.exports: $Exports<'combokeys/test/initialization'>;
}
declare module 'combokeys/test/lib/key-event.js' {
  declare module.exports: $Exports<'combokeys/test/lib/key-event'>;
}
declare module 'combokeys/test/plugins/bind-dictionary.js' {
  declare module.exports: $Exports<'combokeys/test/plugins/bind-dictionary'>;
}
declare module 'combokeys/test/plugins/global-bind.js' {
  declare module.exports: $Exports<'combokeys/test/plugins/global-bind'>;
}
declare module 'combokeys/test/plugins/pause.js' {
  declare module.exports: $Exports<'combokeys/test/plugins/pause'>;
}
declare module 'combokeys/test/plugins/record.js' {
  declare module.exports: $Exports<'combokeys/test/plugins/record'>;
}
declare module 'combokeys/test/unbind.js' {
  declare module.exports: $Exports<'combokeys/test/unbind'>;
}
