// flow-typed signature: a93dcdaa8f8d94a7540a4359fc0348e1
// flow-typed version: <<STUB>>/docpack-page-generator_v0.0.6/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'docpack-page-generator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'docpack-page-generator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'docpack-page-generator/lib/plugin' {
  declare module.exports: any;
}

declare module 'docpack-page-generator/test/fixtures/entry' {
  declare module.exports: any;
}

declare module 'docpack-page-generator/test/fixtures/template' {
  declare module.exports: any;
}

declare module 'docpack-page-generator/test/plugin.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'docpack-page-generator/lib/plugin.js' {
  declare module.exports: $Exports<'docpack-page-generator/lib/plugin'>;
}
declare module 'docpack-page-generator/test/fixtures/entry.js' {
  declare module.exports: $Exports<'docpack-page-generator/test/fixtures/entry'>;
}
declare module 'docpack-page-generator/test/fixtures/template.js' {
  declare module.exports: $Exports<'docpack-page-generator/test/fixtures/template'>;
}
declare module 'docpack-page-generator/test/plugin.test.js' {
  declare module.exports: $Exports<'docpack-page-generator/test/plugin.test'>;
}
