// flow-typed signature: f1472b91a82126b280062a7a83c9d6e3
// flow-typed version: <<STUB>>/docpack-markdown-extractor_v0.0.2/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'docpack-markdown-extractor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'docpack-markdown-extractor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'docpack-markdown-extractor/lib/extractor' {
  declare module.exports: any;
}

declare module 'docpack-markdown-extractor/lib/plugin' {
  declare module.exports: any;
}

declare module 'docpack-markdown-extractor/test/extractor.test' {
  declare module.exports: any;
}

declare module 'docpack-markdown-extractor/test/plugin.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'docpack-markdown-extractor/lib/extractor.js' {
  declare module.exports: $Exports<'docpack-markdown-extractor/lib/extractor'>;
}
declare module 'docpack-markdown-extractor/lib/plugin.js' {
  declare module.exports: $Exports<'docpack-markdown-extractor/lib/plugin'>;
}
declare module 'docpack-markdown-extractor/test/extractor.test.js' {
  declare module.exports: $Exports<'docpack-markdown-extractor/test/extractor.test'>;
}
declare module 'docpack-markdown-extractor/test/plugin.test.js' {
  declare module.exports: $Exports<'docpack-markdown-extractor/test/plugin.test'>;
}
