// flow-typed signature: d8f9b0210c038da96c4192e165b366db
// flow-typed version: <<STUB>>/docpack_v1.0.2/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'docpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'docpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'docpack/lib/data/Asset' {
  declare module.exports: any;
}

declare module 'docpack/lib/data/CodeBlock' {
  declare module.exports: any;
}

declare module 'docpack/lib/data/Example' {
  declare module.exports: any;
}

declare module 'docpack/lib/data/ExampleFile' {
  declare module.exports: any;
}

declare module 'docpack/lib/data/Page' {
  declare module.exports: any;
}

declare module 'docpack/lib/data/Source' {
  declare module.exports: any;
}

declare module 'docpack/lib/data/utils/required' {
  declare module.exports: any;
}

declare module 'docpack/lib/docpack' {
  declare module.exports: any;
}

declare module 'docpack/lib/hooks' {
  declare module.exports: any;
}

declare module 'docpack/lib/utils/DocpackPlugin' {
  declare module.exports: any;
}

declare module 'docpack/lib/utils/DocpackPluginError' {
  declare module.exports: any;
}

declare module 'docpack/lib/utils/DocpackPluginWarning' {
  declare module.exports: any;
}

declare module 'docpack/lib/utils/createExtractorContext' {
  declare module.exports: any;
}

declare module 'docpack/test/data.test' {
  declare module.exports: any;
}

declare module 'docpack/test/docpack.test' {
  declare module.exports: any;
}

declare module 'docpack/test/utils/DocpackPlugin.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'docpack/lib/data/Asset.js' {
  declare module.exports: $Exports<'docpack/lib/data/Asset'>;
}
declare module 'docpack/lib/data/CodeBlock.js' {
  declare module.exports: $Exports<'docpack/lib/data/CodeBlock'>;
}
declare module 'docpack/lib/data/Example.js' {
  declare module.exports: $Exports<'docpack/lib/data/Example'>;
}
declare module 'docpack/lib/data/ExampleFile.js' {
  declare module.exports: $Exports<'docpack/lib/data/ExampleFile'>;
}
declare module 'docpack/lib/data/Page.js' {
  declare module.exports: $Exports<'docpack/lib/data/Page'>;
}
declare module 'docpack/lib/data/Source.js' {
  declare module.exports: $Exports<'docpack/lib/data/Source'>;
}
declare module 'docpack/lib/data/utils/required.js' {
  declare module.exports: $Exports<'docpack/lib/data/utils/required'>;
}
declare module 'docpack/lib/docpack.js' {
  declare module.exports: $Exports<'docpack/lib/docpack'>;
}
declare module 'docpack/lib/hooks.js' {
  declare module.exports: $Exports<'docpack/lib/hooks'>;
}
declare module 'docpack/lib/utils/DocpackPlugin.js' {
  declare module.exports: $Exports<'docpack/lib/utils/DocpackPlugin'>;
}
declare module 'docpack/lib/utils/DocpackPluginError.js' {
  declare module.exports: $Exports<'docpack/lib/utils/DocpackPluginError'>;
}
declare module 'docpack/lib/utils/DocpackPluginWarning.js' {
  declare module.exports: $Exports<'docpack/lib/utils/DocpackPluginWarning'>;
}
declare module 'docpack/lib/utils/createExtractorContext.js' {
  declare module.exports: $Exports<'docpack/lib/utils/createExtractorContext'>;
}
declare module 'docpack/test/data.test.js' {
  declare module.exports: $Exports<'docpack/test/data.test'>;
}
declare module 'docpack/test/docpack.test.js' {
  declare module.exports: $Exports<'docpack/test/docpack.test'>;
}
declare module 'docpack/test/utils/DocpackPlugin.test.js' {
  declare module.exports: $Exports<'docpack/test/utils/DocpackPlugin.test'>;
}
