// flow-typed signature: aa7de86f888e3905f696f80a89b70ff2
// flow-typed version: <<STUB>>/docpack-examples-compiler_v0.0.3/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'docpack-examples-compiler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'docpack-examples-compiler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'docpack-examples-compiler/lib/ExamplesCompiler' {
  declare module.exports: any;
}

declare module 'docpack-examples-compiler/lib/loader' {
  declare module.exports: any;
}

declare module 'docpack-examples-compiler/lib/plugin' {
  declare module.exports: any;
}

declare module 'docpack-examples-compiler/test/ExamplesCompiler.test' {
  declare module.exports: any;
}

declare module 'docpack-examples-compiler/test/fixtures/dummy' {
  declare module.exports: any;
}

declare module 'docpack-examples-compiler/test/loader.test' {
  declare module.exports: any;
}

declare module 'docpack-examples-compiler/test/plugin.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'docpack-examples-compiler/lib/ExamplesCompiler.js' {
  declare module.exports: $Exports<'docpack-examples-compiler/lib/ExamplesCompiler'>;
}
declare module 'docpack-examples-compiler/lib/loader.js' {
  declare module.exports: $Exports<'docpack-examples-compiler/lib/loader'>;
}
declare module 'docpack-examples-compiler/lib/plugin.js' {
  declare module.exports: $Exports<'docpack-examples-compiler/lib/plugin'>;
}
declare module 'docpack-examples-compiler/test/ExamplesCompiler.test.js' {
  declare module.exports: $Exports<'docpack-examples-compiler/test/ExamplesCompiler.test'>;
}
declare module 'docpack-examples-compiler/test/fixtures/dummy.js' {
  declare module.exports: $Exports<'docpack-examples-compiler/test/fixtures/dummy'>;
}
declare module 'docpack-examples-compiler/test/loader.test.js' {
  declare module.exports: $Exports<'docpack-examples-compiler/test/loader.test'>;
}
declare module 'docpack-examples-compiler/test/plugin.test.js' {
  declare module.exports: $Exports<'docpack-examples-compiler/test/plugin.test'>;
}
