// flow-typed signature: a43db8cca2aeaf5019f8dfb17d9c802e
// flow-typed version: <<STUB>>/docpack-jsdoc-extractor_v0.0.6/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'docpack-jsdoc-extractor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'docpack-jsdoc-extractor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'docpack-jsdoc-extractor/lib/extractor' {
  declare module.exports: any;
}

declare module 'docpack-jsdoc-extractor/lib/parseXMLExamples' {
  declare module.exports: any;
}

declare module 'docpack-jsdoc-extractor/lib/plugin' {
  declare module.exports: any;
}

declare module 'docpack-jsdoc-extractor/test/extractor.test' {
  declare module.exports: any;
}

declare module 'docpack-jsdoc-extractor/test/parseXMLExamples.test' {
  declare module.exports: any;
}

declare module 'docpack-jsdoc-extractor/test/plugin.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'docpack-jsdoc-extractor/lib/extractor.js' {
  declare module.exports: $Exports<'docpack-jsdoc-extractor/lib/extractor'>;
}
declare module 'docpack-jsdoc-extractor/lib/parseXMLExamples.js' {
  declare module.exports: $Exports<'docpack-jsdoc-extractor/lib/parseXMLExamples'>;
}
declare module 'docpack-jsdoc-extractor/lib/plugin.js' {
  declare module.exports: $Exports<'docpack-jsdoc-extractor/lib/plugin'>;
}
declare module 'docpack-jsdoc-extractor/test/extractor.test.js' {
  declare module.exports: $Exports<'docpack-jsdoc-extractor/test/extractor.test'>;
}
declare module 'docpack-jsdoc-extractor/test/parseXMLExamples.test.js' {
  declare module.exports: $Exports<'docpack-jsdoc-extractor/test/parseXMLExamples.test'>;
}
declare module 'docpack-jsdoc-extractor/test/plugin.test.js' {
  declare module.exports: $Exports<'docpack-jsdoc-extractor/test/plugin.test'>;
}
