// flow-typed signature: 7ab08f463299a4d19536e47d9c291057
// flow-typed version: <<STUB>>/element-resize-detector_v1.1.11/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'element-resize-detector'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'element-resize-detector' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'element-resize-detector/Gruntfile' {
  declare module.exports: any;
}

declare module 'element-resize-detector/dist/element-resize-detector' {
  declare module.exports: any;
}

declare module 'element-resize-detector/dist/element-resize-detector.min' {
  declare module.exports: any;
}

declare module 'element-resize-detector/karma.conf' {
  declare module.exports: any;
}

declare module 'element-resize-detector/src/browser-detector' {
  declare module.exports: any;
}

declare module 'element-resize-detector/src/collection-utils' {
  declare module.exports: any;
}

declare module 'element-resize-detector/src/detection-strategy/object' {
  declare module.exports: any;
}

declare module 'element-resize-detector/src/detection-strategy/scroll' {
  declare module.exports: any;
}

declare module 'element-resize-detector/src/element-resize-detector' {
  declare module.exports: any;
}

declare module 'element-resize-detector/src/element-utils' {
  declare module.exports: any;
}

declare module 'element-resize-detector/src/id-generator' {
  declare module.exports: any;
}

declare module 'element-resize-detector/src/id-handler' {
  declare module.exports: any;
}

declare module 'element-resize-detector/src/listener-handler' {
  declare module.exports: any;
}

declare module 'element-resize-detector/src/reporter' {
  declare module.exports: any;
}

declare module 'element-resize-detector/src/state-handler' {
  declare module.exports: any;
}

declare module 'element-resize-detector/test/element-resize-detector_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'element-resize-detector/Gruntfile.js' {
  declare module.exports: $Exports<'element-resize-detector/Gruntfile'>;
}
declare module 'element-resize-detector/dist/element-resize-detector.js' {
  declare module.exports: $Exports<'element-resize-detector/dist/element-resize-detector'>;
}
declare module 'element-resize-detector/dist/element-resize-detector.min.js' {
  declare module.exports: $Exports<'element-resize-detector/dist/element-resize-detector.min'>;
}
declare module 'element-resize-detector/karma.conf.js' {
  declare module.exports: $Exports<'element-resize-detector/karma.conf'>;
}
declare module 'element-resize-detector/src/browser-detector.js' {
  declare module.exports: $Exports<'element-resize-detector/src/browser-detector'>;
}
declare module 'element-resize-detector/src/collection-utils.js' {
  declare module.exports: $Exports<'element-resize-detector/src/collection-utils'>;
}
declare module 'element-resize-detector/src/detection-strategy/object.js' {
  declare module.exports: $Exports<'element-resize-detector/src/detection-strategy/object'>;
}
declare module 'element-resize-detector/src/detection-strategy/scroll.js' {
  declare module.exports: $Exports<'element-resize-detector/src/detection-strategy/scroll'>;
}
declare module 'element-resize-detector/src/element-resize-detector.js' {
  declare module.exports: $Exports<'element-resize-detector/src/element-resize-detector'>;
}
declare module 'element-resize-detector/src/element-utils.js' {
  declare module.exports: $Exports<'element-resize-detector/src/element-utils'>;
}
declare module 'element-resize-detector/src/id-generator.js' {
  declare module.exports: $Exports<'element-resize-detector/src/id-generator'>;
}
declare module 'element-resize-detector/src/id-handler.js' {
  declare module.exports: $Exports<'element-resize-detector/src/id-handler'>;
}
declare module 'element-resize-detector/src/listener-handler.js' {
  declare module.exports: $Exports<'element-resize-detector/src/listener-handler'>;
}
declare module 'element-resize-detector/src/reporter.js' {
  declare module.exports: $Exports<'element-resize-detector/src/reporter'>;
}
declare module 'element-resize-detector/src/state-handler.js' {
  declare module.exports: $Exports<'element-resize-detector/src/state-handler'>;
}
declare module 'element-resize-detector/test/element-resize-detector_test.js' {
  declare module.exports: $Exports<'element-resize-detector/test/element-resize-detector_test'>;
}
