// flow-typed signature: cbb39047c6872b99802c362d4ef7e8a1
// flow-typed version: <<STUB>>/es6-error_v^4.0.2/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'es6-error'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'es6-error' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'es6-error/babel-config' {
  declare module.exports: any;
}

declare module 'es6-error/lib/index' {
  declare module.exports: any;
}

declare module 'es6-error/lib/index.jsnext' {
  declare module.exports: any;
}

declare module 'es6-error/lib/index.ts' {
  declare module.exports: any;
}

declare module 'es6-error/src/index' {
  declare module.exports: any;
}

declare module 'es6-error/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'es6-error/babel-config.js' {
  declare module.exports: $Exports<'es6-error/babel-config'>;
}
declare module 'es6-error/lib/index.js' {
  declare module.exports: $Exports<'es6-error/lib/index'>;
}
declare module 'es6-error/lib/index.jsnext.js' {
  declare module.exports: $Exports<'es6-error/lib/index.jsnext'>;
}
declare module 'es6-error/lib/index.ts.js' {
  declare module.exports: $Exports<'es6-error/lib/index.ts'>;
}
declare module 'es6-error/src/index.js' {
  declare module.exports: $Exports<'es6-error/src/index'>;
}
declare module 'es6-error/test/index.js' {
  declare module.exports: $Exports<'es6-error/test/index'>;
}
