// flow-typed signature: 9df70982410bb34ab74f5afce3dff8fa
// flow-typed version: <<STUB>>/eslint-nibble_v3.0.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-nibble'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-nibble' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-nibble/bin/eslint-nibble' {
  declare module.exports: any;
}

declare module 'eslint-nibble/lib/cli' {
  declare module.exports: any;
}

declare module 'eslint-nibble/lib/config/formatters' {
  declare module.exports: any;
}

declare module 'eslint-nibble/lib/config/options' {
  declare module.exports: any;
}

declare module 'eslint-nibble/lib/nibbler' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-nibble/bin/eslint-nibble.js' {
  declare module.exports: $Exports<'eslint-nibble/bin/eslint-nibble'>;
}
declare module 'eslint-nibble/index' {
  declare module.exports: $Exports<'eslint-nibble'>;
}
declare module 'eslint-nibble/index.js' {
  declare module.exports: $Exports<'eslint-nibble'>;
}
declare module 'eslint-nibble/lib/cli.js' {
  declare module.exports: $Exports<'eslint-nibble/lib/cli'>;
}
declare module 'eslint-nibble/lib/config/formatters.js' {
  declare module.exports: $Exports<'eslint-nibble/lib/config/formatters'>;
}
declare module 'eslint-nibble/lib/config/options.js' {
  declare module.exports: $Exports<'eslint-nibble/lib/config/options'>;
}
declare module 'eslint-nibble/lib/nibbler.js' {
  declare module.exports: $Exports<'eslint-nibble/lib/nibbler'>;
}
