// flow-typed signature: 86d6ad66b16e104b7de15b4533dceefe
// flow-typed version: <<STUB>>/eslint-config-jetbrains_v2.0.28/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-jetbrains'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-jetbrains' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-jetbrains/angular' {
  declare module.exports: any;
}

declare module 'eslint-config-jetbrains/es6' {
  declare module.exports: any;
}

declare module 'eslint-config-jetbrains/node' {
  declare module.exports: any;
}

declare module 'eslint-config-jetbrains/react' {
  declare module.exports: any;
}

declare module 'eslint-config-jetbrains/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-jetbrains/angular.js' {
  declare module.exports: $Exports<'eslint-config-jetbrains/angular'>;
}
declare module 'eslint-config-jetbrains/es6.js' {
  declare module.exports: $Exports<'eslint-config-jetbrains/es6'>;
}
declare module 'eslint-config-jetbrains/index' {
  declare module.exports: $Exports<'eslint-config-jetbrains'>;
}
declare module 'eslint-config-jetbrains/index.js' {
  declare module.exports: $Exports<'eslint-config-jetbrains'>;
}
declare module 'eslint-config-jetbrains/node.js' {
  declare module.exports: $Exports<'eslint-config-jetbrains/node'>;
}
declare module 'eslint-config-jetbrains/react.js' {
  declare module.exports: $Exports<'eslint-config-jetbrains/react'>;
}
declare module 'eslint-config-jetbrains/test.js' {
  declare module.exports: $Exports<'eslint-config-jetbrains/test'>;
}
