// flow-typed signature: 91f4c337080a25be7c891e700b836ad5
// flow-typed version: <<STUB>>/exports-loader_v0.6.3/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'exports-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'exports-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'exports-loader/index' {
  declare module.exports: $Exports<'exports-loader'>;
}
declare module 'exports-loader/index.js' {
  declare module.exports: $Exports<'exports-loader'>;
}
