// flow-typed signature: bcfea4b1f8b97a4bcab7463e3f4bc80c
// flow-typed version: <<STUB>>/forever_v0.15.3/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'forever'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'forever' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'forever/lib/forever' {
  declare module.exports: any;
}

declare module 'forever/lib/forever/cli' {
  declare module.exports: any;
}

declare module 'forever/lib/forever/worker' {
  declare module.exports: any;
}

declare module 'forever/test/core/daemonic-inheritance-test' {
  declare module.exports: any;
}

declare module 'forever/test/core/start-stop-json-array-test' {
  declare module.exports: any;
}

declare module 'forever/test/core/start-stop-json-obj-test' {
  declare module.exports: any;
}

declare module 'forever/test/core/start-stop-relative-test' {
  declare module.exports: any;
}

declare module 'forever/test/core/stopall-peaceful-test' {
  declare module.exports: any;
}

declare module 'forever/test/core/stopbypid-peaceful-test' {
  declare module.exports: any;
}

declare module 'forever/test/core/tail-stopall-test' {
  declare module.exports: any;
}

declare module 'forever/test/fixtures/cluster-fork-mode' {
  declare module.exports: any;
}

declare module 'forever/test/fixtures/log-on-interval' {
  declare module.exports: any;
}

declare module 'forever/test/fixtures/server' {
  declare module.exports: any;
}

declare module 'forever/test/fixtures/start-daemon' {
  declare module.exports: any;
}

declare module 'forever/test/helpers/index' {
  declare module.exports: any;
}

declare module 'forever/test/helpers/macros' {
  declare module.exports: any;
}

declare module 'forever/test/helpers/mocks/child-process' {
  declare module.exports: any;
}

declare module 'forever/test/helpers/mocks/monitor' {
  declare module.exports: any;
}

declare module 'forever/test/helpers/mocks/stream' {
  declare module.exports: any;
}

declare module 'forever/test/worker/multiple-workers-test' {
  declare module.exports: any;
}

declare module 'forever/test/worker/simple-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'forever/lib/forever.js' {
  declare module.exports: $Exports<'forever/lib/forever'>;
}
declare module 'forever/lib/forever/cli.js' {
  declare module.exports: $Exports<'forever/lib/forever/cli'>;
}
declare module 'forever/lib/forever/worker.js' {
  declare module.exports: $Exports<'forever/lib/forever/worker'>;
}
declare module 'forever/test/core/daemonic-inheritance-test.js' {
  declare module.exports: $Exports<'forever/test/core/daemonic-inheritance-test'>;
}
declare module 'forever/test/core/start-stop-json-array-test.js' {
  declare module.exports: $Exports<'forever/test/core/start-stop-json-array-test'>;
}
declare module 'forever/test/core/start-stop-json-obj-test.js' {
  declare module.exports: $Exports<'forever/test/core/start-stop-json-obj-test'>;
}
declare module 'forever/test/core/start-stop-relative-test.js' {
  declare module.exports: $Exports<'forever/test/core/start-stop-relative-test'>;
}
declare module 'forever/test/core/stopall-peaceful-test.js' {
  declare module.exports: $Exports<'forever/test/core/stopall-peaceful-test'>;
}
declare module 'forever/test/core/stopbypid-peaceful-test.js' {
  declare module.exports: $Exports<'forever/test/core/stopbypid-peaceful-test'>;
}
declare module 'forever/test/core/tail-stopall-test.js' {
  declare module.exports: $Exports<'forever/test/core/tail-stopall-test'>;
}
declare module 'forever/test/fixtures/cluster-fork-mode.js' {
  declare module.exports: $Exports<'forever/test/fixtures/cluster-fork-mode'>;
}
declare module 'forever/test/fixtures/log-on-interval.js' {
  declare module.exports: $Exports<'forever/test/fixtures/log-on-interval'>;
}
declare module 'forever/test/fixtures/server.js' {
  declare module.exports: $Exports<'forever/test/fixtures/server'>;
}
declare module 'forever/test/fixtures/start-daemon.js' {
  declare module.exports: $Exports<'forever/test/fixtures/start-daemon'>;
}
declare module 'forever/test/helpers/index.js' {
  declare module.exports: $Exports<'forever/test/helpers/index'>;
}
declare module 'forever/test/helpers/macros.js' {
  declare module.exports: $Exports<'forever/test/helpers/macros'>;
}
declare module 'forever/test/helpers/mocks/child-process.js' {
  declare module.exports: $Exports<'forever/test/helpers/mocks/child-process'>;
}
declare module 'forever/test/helpers/mocks/monitor.js' {
  declare module.exports: $Exports<'forever/test/helpers/mocks/monitor'>;
}
declare module 'forever/test/helpers/mocks/stream.js' {
  declare module.exports: $Exports<'forever/test/helpers/mocks/stream'>;
}
declare module 'forever/test/worker/multiple-workers-test.js' {
  declare module.exports: $Exports<'forever/test/worker/multiple-workers-test'>;
}
declare module 'forever/test/worker/simple-test.js' {
  declare module.exports: $Exports<'forever/test/worker/simple-test'>;
}
