// flow-typed signature: b1aab418ed61221effcbf014ddbb12b6
// flow-typed version: <<STUB>>/gemini_v4.18.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gemini'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gemini' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gemini/api' {
  declare module.exports: any;
}

declare module 'gemini/lib/browser-pool/basic-pool' {
  declare module.exports: any;
}

declare module 'gemini/lib/browser-pool/caching-pool' {
  declare module.exports: any;
}

declare module 'gemini/lib/browser-pool/index' {
  declare module.exports: any;
}

declare module 'gemini/lib/browser-pool/limited-pool' {
  declare module.exports: any;
}

declare module 'gemini/lib/browser-pool/limited-use-set' {
  declare module.exports: any;
}

declare module 'gemini/lib/browser-pool/per-browser-limited-pool' {
  declare module.exports: any;
}

declare module 'gemini/lib/browser-pool/pool' {
  declare module.exports: any;
}

declare module 'gemini/lib/browser/browser' {
  declare module.exports: any;
}

declare module 'gemini/lib/browser/camera' {
  declare module.exports: any;
}

declare module 'gemini/lib/browser/client-bridge' {
  declare module.exports: any;
}

declare module 'gemini/lib/browser/client-scripts/gemini.calibrate.min' {
  declare module.exports: any;
}

declare module 'gemini/lib/browser/client-scripts/gemini.coverage' {
  declare module.exports: any;
}

declare module 'gemini/lib/browser/client-scripts/gemini' {
  declare module.exports: any;
}

declare module 'gemini/lib/browser/client-scripts/lib.compat' {
  declare module.exports: any;
}

declare module 'gemini/lib/browser/client-scripts/lib.native' {
  declare module.exports: any;
}

declare module 'gemini/lib/browser/client-scripts/polyfills/getComputedStyle' {
  declare module.exports: any;
}

declare module 'gemini/lib/browser/client-scripts/polyfills/matchMedia' {
  declare module.exports: any;
}

declare module 'gemini/lib/browser/client-scripts/rect' {
  declare module.exports: any;
}

declare module 'gemini/lib/browser/client-scripts/util' {
  declare module.exports: any;
}

declare module 'gemini/lib/browser/existing-browser' {
  declare module.exports: any;
}

declare module 'gemini/lib/browser/index' {
  declare module.exports: any;
}

declare module 'gemini/lib/browser/new-browser' {
  declare module.exports: any;
}

declare module 'gemini/lib/browser/util' {
  declare module.exports: any;
}

declare module 'gemini/lib/browser/wd-bluebird' {
  declare module.exports: any;
}

declare module 'gemini/lib/calibrator' {
  declare module.exports: any;
}

declare module 'gemini/lib/capture-session/coord-validator/errors/height-viewport-error' {
  declare module.exports: any;
}

declare module 'gemini/lib/capture-session/coord-validator/errors/offset-viewport-error' {
  declare module.exports: any;
}

declare module 'gemini/lib/capture-session/coord-validator/index' {
  declare module.exports: any;
}

declare module 'gemini/lib/capture-session/index' {
  declare module.exports: any;
}

declare module 'gemini/lib/capture-session/viewport' {
  declare module.exports: any;
}

declare module 'gemini/lib/cli/deprecations' {
  declare module.exports: any;
}

declare module 'gemini/lib/cli/errors' {
  declare module.exports: any;
}

declare module 'gemini/lib/cli/index' {
  declare module.exports: any;
}

declare module 'gemini/lib/config/browser-config' {
  declare module.exports: any;
}

declare module 'gemini/lib/config/browser-options' {
  declare module.exports: any;
}

declare module 'gemini/lib/config/config-reader' {
  declare module.exports: any;
}

declare module 'gemini/lib/config/index' {
  declare module.exports: any;
}

declare module 'gemini/lib/config/options' {
  declare module.exports: any;
}

declare module 'gemini/lib/config/util' {
  declare module.exports: any;
}

declare module 'gemini/lib/constants/events' {
  declare module.exports: any;
}

declare module 'gemini/lib/constants/wd-errors' {
  declare module.exports: any;
}

declare module 'gemini/lib/coverage-level' {
  declare module.exports: any;
}

declare module 'gemini/lib/coverage' {
  declare module.exports: any;
}

declare module 'gemini/lib/errors/cancelled-error' {
  declare module.exports: any;
}

declare module 'gemini/lib/errors/gemini-error' {
  declare module.exports: any;
}

declare module 'gemini/lib/errors/no-ref-image-error' {
  declare module.exports: any;
}

declare module 'gemini/lib/errors/state-error' {
  declare module.exports: any;
}

declare module 'gemini/lib/errors/utils' {
  declare module.exports: any;
}

declare module 'gemini/lib/gemini' {
  declare module.exports: any;
}

declare module 'gemini/lib/image/index' {
  declare module.exports: any;
}

declare module 'gemini/lib/image/safe-rect' {
  declare module.exports: any;
}

declare module 'gemini/lib/passthrough-emitter' {
  declare module.exports: any;
}

declare module 'gemini/lib/public-api' {
  declare module.exports: any;
}

declare module 'gemini/lib/reporters/flat-factory/flat-verbose' {
  declare module.exports: any;
}

declare module 'gemini/lib/reporters/flat-factory/flat' {
  declare module.exports: any;
}

declare module 'gemini/lib/reporters/flat-factory/index' {
  declare module.exports: any;
}

declare module 'gemini/lib/reporters/flat' {
  declare module.exports: any;
}

declare module 'gemini/lib/reporters/html/index' {
  declare module.exports: any;
}

declare module 'gemini/lib/reporters/html/lib' {
  declare module.exports: any;
}

declare module 'gemini/lib/reporters/html/static/report.min' {
  declare module.exports: any;
}

declare module 'gemini/lib/reporters/html/view-model' {
  declare module.exports: any;
}

declare module 'gemini/lib/reporters/html/view' {
  declare module.exports: any;
}

declare module 'gemini/lib/reporters/vflat' {
  declare module.exports: any;
}

declare module 'gemini/lib/runner/browser-runner/browser-agent' {
  declare module.exports: any;
}

declare module 'gemini/lib/runner/browser-runner/index' {
  declare module.exports: any;
}

declare module 'gemini/lib/runner/index' {
  declare module.exports: any;
}

declare module 'gemini/lib/runner/runner' {
  declare module.exports: any;
}

declare module 'gemini/lib/runner/state-runner/disabled-state-runner' {
  declare module.exports: any;
}

declare module 'gemini/lib/runner/state-runner/index' {
  declare module.exports: any;
}

declare module 'gemini/lib/runner/state-runner/state-runner' {
  declare module.exports: any;
}

declare module 'gemini/lib/runner/suite-runner/index' {
  declare module.exports: any;
}

declare module 'gemini/lib/runner/suite-runner/insistent-suite-runner' {
  declare module.exports: any;
}

declare module 'gemini/lib/runner/suite-runner/regular-suite-runner' {
  declare module.exports: any;
}

declare module 'gemini/lib/runner/suite-runner/skipped-suite-runner' {
  declare module.exports: any;
}

declare module 'gemini/lib/runner/suite-runner/stateless-suite-runner' {
  declare module.exports: any;
}

declare module 'gemini/lib/runner/suite-runner/suite-runner' {
  declare module.exports: any;
}

declare module 'gemini/lib/signal-handler' {
  declare module.exports: any;
}

declare module 'gemini/lib/state-processor/capture-processor/capture-processor' {
  declare module.exports: any;
}

declare module 'gemini/lib/state-processor/capture-processor/screen-updater/diff-screen-updater' {
  declare module.exports: any;
}

declare module 'gemini/lib/state-processor/capture-processor/screen-updater/index' {
  declare module.exports: any;
}

declare module 'gemini/lib/state-processor/capture-processor/screen-updater/meta-screen-updater' {
  declare module.exports: any;
}

declare module 'gemini/lib/state-processor/capture-processor/screen-updater/new-screen-updater' {
  declare module.exports: any;
}

declare module 'gemini/lib/state-processor/capture-processor/screen-updater/screen-updater' {
  declare module.exports: any;
}

declare module 'gemini/lib/state-processor/capture-processor/tester' {
  declare module.exports: any;
}

declare module 'gemini/lib/state-processor/index' {
  declare module.exports: any;
}

declare module 'gemini/lib/state-processor/job' {
  declare module.exports: any;
}

declare module 'gemini/lib/state-processor/state-processor' {
  declare module.exports: any;
}

declare module 'gemini/lib/state-processor/test-state-processor' {
  declare module.exports: any;
}

declare module 'gemini/lib/state-processor/update-state-processor' {
  declare module.exports: any;
}

declare module 'gemini/lib/state' {
  declare module.exports: any;
}

declare module 'gemini/lib/stats' {
  declare module.exports: any;
}

declare module 'gemini/lib/suite-collection' {
  declare module.exports: any;
}

declare module 'gemini/lib/suite-monitor' {
  declare module.exports: any;
}

declare module 'gemini/lib/suite-util' {
  declare module.exports: any;
}

declare module 'gemini/lib/suite' {
  declare module.exports: any;
}

declare module 'gemini/lib/temp' {
  declare module.exports: any;
}

declare module 'gemini/lib/test-counter' {
  declare module.exports: any;
}

declare module 'gemini/lib/test-reader' {
  declare module.exports: any;
}

declare module 'gemini/lib/tests-api/actions-builder' {
  declare module.exports: any;
}

declare module 'gemini/lib/tests-api/find-func' {
  declare module.exports: any;
}

declare module 'gemini/lib/tests-api/index' {
  declare module.exports: any;
}

declare module 'gemini/lib/tests-api/keys-codes' {
  declare module.exports: any;
}

declare module 'gemini/lib/tests-api/suite-builder' {
  declare module.exports: any;
}

declare module 'gemini/lib/typedefs' {
  declare module.exports: any;
}

declare module 'gemini/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gemini/api.js' {
  declare module.exports: $Exports<'gemini/api'>;
}
declare module 'gemini/lib/browser-pool/basic-pool.js' {
  declare module.exports: $Exports<'gemini/lib/browser-pool/basic-pool'>;
}
declare module 'gemini/lib/browser-pool/caching-pool.js' {
  declare module.exports: $Exports<'gemini/lib/browser-pool/caching-pool'>;
}
declare module 'gemini/lib/browser-pool/index.js' {
  declare module.exports: $Exports<'gemini/lib/browser-pool/index'>;
}
declare module 'gemini/lib/browser-pool/limited-pool.js' {
  declare module.exports: $Exports<'gemini/lib/browser-pool/limited-pool'>;
}
declare module 'gemini/lib/browser-pool/limited-use-set.js' {
  declare module.exports: $Exports<'gemini/lib/browser-pool/limited-use-set'>;
}
declare module 'gemini/lib/browser-pool/per-browser-limited-pool.js' {
  declare module.exports: $Exports<'gemini/lib/browser-pool/per-browser-limited-pool'>;
}
declare module 'gemini/lib/browser-pool/pool.js' {
  declare module.exports: $Exports<'gemini/lib/browser-pool/pool'>;
}
declare module 'gemini/lib/browser/browser.js' {
  declare module.exports: $Exports<'gemini/lib/browser/browser'>;
}
declare module 'gemini/lib/browser/camera.js' {
  declare module.exports: $Exports<'gemini/lib/browser/camera'>;
}
declare module 'gemini/lib/browser/client-bridge.js' {
  declare module.exports: $Exports<'gemini/lib/browser/client-bridge'>;
}
declare module 'gemini/lib/browser/client-scripts/gemini.calibrate.min.js' {
  declare module.exports: $Exports<'gemini/lib/browser/client-scripts/gemini.calibrate.min'>;
}
declare module 'gemini/lib/browser/client-scripts/gemini.coverage.js' {
  declare module.exports: $Exports<'gemini/lib/browser/client-scripts/gemini.coverage'>;
}
declare module 'gemini/lib/browser/client-scripts/gemini.js' {
  declare module.exports: $Exports<'gemini/lib/browser/client-scripts/gemini'>;
}
declare module 'gemini/lib/browser/client-scripts/lib.compat.js' {
  declare module.exports: $Exports<'gemini/lib/browser/client-scripts/lib.compat'>;
}
declare module 'gemini/lib/browser/client-scripts/lib.native.js' {
  declare module.exports: $Exports<'gemini/lib/browser/client-scripts/lib.native'>;
}
declare module 'gemini/lib/browser/client-scripts/polyfills/getComputedStyle.js' {
  declare module.exports: $Exports<'gemini/lib/browser/client-scripts/polyfills/getComputedStyle'>;
}
declare module 'gemini/lib/browser/client-scripts/polyfills/matchMedia.js' {
  declare module.exports: $Exports<'gemini/lib/browser/client-scripts/polyfills/matchMedia'>;
}
declare module 'gemini/lib/browser/client-scripts/rect.js' {
  declare module.exports: $Exports<'gemini/lib/browser/client-scripts/rect'>;
}
declare module 'gemini/lib/browser/client-scripts/util.js' {
  declare module.exports: $Exports<'gemini/lib/browser/client-scripts/util'>;
}
declare module 'gemini/lib/browser/existing-browser.js' {
  declare module.exports: $Exports<'gemini/lib/browser/existing-browser'>;
}
declare module 'gemini/lib/browser/index.js' {
  declare module.exports: $Exports<'gemini/lib/browser/index'>;
}
declare module 'gemini/lib/browser/new-browser.js' {
  declare module.exports: $Exports<'gemini/lib/browser/new-browser'>;
}
declare module 'gemini/lib/browser/util.js' {
  declare module.exports: $Exports<'gemini/lib/browser/util'>;
}
declare module 'gemini/lib/browser/wd-bluebird.js' {
  declare module.exports: $Exports<'gemini/lib/browser/wd-bluebird'>;
}
declare module 'gemini/lib/calibrator.js' {
  declare module.exports: $Exports<'gemini/lib/calibrator'>;
}
declare module 'gemini/lib/capture-session/coord-validator/errors/height-viewport-error.js' {
  declare module.exports: $Exports<'gemini/lib/capture-session/coord-validator/errors/height-viewport-error'>;
}
declare module 'gemini/lib/capture-session/coord-validator/errors/offset-viewport-error.js' {
  declare module.exports: $Exports<'gemini/lib/capture-session/coord-validator/errors/offset-viewport-error'>;
}
declare module 'gemini/lib/capture-session/coord-validator/index.js' {
  declare module.exports: $Exports<'gemini/lib/capture-session/coord-validator/index'>;
}
declare module 'gemini/lib/capture-session/index.js' {
  declare module.exports: $Exports<'gemini/lib/capture-session/index'>;
}
declare module 'gemini/lib/capture-session/viewport.js' {
  declare module.exports: $Exports<'gemini/lib/capture-session/viewport'>;
}
declare module 'gemini/lib/cli/deprecations.js' {
  declare module.exports: $Exports<'gemini/lib/cli/deprecations'>;
}
declare module 'gemini/lib/cli/errors.js' {
  declare module.exports: $Exports<'gemini/lib/cli/errors'>;
}
declare module 'gemini/lib/cli/index.js' {
  declare module.exports: $Exports<'gemini/lib/cli/index'>;
}
declare module 'gemini/lib/config/browser-config.js' {
  declare module.exports: $Exports<'gemini/lib/config/browser-config'>;
}
declare module 'gemini/lib/config/browser-options.js' {
  declare module.exports: $Exports<'gemini/lib/config/browser-options'>;
}
declare module 'gemini/lib/config/config-reader.js' {
  declare module.exports: $Exports<'gemini/lib/config/config-reader'>;
}
declare module 'gemini/lib/config/index.js' {
  declare module.exports: $Exports<'gemini/lib/config/index'>;
}
declare module 'gemini/lib/config/options.js' {
  declare module.exports: $Exports<'gemini/lib/config/options'>;
}
declare module 'gemini/lib/config/util.js' {
  declare module.exports: $Exports<'gemini/lib/config/util'>;
}
declare module 'gemini/lib/constants/events.js' {
  declare module.exports: $Exports<'gemini/lib/constants/events'>;
}
declare module 'gemini/lib/constants/wd-errors.js' {
  declare module.exports: $Exports<'gemini/lib/constants/wd-errors'>;
}
declare module 'gemini/lib/coverage-level.js' {
  declare module.exports: $Exports<'gemini/lib/coverage-level'>;
}
declare module 'gemini/lib/coverage.js' {
  declare module.exports: $Exports<'gemini/lib/coverage'>;
}
declare module 'gemini/lib/errors/cancelled-error.js' {
  declare module.exports: $Exports<'gemini/lib/errors/cancelled-error'>;
}
declare module 'gemini/lib/errors/gemini-error.js' {
  declare module.exports: $Exports<'gemini/lib/errors/gemini-error'>;
}
declare module 'gemini/lib/errors/no-ref-image-error.js' {
  declare module.exports: $Exports<'gemini/lib/errors/no-ref-image-error'>;
}
declare module 'gemini/lib/errors/state-error.js' {
  declare module.exports: $Exports<'gemini/lib/errors/state-error'>;
}
declare module 'gemini/lib/errors/utils.js' {
  declare module.exports: $Exports<'gemini/lib/errors/utils'>;
}
declare module 'gemini/lib/gemini.js' {
  declare module.exports: $Exports<'gemini/lib/gemini'>;
}
declare module 'gemini/lib/image/index.js' {
  declare module.exports: $Exports<'gemini/lib/image/index'>;
}
declare module 'gemini/lib/image/safe-rect.js' {
  declare module.exports: $Exports<'gemini/lib/image/safe-rect'>;
}
declare module 'gemini/lib/passthrough-emitter.js' {
  declare module.exports: $Exports<'gemini/lib/passthrough-emitter'>;
}
declare module 'gemini/lib/public-api.js' {
  declare module.exports: $Exports<'gemini/lib/public-api'>;
}
declare module 'gemini/lib/reporters/flat-factory/flat-verbose.js' {
  declare module.exports: $Exports<'gemini/lib/reporters/flat-factory/flat-verbose'>;
}
declare module 'gemini/lib/reporters/flat-factory/flat.js' {
  declare module.exports: $Exports<'gemini/lib/reporters/flat-factory/flat'>;
}
declare module 'gemini/lib/reporters/flat-factory/index.js' {
  declare module.exports: $Exports<'gemini/lib/reporters/flat-factory/index'>;
}
declare module 'gemini/lib/reporters/flat.js' {
  declare module.exports: $Exports<'gemini/lib/reporters/flat'>;
}
declare module 'gemini/lib/reporters/html/index.js' {
  declare module.exports: $Exports<'gemini/lib/reporters/html/index'>;
}
declare module 'gemini/lib/reporters/html/lib.js' {
  declare module.exports: $Exports<'gemini/lib/reporters/html/lib'>;
}
declare module 'gemini/lib/reporters/html/static/report.min.js' {
  declare module.exports: $Exports<'gemini/lib/reporters/html/static/report.min'>;
}
declare module 'gemini/lib/reporters/html/view-model.js' {
  declare module.exports: $Exports<'gemini/lib/reporters/html/view-model'>;
}
declare module 'gemini/lib/reporters/html/view.js' {
  declare module.exports: $Exports<'gemini/lib/reporters/html/view'>;
}
declare module 'gemini/lib/reporters/vflat.js' {
  declare module.exports: $Exports<'gemini/lib/reporters/vflat'>;
}
declare module 'gemini/lib/runner/browser-runner/browser-agent.js' {
  declare module.exports: $Exports<'gemini/lib/runner/browser-runner/browser-agent'>;
}
declare module 'gemini/lib/runner/browser-runner/index.js' {
  declare module.exports: $Exports<'gemini/lib/runner/browser-runner/index'>;
}
declare module 'gemini/lib/runner/index.js' {
  declare module.exports: $Exports<'gemini/lib/runner/index'>;
}
declare module 'gemini/lib/runner/runner.js' {
  declare module.exports: $Exports<'gemini/lib/runner/runner'>;
}
declare module 'gemini/lib/runner/state-runner/disabled-state-runner.js' {
  declare module.exports: $Exports<'gemini/lib/runner/state-runner/disabled-state-runner'>;
}
declare module 'gemini/lib/runner/state-runner/index.js' {
  declare module.exports: $Exports<'gemini/lib/runner/state-runner/index'>;
}
declare module 'gemini/lib/runner/state-runner/state-runner.js' {
  declare module.exports: $Exports<'gemini/lib/runner/state-runner/state-runner'>;
}
declare module 'gemini/lib/runner/suite-runner/index.js' {
  declare module.exports: $Exports<'gemini/lib/runner/suite-runner/index'>;
}
declare module 'gemini/lib/runner/suite-runner/insistent-suite-runner.js' {
  declare module.exports: $Exports<'gemini/lib/runner/suite-runner/insistent-suite-runner'>;
}
declare module 'gemini/lib/runner/suite-runner/regular-suite-runner.js' {
  declare module.exports: $Exports<'gemini/lib/runner/suite-runner/regular-suite-runner'>;
}
declare module 'gemini/lib/runner/suite-runner/skipped-suite-runner.js' {
  declare module.exports: $Exports<'gemini/lib/runner/suite-runner/skipped-suite-runner'>;
}
declare module 'gemini/lib/runner/suite-runner/stateless-suite-runner.js' {
  declare module.exports: $Exports<'gemini/lib/runner/suite-runner/stateless-suite-runner'>;
}
declare module 'gemini/lib/runner/suite-runner/suite-runner.js' {
  declare module.exports: $Exports<'gemini/lib/runner/suite-runner/suite-runner'>;
}
declare module 'gemini/lib/signal-handler.js' {
  declare module.exports: $Exports<'gemini/lib/signal-handler'>;
}
declare module 'gemini/lib/state-processor/capture-processor/capture-processor.js' {
  declare module.exports: $Exports<'gemini/lib/state-processor/capture-processor/capture-processor'>;
}
declare module 'gemini/lib/state-processor/capture-processor/screen-updater/diff-screen-updater.js' {
  declare module.exports: $Exports<'gemini/lib/state-processor/capture-processor/screen-updater/diff-screen-updater'>;
}
declare module 'gemini/lib/state-processor/capture-processor/screen-updater/index.js' {
  declare module.exports: $Exports<'gemini/lib/state-processor/capture-processor/screen-updater/index'>;
}
declare module 'gemini/lib/state-processor/capture-processor/screen-updater/meta-screen-updater.js' {
  declare module.exports: $Exports<'gemini/lib/state-processor/capture-processor/screen-updater/meta-screen-updater'>;
}
declare module 'gemini/lib/state-processor/capture-processor/screen-updater/new-screen-updater.js' {
  declare module.exports: $Exports<'gemini/lib/state-processor/capture-processor/screen-updater/new-screen-updater'>;
}
declare module 'gemini/lib/state-processor/capture-processor/screen-updater/screen-updater.js' {
  declare module.exports: $Exports<'gemini/lib/state-processor/capture-processor/screen-updater/screen-updater'>;
}
declare module 'gemini/lib/state-processor/capture-processor/tester.js' {
  declare module.exports: $Exports<'gemini/lib/state-processor/capture-processor/tester'>;
}
declare module 'gemini/lib/state-processor/index.js' {
  declare module.exports: $Exports<'gemini/lib/state-processor/index'>;
}
declare module 'gemini/lib/state-processor/job.js' {
  declare module.exports: $Exports<'gemini/lib/state-processor/job'>;
}
declare module 'gemini/lib/state-processor/state-processor.js' {
  declare module.exports: $Exports<'gemini/lib/state-processor/state-processor'>;
}
declare module 'gemini/lib/state-processor/test-state-processor.js' {
  declare module.exports: $Exports<'gemini/lib/state-processor/test-state-processor'>;
}
declare module 'gemini/lib/state-processor/update-state-processor.js' {
  declare module.exports: $Exports<'gemini/lib/state-processor/update-state-processor'>;
}
declare module 'gemini/lib/state.js' {
  declare module.exports: $Exports<'gemini/lib/state'>;
}
declare module 'gemini/lib/stats.js' {
  declare module.exports: $Exports<'gemini/lib/stats'>;
}
declare module 'gemini/lib/suite-collection.js' {
  declare module.exports: $Exports<'gemini/lib/suite-collection'>;
}
declare module 'gemini/lib/suite-monitor.js' {
  declare module.exports: $Exports<'gemini/lib/suite-monitor'>;
}
declare module 'gemini/lib/suite-util.js' {
  declare module.exports: $Exports<'gemini/lib/suite-util'>;
}
declare module 'gemini/lib/suite.js' {
  declare module.exports: $Exports<'gemini/lib/suite'>;
}
declare module 'gemini/lib/temp.js' {
  declare module.exports: $Exports<'gemini/lib/temp'>;
}
declare module 'gemini/lib/test-counter.js' {
  declare module.exports: $Exports<'gemini/lib/test-counter'>;
}
declare module 'gemini/lib/test-reader.js' {
  declare module.exports: $Exports<'gemini/lib/test-reader'>;
}
declare module 'gemini/lib/tests-api/actions-builder.js' {
  declare module.exports: $Exports<'gemini/lib/tests-api/actions-builder'>;
}
declare module 'gemini/lib/tests-api/find-func.js' {
  declare module.exports: $Exports<'gemini/lib/tests-api/find-func'>;
}
declare module 'gemini/lib/tests-api/index.js' {
  declare module.exports: $Exports<'gemini/lib/tests-api/index'>;
}
declare module 'gemini/lib/tests-api/keys-codes.js' {
  declare module.exports: $Exports<'gemini/lib/tests-api/keys-codes'>;
}
declare module 'gemini/lib/tests-api/suite-builder.js' {
  declare module.exports: $Exports<'gemini/lib/tests-api/suite-builder'>;
}
declare module 'gemini/lib/typedefs.js' {
  declare module.exports: $Exports<'gemini/lib/typedefs'>;
}
declare module 'gemini/lib/utils.js' {
  declare module.exports: $Exports<'gemini/lib/utils'>;
}
