// flow-typed signature: b0cdbddfb5bdc30126f430b9b70e324b
// flow-typed version: <<STUB>>/gemini-teamcity_v2.1.3/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gemini-teamcity'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gemini-teamcity' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gemini-teamcity/lib/plugin' {
  declare module.exports: any;
}

declare module 'gemini-teamcity/lib/utils' {
  declare module.exports: any;
}

declare module 'gemini-teamcity/test/plugin' {
  declare module.exports: any;
}

declare module 'gemini-teamcity/test/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gemini-teamcity/lib/plugin.js' {
  declare module.exports: $Exports<'gemini-teamcity/lib/plugin'>;
}
declare module 'gemini-teamcity/lib/utils.js' {
  declare module.exports: $Exports<'gemini-teamcity/lib/utils'>;
}
declare module 'gemini-teamcity/test/plugin.js' {
  declare module.exports: $Exports<'gemini-teamcity/test/plugin'>;
}
declare module 'gemini-teamcity/test/utils.js' {
  declare module.exports: $Exports<'gemini-teamcity/test/utils'>;
}
