// flow-typed signature: 3462958a468923e06b1ae31fa5d3f6dc
// flow-typed version: <<STUB>>/generator-ring-ui_v1.0.35/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'generator-ring-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'generator-ring-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'generator-ring-ui/app/index' {
  declare module.exports: any;
}

declare module 'generator-ring-ui/app/templates/karma.conf' {
  declare module.exports: any;
}

declare module 'generator-ring-ui/app/templates/postcss.config' {
  declare module.exports: any;
}

declare module 'generator-ring-ui/app/templates/src/components/app/app-root' {
  declare module.exports: any;
}

declare module 'generator-ring-ui/app/templates/src/components/app/app-root.test' {
  declare module.exports: any;
}

declare module 'generator-ring-ui/app/templates/src/components/app/app' {
  declare module.exports: any;
}

declare module 'generator-ring-ui/app/templates/webpack.config' {
  declare module.exports: any;
}

declare module 'generator-ring-ui/es6/index' {
  declare module.exports: any;
}

declare module 'generator-ring-ui/es6/templates/component' {
  declare module.exports: any;
}

declare module 'generator-ring-ui/es6/templates/component.test' {
  declare module.exports: any;
}

declare module 'generator-ring-ui/generate-component' {
  declare module.exports: any;
}

declare module 'generator-ring-ui/ng/index' {
  declare module.exports: any;
}

declare module 'generator-ring-ui/ng/templates/component.gemini' {
  declare module.exports: any;
}

declare module 'generator-ring-ui/ng/templates/component' {
  declare module.exports: any;
}

declare module 'generator-ring-ui/ng/templates/component.test' {
  declare module.exports: any;
}

declare module 'generator-ring-ui/react/index' {
  declare module.exports: any;
}

declare module 'generator-ring-ui/react/templates/component.gemini' {
  declare module.exports: any;
}

declare module 'generator-ring-ui/react/templates/component' {
  declare module.exports: any;
}

declare module 'generator-ring-ui/react/templates/component.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'generator-ring-ui/app/index.js' {
  declare module.exports: $Exports<'generator-ring-ui/app/index'>;
}
declare module 'generator-ring-ui/app/templates/karma.conf.js' {
  declare module.exports: $Exports<'generator-ring-ui/app/templates/karma.conf'>;
}
declare module 'generator-ring-ui/app/templates/postcss.config.js' {
  declare module.exports: $Exports<'generator-ring-ui/app/templates/postcss.config'>;
}
declare module 'generator-ring-ui/app/templates/src/components/app/app-root.js' {
  declare module.exports: $Exports<'generator-ring-ui/app/templates/src/components/app/app-root'>;
}
declare module 'generator-ring-ui/app/templates/src/components/app/app-root.test.js' {
  declare module.exports: $Exports<'generator-ring-ui/app/templates/src/components/app/app-root.test'>;
}
declare module 'generator-ring-ui/app/templates/src/components/app/app.js' {
  declare module.exports: $Exports<'generator-ring-ui/app/templates/src/components/app/app'>;
}
declare module 'generator-ring-ui/app/templates/webpack.config.js' {
  declare module.exports: $Exports<'generator-ring-ui/app/templates/webpack.config'>;
}
declare module 'generator-ring-ui/es6/index.js' {
  declare module.exports: $Exports<'generator-ring-ui/es6/index'>;
}
declare module 'generator-ring-ui/es6/templates/component.js' {
  declare module.exports: $Exports<'generator-ring-ui/es6/templates/component'>;
}
declare module 'generator-ring-ui/es6/templates/component.test.js' {
  declare module.exports: $Exports<'generator-ring-ui/es6/templates/component.test'>;
}
declare module 'generator-ring-ui/generate-component.js' {
  declare module.exports: $Exports<'generator-ring-ui/generate-component'>;
}
declare module 'generator-ring-ui/ng/index.js' {
  declare module.exports: $Exports<'generator-ring-ui/ng/index'>;
}
declare module 'generator-ring-ui/ng/templates/component.gemini.js' {
  declare module.exports: $Exports<'generator-ring-ui/ng/templates/component.gemini'>;
}
declare module 'generator-ring-ui/ng/templates/component.js' {
  declare module.exports: $Exports<'generator-ring-ui/ng/templates/component'>;
}
declare module 'generator-ring-ui/ng/templates/component.test.js' {
  declare module.exports: $Exports<'generator-ring-ui/ng/templates/component.test'>;
}
declare module 'generator-ring-ui/react/index.js' {
  declare module.exports: $Exports<'generator-ring-ui/react/index'>;
}
declare module 'generator-ring-ui/react/templates/component.gemini.js' {
  declare module.exports: $Exports<'generator-ring-ui/react/templates/component.gemini'>;
}
declare module 'generator-ring-ui/react/templates/component.js' {
  declare module.exports: $Exports<'generator-ring-ui/react/templates/component'>;
}
declare module 'generator-ring-ui/react/templates/component.test.js' {
  declare module.exports: $Exports<'generator-ring-ui/react/templates/component.test'>;
}
