// flow-typed signature: de530cb3478db276d155acad7c2e0fdf
// flow-typed version: <<STUB>>/jetbrains-logos_v1.1.51/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jetbrains-logos'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jetbrains-logos' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jetbrains-logos/logos' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jetbrains-logos/index' {
  declare module.exports: $Exports<'jetbrains-logos'>;
}
declare module 'jetbrains-logos/index.js' {
  declare module.exports: $Exports<'jetbrains-logos'>;
}
declare module 'jetbrains-logos/logos.js' {
  declare module.exports: $Exports<'jetbrains-logos/logos'>;
}
