// flow-typed signature: 7616a965a66ba2a23ad72f0fff0c29d7
// flow-typed version: <<STUB>>/jetbrains-icons_v1.0.38/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jetbrains-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jetbrains-icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'jetbrains-icons/index' {
  declare module.exports: $Exports<'jetbrains-icons'>;
}
declare module 'jetbrains-icons/index.js' {
  declare module.exports: $Exports<'jetbrains-icons'>;
}
