// flow-typed signature: 27dbe51fcd29c08b5eab3705eaa76486
// flow-typed version: <<STUB>>/karma-chai-plugins_v0.9.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-chai-plugins'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-chai-plugins' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-chai-plugins/chai-adapter' {
  declare module.exports: any;
}

declare module 'karma-chai-plugins/function-bind-polyfill' {
  declare module.exports: any;
}

declare module 'karma-chai-plugins/karma.conf' {
  declare module.exports: any;
}

declare module 'karma-chai-plugins/test/spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-chai-plugins/chai-adapter.js' {
  declare module.exports: $Exports<'karma-chai-plugins/chai-adapter'>;
}
declare module 'karma-chai-plugins/function-bind-polyfill.js' {
  declare module.exports: $Exports<'karma-chai-plugins/function-bind-polyfill'>;
}
declare module 'karma-chai-plugins/index' {
  declare module.exports: $Exports<'karma-chai-plugins'>;
}
declare module 'karma-chai-plugins/index.js' {
  declare module.exports: $Exports<'karma-chai-plugins'>;
}
declare module 'karma-chai-plugins/karma.conf.js' {
  declare module.exports: $Exports<'karma-chai-plugins/karma.conf'>;
}
declare module 'karma-chai-plugins/test/spec.js' {
  declare module.exports: $Exports<'karma-chai-plugins/test/spec'>;
}
