// flow-typed signature: 105e506738ad9067a1ba2f834feb57d2
// flow-typed version: <<STUB>>/karma-electron-launcher_v0.2.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-electron-launcher'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-electron-launcher' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-electron-launcher/runner.electron/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-electron-launcher/index' {
  declare module.exports: $Exports<'karma-electron-launcher'>;
}
declare module 'karma-electron-launcher/index.js' {
  declare module.exports: $Exports<'karma-electron-launcher'>;
}
declare module 'karma-electron-launcher/runner.electron/main.js' {
  declare module.exports: $Exports<'karma-electron-launcher/runner.electron/main'>;
}
