// flow-typed signature: bf5b9cbe5b519ec0fd79e60559737306
// flow-typed version: <<STUB>>/karma-webdriver-launcher_v1.0.4/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-webdriver-launcher'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-webdriver-launcher' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-webdriver-launcher/Gruntfile' {
  declare module.exports: any;
}

declare module 'karma-webdriver-launcher/examples/sauceLabs/karma.conf' {
  declare module.exports: any;
}

declare module 'karma-webdriver-launcher/examples/sauceLabs/tests/example.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-webdriver-launcher/Gruntfile.js' {
  declare module.exports: $Exports<'karma-webdriver-launcher/Gruntfile'>;
}
declare module 'karma-webdriver-launcher/examples/sauceLabs/karma.conf.js' {
  declare module.exports: $Exports<'karma-webdriver-launcher/examples/sauceLabs/karma.conf'>;
}
declare module 'karma-webdriver-launcher/examples/sauceLabs/tests/example.spec.js' {
  declare module.exports: $Exports<'karma-webdriver-launcher/examples/sauceLabs/tests/example.spec'>;
}
declare module 'karma-webdriver-launcher/index' {
  declare module.exports: $Exports<'karma-webdriver-launcher'>;
}
declare module 'karma-webdriver-launcher/index.js' {
  declare module.exports: $Exports<'karma-webdriver-launcher'>;
}
