// flow-typed signature: 2b79ee07b3fbc8703813e08fd3c25d11
// flow-typed version: <<STUB>>/karma-osx-reporter_v0.2.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-osx-reporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-osx-reporter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-osx-reporter/Gruntfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-osx-reporter/Gruntfile.js' {
  declare module.exports: $Exports<'karma-osx-reporter/Gruntfile'>;
}
declare module 'karma-osx-reporter/index' {
  declare module.exports: $Exports<'karma-osx-reporter'>;
}
declare module 'karma-osx-reporter/index.js' {
  declare module.exports: $Exports<'karma-osx-reporter'>;
}
