// flow-typed signature: de5499b17e50c30bfe1df920fa149f06
// flow-typed version: <<STUB>>/karma-coverage-html-index-reporter_v1.0.2/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-coverage-html-index-reporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-coverage-html-index-reporter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'karma-coverage-html-index-reporter/index' {
  declare module.exports: $Exports<'karma-coverage-html-index-reporter'>;
}
declare module 'karma-coverage-html-index-reporter/index.js' {
  declare module.exports: $Exports<'karma-coverage-html-index-reporter'>;
}
