// flow-typed signature: 713082dd0263eb6aa89de9f45f3e8c9e
// flow-typed version: <<STUB>>/mout_v1.0.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mout'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mout' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mout/array' {
  declare module.exports: any;
}

declare module 'mout/array/append' {
  declare module.exports: any;
}

declare module 'mout/array/collect' {
  declare module.exports: any;
}

declare module 'mout/array/combine' {
  declare module.exports: any;
}

declare module 'mout/array/compact' {
  declare module.exports: any;
}

declare module 'mout/array/contains' {
  declare module.exports: any;
}

declare module 'mout/array/difference' {
  declare module.exports: any;
}

declare module 'mout/array/equals' {
  declare module.exports: any;
}

declare module 'mout/array/every' {
  declare module.exports: any;
}

declare module 'mout/array/filter' {
  declare module.exports: any;
}

declare module 'mout/array/find' {
  declare module.exports: any;
}

declare module 'mout/array/findIndex' {
  declare module.exports: any;
}

declare module 'mout/array/findLast' {
  declare module.exports: any;
}

declare module 'mout/array/findLastIndex' {
  declare module.exports: any;
}

declare module 'mout/array/flatten' {
  declare module.exports: any;
}

declare module 'mout/array/forEach' {
  declare module.exports: any;
}

declare module 'mout/array/groupBy' {
  declare module.exports: any;
}

declare module 'mout/array/indexOf' {
  declare module.exports: any;
}

declare module 'mout/array/indicesOf' {
  declare module.exports: any;
}

declare module 'mout/array/insert' {
  declare module.exports: any;
}

declare module 'mout/array/intersection' {
  declare module.exports: any;
}

declare module 'mout/array/invoke' {
  declare module.exports: any;
}

declare module 'mout/array/join' {
  declare module.exports: any;
}

declare module 'mout/array/last' {
  declare module.exports: any;
}

declare module 'mout/array/lastIndexOf' {
  declare module.exports: any;
}

declare module 'mout/array/map' {
  declare module.exports: any;
}

declare module 'mout/array/max' {
  declare module.exports: any;
}

declare module 'mout/array/min' {
  declare module.exports: any;
}

declare module 'mout/array/pick' {
  declare module.exports: any;
}

declare module 'mout/array/pluck' {
  declare module.exports: any;
}

declare module 'mout/array/range' {
  declare module.exports: any;
}

declare module 'mout/array/reduce' {
  declare module.exports: any;
}

declare module 'mout/array/reduceRight' {
  declare module.exports: any;
}

declare module 'mout/array/reject' {
  declare module.exports: any;
}

declare module 'mout/array/remove' {
  declare module.exports: any;
}

declare module 'mout/array/removeAll' {
  declare module.exports: any;
}

declare module 'mout/array/reverse' {
  declare module.exports: any;
}

declare module 'mout/array/shuffle' {
  declare module.exports: any;
}

declare module 'mout/array/slice' {
  declare module.exports: any;
}

declare module 'mout/array/some' {
  declare module.exports: any;
}

declare module 'mout/array/sort' {
  declare module.exports: any;
}

declare module 'mout/array/sortBy' {
  declare module.exports: any;
}

declare module 'mout/array/split' {
  declare module.exports: any;
}

declare module 'mout/array/take' {
  declare module.exports: any;
}

declare module 'mout/array/toLookup' {
  declare module.exports: any;
}

declare module 'mout/array/union' {
  declare module.exports: any;
}

declare module 'mout/array/unique' {
  declare module.exports: any;
}

declare module 'mout/array/xor' {
  declare module.exports: any;
}

declare module 'mout/array/zip' {
  declare module.exports: any;
}

declare module 'mout/collection' {
  declare module.exports: any;
}

declare module 'mout/collection/contains' {
  declare module.exports: any;
}

declare module 'mout/collection/every' {
  declare module.exports: any;
}

declare module 'mout/collection/filter' {
  declare module.exports: any;
}

declare module 'mout/collection/find' {
  declare module.exports: any;
}

declare module 'mout/collection/forEach' {
  declare module.exports: any;
}

declare module 'mout/collection/make_' {
  declare module.exports: any;
}

declare module 'mout/collection/map' {
  declare module.exports: any;
}

declare module 'mout/collection/max' {
  declare module.exports: any;
}

declare module 'mout/collection/min' {
  declare module.exports: any;
}

declare module 'mout/collection/pluck' {
  declare module.exports: any;
}

declare module 'mout/collection/reduce' {
  declare module.exports: any;
}

declare module 'mout/collection/reject' {
  declare module.exports: any;
}

declare module 'mout/collection/size' {
  declare module.exports: any;
}

declare module 'mout/collection/some' {
  declare module.exports: any;
}

declare module 'mout/date' {
  declare module.exports: any;
}

declare module 'mout/date/dayOfTheYear' {
  declare module.exports: any;
}

declare module 'mout/date/diff' {
  declare module.exports: any;
}

declare module 'mout/date/i18n/de-DE' {
  declare module.exports: any;
}

declare module 'mout/date/i18n/en-US' {
  declare module.exports: any;
}

declare module 'mout/date/i18n/pt-BR' {
  declare module.exports: any;
}

declare module 'mout/date/i18n_' {
  declare module.exports: any;
}

declare module 'mout/date/isLeapYear' {
  declare module.exports: any;
}

declare module 'mout/date/isSame' {
  declare module.exports: any;
}

declare module 'mout/date/parseIso' {
  declare module.exports: any;
}

declare module 'mout/date/quarter' {
  declare module.exports: any;
}

declare module 'mout/date/startOf' {
  declare module.exports: any;
}

declare module 'mout/date/strftime' {
  declare module.exports: any;
}

declare module 'mout/date/timezoneAbbr' {
  declare module.exports: any;
}

declare module 'mout/date/timezoneOffset' {
  declare module.exports: any;
}

declare module 'mout/date/totalDaysInMonth' {
  declare module.exports: any;
}

declare module 'mout/date/totalDaysInYear' {
  declare module.exports: any;
}

declare module 'mout/date/weekOfTheYear' {
  declare module.exports: any;
}

declare module 'mout/function' {
  declare module.exports: any;
}

declare module 'mout/function/after' {
  declare module.exports: any;
}

declare module 'mout/function/awaitDelay' {
  declare module.exports: any;
}

declare module 'mout/function/bind' {
  declare module.exports: any;
}

declare module 'mout/function/compose' {
  declare module.exports: any;
}

declare module 'mout/function/constant' {
  declare module.exports: any;
}

declare module 'mout/function/debounce' {
  declare module.exports: any;
}

declare module 'mout/function/func' {
  declare module.exports: any;
}

declare module 'mout/function/identity' {
  declare module.exports: any;
}

declare module 'mout/function/makeIterator_' {
  declare module.exports: any;
}

declare module 'mout/function/memoize' {
  declare module.exports: any;
}

declare module 'mout/function/partial' {
  declare module.exports: any;
}

declare module 'mout/function/prop' {
  declare module.exports: any;
}

declare module 'mout/function/series' {
  declare module.exports: any;
}

declare module 'mout/function/throttle' {
  declare module.exports: any;
}

declare module 'mout/function/timeout' {
  declare module.exports: any;
}

declare module 'mout/function/times' {
  declare module.exports: any;
}

declare module 'mout/function/wrap' {
  declare module.exports: any;
}

declare module 'mout/lang' {
  declare module.exports: any;
}

declare module 'mout/lang/GLOBAL' {
  declare module.exports: any;
}

declare module 'mout/lang/clone' {
  declare module.exports: any;
}

declare module 'mout/lang/createObject' {
  declare module.exports: any;
}

declare module 'mout/lang/ctorApply' {
  declare module.exports: any;
}

declare module 'mout/lang/deepClone' {
  declare module.exports: any;
}

declare module 'mout/lang/deepEquals' {
  declare module.exports: any;
}

declare module 'mout/lang/defaults' {
  declare module.exports: any;
}

declare module 'mout/lang/inheritPrototype' {
  declare module.exports: any;
}

declare module 'mout/lang/is' {
  declare module.exports: any;
}

declare module 'mout/lang/isArguments' {
  declare module.exports: any;
}

declare module 'mout/lang/isArray' {
  declare module.exports: any;
}

declare module 'mout/lang/isBoolean' {
  declare module.exports: any;
}

declare module 'mout/lang/isDate' {
  declare module.exports: any;
}

declare module 'mout/lang/isEmpty' {
  declare module.exports: any;
}

declare module 'mout/lang/isFinite' {
  declare module.exports: any;
}

declare module 'mout/lang/isFunction' {
  declare module.exports: any;
}

declare module 'mout/lang/isInteger' {
  declare module.exports: any;
}

declare module 'mout/lang/isKind' {
  declare module.exports: any;
}

declare module 'mout/lang/isNaN' {
  declare module.exports: any;
}

declare module 'mout/lang/isNull' {
  declare module.exports: any;
}

declare module 'mout/lang/isNumber' {
  declare module.exports: any;
}

declare module 'mout/lang/isObject' {
  declare module.exports: any;
}

declare module 'mout/lang/isPlainObject' {
  declare module.exports: any;
}

declare module 'mout/lang/isPrimitive' {
  declare module.exports: any;
}

declare module 'mout/lang/isRegExp' {
  declare module.exports: any;
}

declare module 'mout/lang/isString' {
  declare module.exports: any;
}

declare module 'mout/lang/isUndefined' {
  declare module.exports: any;
}

declare module 'mout/lang/isnt' {
  declare module.exports: any;
}

declare module 'mout/lang/kindOf' {
  declare module.exports: any;
}

declare module 'mout/lang/toArray' {
  declare module.exports: any;
}

declare module 'mout/lang/toNumber' {
  declare module.exports: any;
}

declare module 'mout/lang/toString' {
  declare module.exports: any;
}

declare module 'mout/math' {
  declare module.exports: any;
}

declare module 'mout/math/ceil' {
  declare module.exports: any;
}

declare module 'mout/math/clamp' {
  declare module.exports: any;
}

declare module 'mout/math/countSteps' {
  declare module.exports: any;
}

declare module 'mout/math/floor' {
  declare module.exports: any;
}

declare module 'mout/math/inRange' {
  declare module.exports: any;
}

declare module 'mout/math/isNear' {
  declare module.exports: any;
}

declare module 'mout/math/lerp' {
  declare module.exports: any;
}

declare module 'mout/math/loop' {
  declare module.exports: any;
}

declare module 'mout/math/map' {
  declare module.exports: any;
}

declare module 'mout/math/norm' {
  declare module.exports: any;
}

declare module 'mout/math/overflow' {
  declare module.exports: any;
}

declare module 'mout/math/round' {
  declare module.exports: any;
}

declare module 'mout/number' {
  declare module.exports: any;
}

declare module 'mout/number/MAX_INT' {
  declare module.exports: any;
}

declare module 'mout/number/MAX_SAFE_INTEGER' {
  declare module.exports: any;
}

declare module 'mout/number/MAX_UINT' {
  declare module.exports: any;
}

declare module 'mout/number/MIN_INT' {
  declare module.exports: any;
}

declare module 'mout/number/abbreviate' {
  declare module.exports: any;
}

declare module 'mout/number/currencyFormat' {
  declare module.exports: any;
}

declare module 'mout/number/enforcePrecision' {
  declare module.exports: any;
}

declare module 'mout/number/isNaN' {
  declare module.exports: any;
}

declare module 'mout/number/nth' {
  declare module.exports: any;
}

declare module 'mout/number/ordinal' {
  declare module.exports: any;
}

declare module 'mout/number/pad' {
  declare module.exports: any;
}

declare module 'mout/number/rol' {
  declare module.exports: any;
}

declare module 'mout/number/ror' {
  declare module.exports: any;
}

declare module 'mout/number/sign' {
  declare module.exports: any;
}

declare module 'mout/number/toInt' {
  declare module.exports: any;
}

declare module 'mout/number/toUInt' {
  declare module.exports: any;
}

declare module 'mout/number/toUInt31' {
  declare module.exports: any;
}

declare module 'mout/object' {
  declare module.exports: any;
}

declare module 'mout/object/bindAll' {
  declare module.exports: any;
}

declare module 'mout/object/contains' {
  declare module.exports: any;
}

declare module 'mout/object/deepFillIn' {
  declare module.exports: any;
}

declare module 'mout/object/deepMatches' {
  declare module.exports: any;
}

declare module 'mout/object/deepMixIn' {
  declare module.exports: any;
}

declare module 'mout/object/equals' {
  declare module.exports: any;
}

declare module 'mout/object/every' {
  declare module.exports: any;
}

declare module 'mout/object/fillIn' {
  declare module.exports: any;
}

declare module 'mout/object/filter' {
  declare module.exports: any;
}

declare module 'mout/object/find' {
  declare module.exports: any;
}

declare module 'mout/object/flatten' {
  declare module.exports: any;
}

declare module 'mout/object/forIn' {
  declare module.exports: any;
}

declare module 'mout/object/forOwn' {
  declare module.exports: any;
}

declare module 'mout/object/functions' {
  declare module.exports: any;
}

declare module 'mout/object/get' {
  declare module.exports: any;
}

declare module 'mout/object/has' {
  declare module.exports: any;
}

declare module 'mout/object/hasOwn' {
  declare module.exports: any;
}

declare module 'mout/object/keys' {
  declare module.exports: any;
}

declare module 'mout/object/map' {
  declare module.exports: any;
}

declare module 'mout/object/matches' {
  declare module.exports: any;
}

declare module 'mout/object/max' {
  declare module.exports: any;
}

declare module 'mout/object/merge' {
  declare module.exports: any;
}

declare module 'mout/object/min' {
  declare module.exports: any;
}

declare module 'mout/object/mixIn' {
  declare module.exports: any;
}

declare module 'mout/object/namespace' {
  declare module.exports: any;
}

declare module 'mout/object/omit' {
  declare module.exports: any;
}

declare module 'mout/object/pick' {
  declare module.exports: any;
}

declare module 'mout/object/pluck' {
  declare module.exports: any;
}

declare module 'mout/object/reduce' {
  declare module.exports: any;
}

declare module 'mout/object/reject' {
  declare module.exports: any;
}

declare module 'mout/object/result' {
  declare module.exports: any;
}

declare module 'mout/object/set' {
  declare module.exports: any;
}

declare module 'mout/object/size' {
  declare module.exports: any;
}

declare module 'mout/object/some' {
  declare module.exports: any;
}

declare module 'mout/object/unset' {
  declare module.exports: any;
}

declare module 'mout/object/values' {
  declare module.exports: any;
}

declare module 'mout/queryString' {
  declare module.exports: any;
}

declare module 'mout/queryString/contains' {
  declare module.exports: any;
}

declare module 'mout/queryString/decode' {
  declare module.exports: any;
}

declare module 'mout/queryString/encode' {
  declare module.exports: any;
}

declare module 'mout/queryString/getParam' {
  declare module.exports: any;
}

declare module 'mout/queryString/getQuery' {
  declare module.exports: any;
}

declare module 'mout/queryString/parse' {
  declare module.exports: any;
}

declare module 'mout/queryString/setParam' {
  declare module.exports: any;
}

declare module 'mout/random' {
  declare module.exports: any;
}

declare module 'mout/random/choice' {
  declare module.exports: any;
}

declare module 'mout/random/guid' {
  declare module.exports: any;
}

declare module 'mout/random/rand' {
  declare module.exports: any;
}

declare module 'mout/random/randBit' {
  declare module.exports: any;
}

declare module 'mout/random/randBool' {
  declare module.exports: any;
}

declare module 'mout/random/randHex' {
  declare module.exports: any;
}

declare module 'mout/random/randInt' {
  declare module.exports: any;
}

declare module 'mout/random/randSign' {
  declare module.exports: any;
}

declare module 'mout/random/randString' {
  declare module.exports: any;
}

declare module 'mout/random/random' {
  declare module.exports: any;
}

declare module 'mout/src/array' {
  declare module.exports: any;
}

declare module 'mout/src/array/append' {
  declare module.exports: any;
}

declare module 'mout/src/array/collect' {
  declare module.exports: any;
}

declare module 'mout/src/array/combine' {
  declare module.exports: any;
}

declare module 'mout/src/array/compact' {
  declare module.exports: any;
}

declare module 'mout/src/array/contains' {
  declare module.exports: any;
}

declare module 'mout/src/array/difference' {
  declare module.exports: any;
}

declare module 'mout/src/array/equals' {
  declare module.exports: any;
}

declare module 'mout/src/array/every' {
  declare module.exports: any;
}

declare module 'mout/src/array/filter' {
  declare module.exports: any;
}

declare module 'mout/src/array/find' {
  declare module.exports: any;
}

declare module 'mout/src/array/findIndex' {
  declare module.exports: any;
}

declare module 'mout/src/array/findLast' {
  declare module.exports: any;
}

declare module 'mout/src/array/findLastIndex' {
  declare module.exports: any;
}

declare module 'mout/src/array/flatten' {
  declare module.exports: any;
}

declare module 'mout/src/array/forEach' {
  declare module.exports: any;
}

declare module 'mout/src/array/groupBy' {
  declare module.exports: any;
}

declare module 'mout/src/array/indexOf' {
  declare module.exports: any;
}

declare module 'mout/src/array/indicesOf' {
  declare module.exports: any;
}

declare module 'mout/src/array/insert' {
  declare module.exports: any;
}

declare module 'mout/src/array/intersection' {
  declare module.exports: any;
}

declare module 'mout/src/array/invoke' {
  declare module.exports: any;
}

declare module 'mout/src/array/join' {
  declare module.exports: any;
}

declare module 'mout/src/array/last' {
  declare module.exports: any;
}

declare module 'mout/src/array/lastIndexOf' {
  declare module.exports: any;
}

declare module 'mout/src/array/map' {
  declare module.exports: any;
}

declare module 'mout/src/array/max' {
  declare module.exports: any;
}

declare module 'mout/src/array/min' {
  declare module.exports: any;
}

declare module 'mout/src/array/pick' {
  declare module.exports: any;
}

declare module 'mout/src/array/pluck' {
  declare module.exports: any;
}

declare module 'mout/src/array/range' {
  declare module.exports: any;
}

declare module 'mout/src/array/reduce' {
  declare module.exports: any;
}

declare module 'mout/src/array/reduceRight' {
  declare module.exports: any;
}

declare module 'mout/src/array/reject' {
  declare module.exports: any;
}

declare module 'mout/src/array/remove' {
  declare module.exports: any;
}

declare module 'mout/src/array/removeAll' {
  declare module.exports: any;
}

declare module 'mout/src/array/reverse' {
  declare module.exports: any;
}

declare module 'mout/src/array/shuffle' {
  declare module.exports: any;
}

declare module 'mout/src/array/slice' {
  declare module.exports: any;
}

declare module 'mout/src/array/some' {
  declare module.exports: any;
}

declare module 'mout/src/array/sort' {
  declare module.exports: any;
}

declare module 'mout/src/array/sortBy' {
  declare module.exports: any;
}

declare module 'mout/src/array/split' {
  declare module.exports: any;
}

declare module 'mout/src/array/take' {
  declare module.exports: any;
}

declare module 'mout/src/array/toLookup' {
  declare module.exports: any;
}

declare module 'mout/src/array/union' {
  declare module.exports: any;
}

declare module 'mout/src/array/unique' {
  declare module.exports: any;
}

declare module 'mout/src/array/xor' {
  declare module.exports: any;
}

declare module 'mout/src/array/zip' {
  declare module.exports: any;
}

declare module 'mout/src/collection' {
  declare module.exports: any;
}

declare module 'mout/src/collection/contains' {
  declare module.exports: any;
}

declare module 'mout/src/collection/every' {
  declare module.exports: any;
}

declare module 'mout/src/collection/filter' {
  declare module.exports: any;
}

declare module 'mout/src/collection/find' {
  declare module.exports: any;
}

declare module 'mout/src/collection/forEach' {
  declare module.exports: any;
}

declare module 'mout/src/collection/make_' {
  declare module.exports: any;
}

declare module 'mout/src/collection/map' {
  declare module.exports: any;
}

declare module 'mout/src/collection/max' {
  declare module.exports: any;
}

declare module 'mout/src/collection/min' {
  declare module.exports: any;
}

declare module 'mout/src/collection/pluck' {
  declare module.exports: any;
}

declare module 'mout/src/collection/reduce' {
  declare module.exports: any;
}

declare module 'mout/src/collection/reject' {
  declare module.exports: any;
}

declare module 'mout/src/collection/size' {
  declare module.exports: any;
}

declare module 'mout/src/collection/some' {
  declare module.exports: any;
}

declare module 'mout/src/date' {
  declare module.exports: any;
}

declare module 'mout/src/date/dayOfTheYear' {
  declare module.exports: any;
}

declare module 'mout/src/date/diff' {
  declare module.exports: any;
}

declare module 'mout/src/date/i18n/de-DE' {
  declare module.exports: any;
}

declare module 'mout/src/date/i18n/en-US' {
  declare module.exports: any;
}

declare module 'mout/src/date/i18n/pt-BR' {
  declare module.exports: any;
}

declare module 'mout/src/date/i18n_' {
  declare module.exports: any;
}

declare module 'mout/src/date/isLeapYear' {
  declare module.exports: any;
}

declare module 'mout/src/date/isSame' {
  declare module.exports: any;
}

declare module 'mout/src/date/parseIso' {
  declare module.exports: any;
}

declare module 'mout/src/date/quarter' {
  declare module.exports: any;
}

declare module 'mout/src/date/startOf' {
  declare module.exports: any;
}

declare module 'mout/src/date/strftime' {
  declare module.exports: any;
}

declare module 'mout/src/date/timezoneAbbr' {
  declare module.exports: any;
}

declare module 'mout/src/date/timezoneOffset' {
  declare module.exports: any;
}

declare module 'mout/src/date/totalDaysInMonth' {
  declare module.exports: any;
}

declare module 'mout/src/date/totalDaysInYear' {
  declare module.exports: any;
}

declare module 'mout/src/date/weekOfTheYear' {
  declare module.exports: any;
}

declare module 'mout/src/function' {
  declare module.exports: any;
}

declare module 'mout/src/function/after' {
  declare module.exports: any;
}

declare module 'mout/src/function/awaitDelay' {
  declare module.exports: any;
}

declare module 'mout/src/function/bind' {
  declare module.exports: any;
}

declare module 'mout/src/function/compose' {
  declare module.exports: any;
}

declare module 'mout/src/function/constant' {
  declare module.exports: any;
}

declare module 'mout/src/function/debounce' {
  declare module.exports: any;
}

declare module 'mout/src/function/func' {
  declare module.exports: any;
}

declare module 'mout/src/function/identity' {
  declare module.exports: any;
}

declare module 'mout/src/function/makeIterator_' {
  declare module.exports: any;
}

declare module 'mout/src/function/memoize' {
  declare module.exports: any;
}

declare module 'mout/src/function/partial' {
  declare module.exports: any;
}

declare module 'mout/src/function/prop' {
  declare module.exports: any;
}

declare module 'mout/src/function/series' {
  declare module.exports: any;
}

declare module 'mout/src/function/throttle' {
  declare module.exports: any;
}

declare module 'mout/src/function/timeout' {
  declare module.exports: any;
}

declare module 'mout/src/function/times' {
  declare module.exports: any;
}

declare module 'mout/src/function/wrap' {
  declare module.exports: any;
}

declare module 'mout/src/index' {
  declare module.exports: any;
}

declare module 'mout/src/lang' {
  declare module.exports: any;
}

declare module 'mout/src/lang/GLOBAL' {
  declare module.exports: any;
}

declare module 'mout/src/lang/clone' {
  declare module.exports: any;
}

declare module 'mout/src/lang/createObject' {
  declare module.exports: any;
}

declare module 'mout/src/lang/ctorApply' {
  declare module.exports: any;
}

declare module 'mout/src/lang/deepClone' {
  declare module.exports: any;
}

declare module 'mout/src/lang/deepEquals' {
  declare module.exports: any;
}

declare module 'mout/src/lang/defaults' {
  declare module.exports: any;
}

declare module 'mout/src/lang/inheritPrototype' {
  declare module.exports: any;
}

declare module 'mout/src/lang/is' {
  declare module.exports: any;
}

declare module 'mout/src/lang/isArguments' {
  declare module.exports: any;
}

declare module 'mout/src/lang/isArray' {
  declare module.exports: any;
}

declare module 'mout/src/lang/isBoolean' {
  declare module.exports: any;
}

declare module 'mout/src/lang/isDate' {
  declare module.exports: any;
}

declare module 'mout/src/lang/isEmpty' {
  declare module.exports: any;
}

declare module 'mout/src/lang/isFinite' {
  declare module.exports: any;
}

declare module 'mout/src/lang/isFunction' {
  declare module.exports: any;
}

declare module 'mout/src/lang/isInteger' {
  declare module.exports: any;
}

declare module 'mout/src/lang/isKind' {
  declare module.exports: any;
}

declare module 'mout/src/lang/isNaN' {
  declare module.exports: any;
}

declare module 'mout/src/lang/isNull' {
  declare module.exports: any;
}

declare module 'mout/src/lang/isNumber' {
  declare module.exports: any;
}

declare module 'mout/src/lang/isObject' {
  declare module.exports: any;
}

declare module 'mout/src/lang/isPlainObject' {
  declare module.exports: any;
}

declare module 'mout/src/lang/isPrimitive' {
  declare module.exports: any;
}

declare module 'mout/src/lang/isRegExp' {
  declare module.exports: any;
}

declare module 'mout/src/lang/isString' {
  declare module.exports: any;
}

declare module 'mout/src/lang/isUndefined' {
  declare module.exports: any;
}

declare module 'mout/src/lang/isnt' {
  declare module.exports: any;
}

declare module 'mout/src/lang/kindOf' {
  declare module.exports: any;
}

declare module 'mout/src/lang/toArray' {
  declare module.exports: any;
}

declare module 'mout/src/lang/toNumber' {
  declare module.exports: any;
}

declare module 'mout/src/lang/toString' {
  declare module.exports: any;
}

declare module 'mout/src/math' {
  declare module.exports: any;
}

declare module 'mout/src/math/ceil' {
  declare module.exports: any;
}

declare module 'mout/src/math/clamp' {
  declare module.exports: any;
}

declare module 'mout/src/math/countSteps' {
  declare module.exports: any;
}

declare module 'mout/src/math/floor' {
  declare module.exports: any;
}

declare module 'mout/src/math/inRange' {
  declare module.exports: any;
}

declare module 'mout/src/math/isNear' {
  declare module.exports: any;
}

declare module 'mout/src/math/lerp' {
  declare module.exports: any;
}

declare module 'mout/src/math/loop' {
  declare module.exports: any;
}

declare module 'mout/src/math/map' {
  declare module.exports: any;
}

declare module 'mout/src/math/norm' {
  declare module.exports: any;
}

declare module 'mout/src/math/overflow' {
  declare module.exports: any;
}

declare module 'mout/src/math/round' {
  declare module.exports: any;
}

declare module 'mout/src/number' {
  declare module.exports: any;
}

declare module 'mout/src/number/MAX_INT' {
  declare module.exports: any;
}

declare module 'mout/src/number/MAX_SAFE_INTEGER' {
  declare module.exports: any;
}

declare module 'mout/src/number/MAX_UINT' {
  declare module.exports: any;
}

declare module 'mout/src/number/MIN_INT' {
  declare module.exports: any;
}

declare module 'mout/src/number/abbreviate' {
  declare module.exports: any;
}

declare module 'mout/src/number/currencyFormat' {
  declare module.exports: any;
}

declare module 'mout/src/number/enforcePrecision' {
  declare module.exports: any;
}

declare module 'mout/src/number/isNaN' {
  declare module.exports: any;
}

declare module 'mout/src/number/nth' {
  declare module.exports: any;
}

declare module 'mout/src/number/ordinal' {
  declare module.exports: any;
}

declare module 'mout/src/number/pad' {
  declare module.exports: any;
}

declare module 'mout/src/number/rol' {
  declare module.exports: any;
}

declare module 'mout/src/number/ror' {
  declare module.exports: any;
}

declare module 'mout/src/number/sign' {
  declare module.exports: any;
}

declare module 'mout/src/number/toInt' {
  declare module.exports: any;
}

declare module 'mout/src/number/toUInt' {
  declare module.exports: any;
}

declare module 'mout/src/number/toUInt31' {
  declare module.exports: any;
}

declare module 'mout/src/object' {
  declare module.exports: any;
}

declare module 'mout/src/object/bindAll' {
  declare module.exports: any;
}

declare module 'mout/src/object/contains' {
  declare module.exports: any;
}

declare module 'mout/src/object/deepFillIn' {
  declare module.exports: any;
}

declare module 'mout/src/object/deepMatches' {
  declare module.exports: any;
}

declare module 'mout/src/object/deepMixIn' {
  declare module.exports: any;
}

declare module 'mout/src/object/equals' {
  declare module.exports: any;
}

declare module 'mout/src/object/every' {
  declare module.exports: any;
}

declare module 'mout/src/object/fillIn' {
  declare module.exports: any;
}

declare module 'mout/src/object/filter' {
  declare module.exports: any;
}

declare module 'mout/src/object/find' {
  declare module.exports: any;
}

declare module 'mout/src/object/flatten' {
  declare module.exports: any;
}

declare module 'mout/src/object/forIn' {
  declare module.exports: any;
}

declare module 'mout/src/object/forOwn' {
  declare module.exports: any;
}

declare module 'mout/src/object/functions' {
  declare module.exports: any;
}

declare module 'mout/src/object/get' {
  declare module.exports: any;
}

declare module 'mout/src/object/has' {
  declare module.exports: any;
}

declare module 'mout/src/object/hasOwn' {
  declare module.exports: any;
}

declare module 'mout/src/object/keys' {
  declare module.exports: any;
}

declare module 'mout/src/object/map' {
  declare module.exports: any;
}

declare module 'mout/src/object/matches' {
  declare module.exports: any;
}

declare module 'mout/src/object/max' {
  declare module.exports: any;
}

declare module 'mout/src/object/merge' {
  declare module.exports: any;
}

declare module 'mout/src/object/min' {
  declare module.exports: any;
}

declare module 'mout/src/object/mixIn' {
  declare module.exports: any;
}

declare module 'mout/src/object/namespace' {
  declare module.exports: any;
}

declare module 'mout/src/object/omit' {
  declare module.exports: any;
}

declare module 'mout/src/object/pick' {
  declare module.exports: any;
}

declare module 'mout/src/object/pluck' {
  declare module.exports: any;
}

declare module 'mout/src/object/reduce' {
  declare module.exports: any;
}

declare module 'mout/src/object/reject' {
  declare module.exports: any;
}

declare module 'mout/src/object/result' {
  declare module.exports: any;
}

declare module 'mout/src/object/set' {
  declare module.exports: any;
}

declare module 'mout/src/object/size' {
  declare module.exports: any;
}

declare module 'mout/src/object/some' {
  declare module.exports: any;
}

declare module 'mout/src/object/unset' {
  declare module.exports: any;
}

declare module 'mout/src/object/values' {
  declare module.exports: any;
}

declare module 'mout/src/queryString' {
  declare module.exports: any;
}

declare module 'mout/src/queryString/contains' {
  declare module.exports: any;
}

declare module 'mout/src/queryString/decode' {
  declare module.exports: any;
}

declare module 'mout/src/queryString/encode' {
  declare module.exports: any;
}

declare module 'mout/src/queryString/getParam' {
  declare module.exports: any;
}

declare module 'mout/src/queryString/getQuery' {
  declare module.exports: any;
}

declare module 'mout/src/queryString/parse' {
  declare module.exports: any;
}

declare module 'mout/src/queryString/setParam' {
  declare module.exports: any;
}

declare module 'mout/src/random' {
  declare module.exports: any;
}

declare module 'mout/src/random/choice' {
  declare module.exports: any;
}

declare module 'mout/src/random/guid' {
  declare module.exports: any;
}

declare module 'mout/src/random/rand' {
  declare module.exports: any;
}

declare module 'mout/src/random/randBit' {
  declare module.exports: any;
}

declare module 'mout/src/random/randBool' {
  declare module.exports: any;
}

declare module 'mout/src/random/randHex' {
  declare module.exports: any;
}

declare module 'mout/src/random/randInt' {
  declare module.exports: any;
}

declare module 'mout/src/random/randSign' {
  declare module.exports: any;
}

declare module 'mout/src/random/randString' {
  declare module.exports: any;
}

declare module 'mout/src/random/random' {
  declare module.exports: any;
}

declare module 'mout/src/string' {
  declare module.exports: any;
}

declare module 'mout/src/string/WHITE_SPACES' {
  declare module.exports: any;
}

declare module 'mout/src/string/camelCase' {
  declare module.exports: any;
}

declare module 'mout/src/string/contains' {
  declare module.exports: any;
}

declare module 'mout/src/string/crop' {
  declare module.exports: any;
}

declare module 'mout/src/string/endsWith' {
  declare module.exports: any;
}

declare module 'mout/src/string/escapeHtml' {
  declare module.exports: any;
}

declare module 'mout/src/string/escapeRegExp' {
  declare module.exports: any;
}

declare module 'mout/src/string/escapeUnicode' {
  declare module.exports: any;
}

declare module 'mout/src/string/hyphenate' {
  declare module.exports: any;
}

declare module 'mout/src/string/insert' {
  declare module.exports: any;
}

declare module 'mout/src/string/interpolate' {
  declare module.exports: any;
}

declare module 'mout/src/string/lowerCase' {
  declare module.exports: any;
}

declare module 'mout/src/string/lpad' {
  declare module.exports: any;
}

declare module 'mout/src/string/ltrim' {
  declare module.exports: any;
}

declare module 'mout/src/string/makePath' {
  declare module.exports: any;
}

declare module 'mout/src/string/normalizeLineBreaks' {
  declare module.exports: any;
}

declare module 'mout/src/string/pascalCase' {
  declare module.exports: any;
}

declare module 'mout/src/string/properCase' {
  declare module.exports: any;
}

declare module 'mout/src/string/removeNonASCII' {
  declare module.exports: any;
}

declare module 'mout/src/string/removeNonWord' {
  declare module.exports: any;
}

declare module 'mout/src/string/repeat' {
  declare module.exports: any;
}

declare module 'mout/src/string/replace' {
  declare module.exports: any;
}

declare module 'mout/src/string/replaceAccents' {
  declare module.exports: any;
}

declare module 'mout/src/string/rpad' {
  declare module.exports: any;
}

declare module 'mout/src/string/rtrim' {
  declare module.exports: any;
}

declare module 'mout/src/string/sentenceCase' {
  declare module.exports: any;
}

declare module 'mout/src/string/slugify' {
  declare module.exports: any;
}

declare module 'mout/src/string/startsWith' {
  declare module.exports: any;
}

declare module 'mout/src/string/stripHtmlTags' {
  declare module.exports: any;
}

declare module 'mout/src/string/trim' {
  declare module.exports: any;
}

declare module 'mout/src/string/truncate' {
  declare module.exports: any;
}

declare module 'mout/src/string/typecast' {
  declare module.exports: any;
}

declare module 'mout/src/string/unCamelCase' {
  declare module.exports: any;
}

declare module 'mout/src/string/underscore' {
  declare module.exports: any;
}

declare module 'mout/src/string/unescapeHtml' {
  declare module.exports: any;
}

declare module 'mout/src/string/unescapeUnicode' {
  declare module.exports: any;
}

declare module 'mout/src/string/unhyphenate' {
  declare module.exports: any;
}

declare module 'mout/src/string/upperCase' {
  declare module.exports: any;
}

declare module 'mout/src/time' {
  declare module.exports: any;
}

declare module 'mout/src/time/convert' {
  declare module.exports: any;
}

declare module 'mout/src/time/now' {
  declare module.exports: any;
}

declare module 'mout/src/time/parseMs' {
  declare module.exports: any;
}

declare module 'mout/src/time/toTimeString' {
  declare module.exports: any;
}

declare module 'mout/string' {
  declare module.exports: any;
}

declare module 'mout/string/WHITE_SPACES' {
  declare module.exports: any;
}

declare module 'mout/string/camelCase' {
  declare module.exports: any;
}

declare module 'mout/string/contains' {
  declare module.exports: any;
}

declare module 'mout/string/crop' {
  declare module.exports: any;
}

declare module 'mout/string/endsWith' {
  declare module.exports: any;
}

declare module 'mout/string/escapeHtml' {
  declare module.exports: any;
}

declare module 'mout/string/escapeRegExp' {
  declare module.exports: any;
}

declare module 'mout/string/escapeUnicode' {
  declare module.exports: any;
}

declare module 'mout/string/hyphenate' {
  declare module.exports: any;
}

declare module 'mout/string/insert' {
  declare module.exports: any;
}

declare module 'mout/string/interpolate' {
  declare module.exports: any;
}

declare module 'mout/string/lowerCase' {
  declare module.exports: any;
}

declare module 'mout/string/lpad' {
  declare module.exports: any;
}

declare module 'mout/string/ltrim' {
  declare module.exports: any;
}

declare module 'mout/string/makePath' {
  declare module.exports: any;
}

declare module 'mout/string/normalizeLineBreaks' {
  declare module.exports: any;
}

declare module 'mout/string/pascalCase' {
  declare module.exports: any;
}

declare module 'mout/string/properCase' {
  declare module.exports: any;
}

declare module 'mout/string/removeNonASCII' {
  declare module.exports: any;
}

declare module 'mout/string/removeNonWord' {
  declare module.exports: any;
}

declare module 'mout/string/repeat' {
  declare module.exports: any;
}

declare module 'mout/string/replace' {
  declare module.exports: any;
}

declare module 'mout/string/replaceAccents' {
  declare module.exports: any;
}

declare module 'mout/string/rpad' {
  declare module.exports: any;
}

declare module 'mout/string/rtrim' {
  declare module.exports: any;
}

declare module 'mout/string/sentenceCase' {
  declare module.exports: any;
}

declare module 'mout/string/slugify' {
  declare module.exports: any;
}

declare module 'mout/string/startsWith' {
  declare module.exports: any;
}

declare module 'mout/string/stripHtmlTags' {
  declare module.exports: any;
}

declare module 'mout/string/trim' {
  declare module.exports: any;
}

declare module 'mout/string/truncate' {
  declare module.exports: any;
}

declare module 'mout/string/typecast' {
  declare module.exports: any;
}

declare module 'mout/string/unCamelCase' {
  declare module.exports: any;
}

declare module 'mout/string/underscore' {
  declare module.exports: any;
}

declare module 'mout/string/unescapeHtml' {
  declare module.exports: any;
}

declare module 'mout/string/unescapeUnicode' {
  declare module.exports: any;
}

declare module 'mout/string/unhyphenate' {
  declare module.exports: any;
}

declare module 'mout/string/upperCase' {
  declare module.exports: any;
}

declare module 'mout/time' {
  declare module.exports: any;
}

declare module 'mout/time/convert' {
  declare module.exports: any;
}

declare module 'mout/time/now' {
  declare module.exports: any;
}

declare module 'mout/time/parseMs' {
  declare module.exports: any;
}

declare module 'mout/time/toTimeString' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mout/array.js' {
  declare module.exports: $Exports<'mout/array'>;
}
declare module 'mout/array/append.js' {
  declare module.exports: $Exports<'mout/array/append'>;
}
declare module 'mout/array/collect.js' {
  declare module.exports: $Exports<'mout/array/collect'>;
}
declare module 'mout/array/combine.js' {
  declare module.exports: $Exports<'mout/array/combine'>;
}
declare module 'mout/array/compact.js' {
  declare module.exports: $Exports<'mout/array/compact'>;
}
declare module 'mout/array/contains.js' {
  declare module.exports: $Exports<'mout/array/contains'>;
}
declare module 'mout/array/difference.js' {
  declare module.exports: $Exports<'mout/array/difference'>;
}
declare module 'mout/array/equals.js' {
  declare module.exports: $Exports<'mout/array/equals'>;
}
declare module 'mout/array/every.js' {
  declare module.exports: $Exports<'mout/array/every'>;
}
declare module 'mout/array/filter.js' {
  declare module.exports: $Exports<'mout/array/filter'>;
}
declare module 'mout/array/find.js' {
  declare module.exports: $Exports<'mout/array/find'>;
}
declare module 'mout/array/findIndex.js' {
  declare module.exports: $Exports<'mout/array/findIndex'>;
}
declare module 'mout/array/findLast.js' {
  declare module.exports: $Exports<'mout/array/findLast'>;
}
declare module 'mout/array/findLastIndex.js' {
  declare module.exports: $Exports<'mout/array/findLastIndex'>;
}
declare module 'mout/array/flatten.js' {
  declare module.exports: $Exports<'mout/array/flatten'>;
}
declare module 'mout/array/forEach.js' {
  declare module.exports: $Exports<'mout/array/forEach'>;
}
declare module 'mout/array/groupBy.js' {
  declare module.exports: $Exports<'mout/array/groupBy'>;
}
declare module 'mout/array/indexOf.js' {
  declare module.exports: $Exports<'mout/array/indexOf'>;
}
declare module 'mout/array/indicesOf.js' {
  declare module.exports: $Exports<'mout/array/indicesOf'>;
}
declare module 'mout/array/insert.js' {
  declare module.exports: $Exports<'mout/array/insert'>;
}
declare module 'mout/array/intersection.js' {
  declare module.exports: $Exports<'mout/array/intersection'>;
}
declare module 'mout/array/invoke.js' {
  declare module.exports: $Exports<'mout/array/invoke'>;
}
declare module 'mout/array/join.js' {
  declare module.exports: $Exports<'mout/array/join'>;
}
declare module 'mout/array/last.js' {
  declare module.exports: $Exports<'mout/array/last'>;
}
declare module 'mout/array/lastIndexOf.js' {
  declare module.exports: $Exports<'mout/array/lastIndexOf'>;
}
declare module 'mout/array/map.js' {
  declare module.exports: $Exports<'mout/array/map'>;
}
declare module 'mout/array/max.js' {
  declare module.exports: $Exports<'mout/array/max'>;
}
declare module 'mout/array/min.js' {
  declare module.exports: $Exports<'mout/array/min'>;
}
declare module 'mout/array/pick.js' {
  declare module.exports: $Exports<'mout/array/pick'>;
}
declare module 'mout/array/pluck.js' {
  declare module.exports: $Exports<'mout/array/pluck'>;
}
declare module 'mout/array/range.js' {
  declare module.exports: $Exports<'mout/array/range'>;
}
declare module 'mout/array/reduce.js' {
  declare module.exports: $Exports<'mout/array/reduce'>;
}
declare module 'mout/array/reduceRight.js' {
  declare module.exports: $Exports<'mout/array/reduceRight'>;
}
declare module 'mout/array/reject.js' {
  declare module.exports: $Exports<'mout/array/reject'>;
}
declare module 'mout/array/remove.js' {
  declare module.exports: $Exports<'mout/array/remove'>;
}
declare module 'mout/array/removeAll.js' {
  declare module.exports: $Exports<'mout/array/removeAll'>;
}
declare module 'mout/array/reverse.js' {
  declare module.exports: $Exports<'mout/array/reverse'>;
}
declare module 'mout/array/shuffle.js' {
  declare module.exports: $Exports<'mout/array/shuffle'>;
}
declare module 'mout/array/slice.js' {
  declare module.exports: $Exports<'mout/array/slice'>;
}
declare module 'mout/array/some.js' {
  declare module.exports: $Exports<'mout/array/some'>;
}
declare module 'mout/array/sort.js' {
  declare module.exports: $Exports<'mout/array/sort'>;
}
declare module 'mout/array/sortBy.js' {
  declare module.exports: $Exports<'mout/array/sortBy'>;
}
declare module 'mout/array/split.js' {
  declare module.exports: $Exports<'mout/array/split'>;
}
declare module 'mout/array/take.js' {
  declare module.exports: $Exports<'mout/array/take'>;
}
declare module 'mout/array/toLookup.js' {
  declare module.exports: $Exports<'mout/array/toLookup'>;
}
declare module 'mout/array/union.js' {
  declare module.exports: $Exports<'mout/array/union'>;
}
declare module 'mout/array/unique.js' {
  declare module.exports: $Exports<'mout/array/unique'>;
}
declare module 'mout/array/xor.js' {
  declare module.exports: $Exports<'mout/array/xor'>;
}
declare module 'mout/array/zip.js' {
  declare module.exports: $Exports<'mout/array/zip'>;
}
declare module 'mout/collection.js' {
  declare module.exports: $Exports<'mout/collection'>;
}
declare module 'mout/collection/contains.js' {
  declare module.exports: $Exports<'mout/collection/contains'>;
}
declare module 'mout/collection/every.js' {
  declare module.exports: $Exports<'mout/collection/every'>;
}
declare module 'mout/collection/filter.js' {
  declare module.exports: $Exports<'mout/collection/filter'>;
}
declare module 'mout/collection/find.js' {
  declare module.exports: $Exports<'mout/collection/find'>;
}
declare module 'mout/collection/forEach.js' {
  declare module.exports: $Exports<'mout/collection/forEach'>;
}
declare module 'mout/collection/make_.js' {
  declare module.exports: $Exports<'mout/collection/make_'>;
}
declare module 'mout/collection/map.js' {
  declare module.exports: $Exports<'mout/collection/map'>;
}
declare module 'mout/collection/max.js' {
  declare module.exports: $Exports<'mout/collection/max'>;
}
declare module 'mout/collection/min.js' {
  declare module.exports: $Exports<'mout/collection/min'>;
}
declare module 'mout/collection/pluck.js' {
  declare module.exports: $Exports<'mout/collection/pluck'>;
}
declare module 'mout/collection/reduce.js' {
  declare module.exports: $Exports<'mout/collection/reduce'>;
}
declare module 'mout/collection/reject.js' {
  declare module.exports: $Exports<'mout/collection/reject'>;
}
declare module 'mout/collection/size.js' {
  declare module.exports: $Exports<'mout/collection/size'>;
}
declare module 'mout/collection/some.js' {
  declare module.exports: $Exports<'mout/collection/some'>;
}
declare module 'mout/date.js' {
  declare module.exports: $Exports<'mout/date'>;
}
declare module 'mout/date/dayOfTheYear.js' {
  declare module.exports: $Exports<'mout/date/dayOfTheYear'>;
}
declare module 'mout/date/diff.js' {
  declare module.exports: $Exports<'mout/date/diff'>;
}
declare module 'mout/date/i18n/de-DE.js' {
  declare module.exports: $Exports<'mout/date/i18n/de-DE'>;
}
declare module 'mout/date/i18n/en-US.js' {
  declare module.exports: $Exports<'mout/date/i18n/en-US'>;
}
declare module 'mout/date/i18n/pt-BR.js' {
  declare module.exports: $Exports<'mout/date/i18n/pt-BR'>;
}
declare module 'mout/date/i18n_.js' {
  declare module.exports: $Exports<'mout/date/i18n_'>;
}
declare module 'mout/date/isLeapYear.js' {
  declare module.exports: $Exports<'mout/date/isLeapYear'>;
}
declare module 'mout/date/isSame.js' {
  declare module.exports: $Exports<'mout/date/isSame'>;
}
declare module 'mout/date/parseIso.js' {
  declare module.exports: $Exports<'mout/date/parseIso'>;
}
declare module 'mout/date/quarter.js' {
  declare module.exports: $Exports<'mout/date/quarter'>;
}
declare module 'mout/date/startOf.js' {
  declare module.exports: $Exports<'mout/date/startOf'>;
}
declare module 'mout/date/strftime.js' {
  declare module.exports: $Exports<'mout/date/strftime'>;
}
declare module 'mout/date/timezoneAbbr.js' {
  declare module.exports: $Exports<'mout/date/timezoneAbbr'>;
}
declare module 'mout/date/timezoneOffset.js' {
  declare module.exports: $Exports<'mout/date/timezoneOffset'>;
}
declare module 'mout/date/totalDaysInMonth.js' {
  declare module.exports: $Exports<'mout/date/totalDaysInMonth'>;
}
declare module 'mout/date/totalDaysInYear.js' {
  declare module.exports: $Exports<'mout/date/totalDaysInYear'>;
}
declare module 'mout/date/weekOfTheYear.js' {
  declare module.exports: $Exports<'mout/date/weekOfTheYear'>;
}
declare module 'mout/function.js' {
  declare module.exports: $Exports<'mout/function'>;
}
declare module 'mout/function/after.js' {
  declare module.exports: $Exports<'mout/function/after'>;
}
declare module 'mout/function/awaitDelay.js' {
  declare module.exports: $Exports<'mout/function/awaitDelay'>;
}
declare module 'mout/function/bind.js' {
  declare module.exports: $Exports<'mout/function/bind'>;
}
declare module 'mout/function/compose.js' {
  declare module.exports: $Exports<'mout/function/compose'>;
}
declare module 'mout/function/constant.js' {
  declare module.exports: $Exports<'mout/function/constant'>;
}
declare module 'mout/function/debounce.js' {
  declare module.exports: $Exports<'mout/function/debounce'>;
}
declare module 'mout/function/func.js' {
  declare module.exports: $Exports<'mout/function/func'>;
}
declare module 'mout/function/identity.js' {
  declare module.exports: $Exports<'mout/function/identity'>;
}
declare module 'mout/function/makeIterator_.js' {
  declare module.exports: $Exports<'mout/function/makeIterator_'>;
}
declare module 'mout/function/memoize.js' {
  declare module.exports: $Exports<'mout/function/memoize'>;
}
declare module 'mout/function/partial.js' {
  declare module.exports: $Exports<'mout/function/partial'>;
}
declare module 'mout/function/prop.js' {
  declare module.exports: $Exports<'mout/function/prop'>;
}
declare module 'mout/function/series.js' {
  declare module.exports: $Exports<'mout/function/series'>;
}
declare module 'mout/function/throttle.js' {
  declare module.exports: $Exports<'mout/function/throttle'>;
}
declare module 'mout/function/timeout.js' {
  declare module.exports: $Exports<'mout/function/timeout'>;
}
declare module 'mout/function/times.js' {
  declare module.exports: $Exports<'mout/function/times'>;
}
declare module 'mout/function/wrap.js' {
  declare module.exports: $Exports<'mout/function/wrap'>;
}
declare module 'mout/index' {
  declare module.exports: $Exports<'mout'>;
}
declare module 'mout/index.js' {
  declare module.exports: $Exports<'mout'>;
}
declare module 'mout/lang.js' {
  declare module.exports: $Exports<'mout/lang'>;
}
declare module 'mout/lang/GLOBAL.js' {
  declare module.exports: $Exports<'mout/lang/GLOBAL'>;
}
declare module 'mout/lang/clone.js' {
  declare module.exports: $Exports<'mout/lang/clone'>;
}
declare module 'mout/lang/createObject.js' {
  declare module.exports: $Exports<'mout/lang/createObject'>;
}
declare module 'mout/lang/ctorApply.js' {
  declare module.exports: $Exports<'mout/lang/ctorApply'>;
}
declare module 'mout/lang/deepClone.js' {
  declare module.exports: $Exports<'mout/lang/deepClone'>;
}
declare module 'mout/lang/deepEquals.js' {
  declare module.exports: $Exports<'mout/lang/deepEquals'>;
}
declare module 'mout/lang/defaults.js' {
  declare module.exports: $Exports<'mout/lang/defaults'>;
}
declare module 'mout/lang/inheritPrototype.js' {
  declare module.exports: $Exports<'mout/lang/inheritPrototype'>;
}
declare module 'mout/lang/is.js' {
  declare module.exports: $Exports<'mout/lang/is'>;
}
declare module 'mout/lang/isArguments.js' {
  declare module.exports: $Exports<'mout/lang/isArguments'>;
}
declare module 'mout/lang/isArray.js' {
  declare module.exports: $Exports<'mout/lang/isArray'>;
}
declare module 'mout/lang/isBoolean.js' {
  declare module.exports: $Exports<'mout/lang/isBoolean'>;
}
declare module 'mout/lang/isDate.js' {
  declare module.exports: $Exports<'mout/lang/isDate'>;
}
declare module 'mout/lang/isEmpty.js' {
  declare module.exports: $Exports<'mout/lang/isEmpty'>;
}
declare module 'mout/lang/isFinite.js' {
  declare module.exports: $Exports<'mout/lang/isFinite'>;
}
declare module 'mout/lang/isFunction.js' {
  declare module.exports: $Exports<'mout/lang/isFunction'>;
}
declare module 'mout/lang/isInteger.js' {
  declare module.exports: $Exports<'mout/lang/isInteger'>;
}
declare module 'mout/lang/isKind.js' {
  declare module.exports: $Exports<'mout/lang/isKind'>;
}
declare module 'mout/lang/isNaN.js' {
  declare module.exports: $Exports<'mout/lang/isNaN'>;
}
declare module 'mout/lang/isNull.js' {
  declare module.exports: $Exports<'mout/lang/isNull'>;
}
declare module 'mout/lang/isNumber.js' {
  declare module.exports: $Exports<'mout/lang/isNumber'>;
}
declare module 'mout/lang/isObject.js' {
  declare module.exports: $Exports<'mout/lang/isObject'>;
}
declare module 'mout/lang/isPlainObject.js' {
  declare module.exports: $Exports<'mout/lang/isPlainObject'>;
}
declare module 'mout/lang/isPrimitive.js' {
  declare module.exports: $Exports<'mout/lang/isPrimitive'>;
}
declare module 'mout/lang/isRegExp.js' {
  declare module.exports: $Exports<'mout/lang/isRegExp'>;
}
declare module 'mout/lang/isString.js' {
  declare module.exports: $Exports<'mout/lang/isString'>;
}
declare module 'mout/lang/isUndefined.js' {
  declare module.exports: $Exports<'mout/lang/isUndefined'>;
}
declare module 'mout/lang/isnt.js' {
  declare module.exports: $Exports<'mout/lang/isnt'>;
}
declare module 'mout/lang/kindOf.js' {
  declare module.exports: $Exports<'mout/lang/kindOf'>;
}
declare module 'mout/lang/toArray.js' {
  declare module.exports: $Exports<'mout/lang/toArray'>;
}
declare module 'mout/lang/toNumber.js' {
  declare module.exports: $Exports<'mout/lang/toNumber'>;
}
declare module 'mout/lang/toString.js' {
  declare module.exports: $Exports<'mout/lang/toString'>;
}
declare module 'mout/math.js' {
  declare module.exports: $Exports<'mout/math'>;
}
declare module 'mout/math/ceil.js' {
  declare module.exports: $Exports<'mout/math/ceil'>;
}
declare module 'mout/math/clamp.js' {
  declare module.exports: $Exports<'mout/math/clamp'>;
}
declare module 'mout/math/countSteps.js' {
  declare module.exports: $Exports<'mout/math/countSteps'>;
}
declare module 'mout/math/floor.js' {
  declare module.exports: $Exports<'mout/math/floor'>;
}
declare module 'mout/math/inRange.js' {
  declare module.exports: $Exports<'mout/math/inRange'>;
}
declare module 'mout/math/isNear.js' {
  declare module.exports: $Exports<'mout/math/isNear'>;
}
declare module 'mout/math/lerp.js' {
  declare module.exports: $Exports<'mout/math/lerp'>;
}
declare module 'mout/math/loop.js' {
  declare module.exports: $Exports<'mout/math/loop'>;
}
declare module 'mout/math/map.js' {
  declare module.exports: $Exports<'mout/math/map'>;
}
declare module 'mout/math/norm.js' {
  declare module.exports: $Exports<'mout/math/norm'>;
}
declare module 'mout/math/overflow.js' {
  declare module.exports: $Exports<'mout/math/overflow'>;
}
declare module 'mout/math/round.js' {
  declare module.exports: $Exports<'mout/math/round'>;
}
declare module 'mout/number.js' {
  declare module.exports: $Exports<'mout/number'>;
}
declare module 'mout/number/MAX_INT.js' {
  declare module.exports: $Exports<'mout/number/MAX_INT'>;
}
declare module 'mout/number/MAX_SAFE_INTEGER.js' {
  declare module.exports: $Exports<'mout/number/MAX_SAFE_INTEGER'>;
}
declare module 'mout/number/MAX_UINT.js' {
  declare module.exports: $Exports<'mout/number/MAX_UINT'>;
}
declare module 'mout/number/MIN_INT.js' {
  declare module.exports: $Exports<'mout/number/MIN_INT'>;
}
declare module 'mout/number/abbreviate.js' {
  declare module.exports: $Exports<'mout/number/abbreviate'>;
}
declare module 'mout/number/currencyFormat.js' {
  declare module.exports: $Exports<'mout/number/currencyFormat'>;
}
declare module 'mout/number/enforcePrecision.js' {
  declare module.exports: $Exports<'mout/number/enforcePrecision'>;
}
declare module 'mout/number/isNaN.js' {
  declare module.exports: $Exports<'mout/number/isNaN'>;
}
declare module 'mout/number/nth.js' {
  declare module.exports: $Exports<'mout/number/nth'>;
}
declare module 'mout/number/ordinal.js' {
  declare module.exports: $Exports<'mout/number/ordinal'>;
}
declare module 'mout/number/pad.js' {
  declare module.exports: $Exports<'mout/number/pad'>;
}
declare module 'mout/number/rol.js' {
  declare module.exports: $Exports<'mout/number/rol'>;
}
declare module 'mout/number/ror.js' {
  declare module.exports: $Exports<'mout/number/ror'>;
}
declare module 'mout/number/sign.js' {
  declare module.exports: $Exports<'mout/number/sign'>;
}
declare module 'mout/number/toInt.js' {
  declare module.exports: $Exports<'mout/number/toInt'>;
}
declare module 'mout/number/toUInt.js' {
  declare module.exports: $Exports<'mout/number/toUInt'>;
}
declare module 'mout/number/toUInt31.js' {
  declare module.exports: $Exports<'mout/number/toUInt31'>;
}
declare module 'mout/object.js' {
  declare module.exports: $Exports<'mout/object'>;
}
declare module 'mout/object/bindAll.js' {
  declare module.exports: $Exports<'mout/object/bindAll'>;
}
declare module 'mout/object/contains.js' {
  declare module.exports: $Exports<'mout/object/contains'>;
}
declare module 'mout/object/deepFillIn.js' {
  declare module.exports: $Exports<'mout/object/deepFillIn'>;
}
declare module 'mout/object/deepMatches.js' {
  declare module.exports: $Exports<'mout/object/deepMatches'>;
}
declare module 'mout/object/deepMixIn.js' {
  declare module.exports: $Exports<'mout/object/deepMixIn'>;
}
declare module 'mout/object/equals.js' {
  declare module.exports: $Exports<'mout/object/equals'>;
}
declare module 'mout/object/every.js' {
  declare module.exports: $Exports<'mout/object/every'>;
}
declare module 'mout/object/fillIn.js' {
  declare module.exports: $Exports<'mout/object/fillIn'>;
}
declare module 'mout/object/filter.js' {
  declare module.exports: $Exports<'mout/object/filter'>;
}
declare module 'mout/object/find.js' {
  declare module.exports: $Exports<'mout/object/find'>;
}
declare module 'mout/object/flatten.js' {
  declare module.exports: $Exports<'mout/object/flatten'>;
}
declare module 'mout/object/forIn.js' {
  declare module.exports: $Exports<'mout/object/forIn'>;
}
declare module 'mout/object/forOwn.js' {
  declare module.exports: $Exports<'mout/object/forOwn'>;
}
declare module 'mout/object/functions.js' {
  declare module.exports: $Exports<'mout/object/functions'>;
}
declare module 'mout/object/get.js' {
  declare module.exports: $Exports<'mout/object/get'>;
}
declare module 'mout/object/has.js' {
  declare module.exports: $Exports<'mout/object/has'>;
}
declare module 'mout/object/hasOwn.js' {
  declare module.exports: $Exports<'mout/object/hasOwn'>;
}
declare module 'mout/object/keys.js' {
  declare module.exports: $Exports<'mout/object/keys'>;
}
declare module 'mout/object/map.js' {
  declare module.exports: $Exports<'mout/object/map'>;
}
declare module 'mout/object/matches.js' {
  declare module.exports: $Exports<'mout/object/matches'>;
}
declare module 'mout/object/max.js' {
  declare module.exports: $Exports<'mout/object/max'>;
}
declare module 'mout/object/merge.js' {
  declare module.exports: $Exports<'mout/object/merge'>;
}
declare module 'mout/object/min.js' {
  declare module.exports: $Exports<'mout/object/min'>;
}
declare module 'mout/object/mixIn.js' {
  declare module.exports: $Exports<'mout/object/mixIn'>;
}
declare module 'mout/object/namespace.js' {
  declare module.exports: $Exports<'mout/object/namespace'>;
}
declare module 'mout/object/omit.js' {
  declare module.exports: $Exports<'mout/object/omit'>;
}
declare module 'mout/object/pick.js' {
  declare module.exports: $Exports<'mout/object/pick'>;
}
declare module 'mout/object/pluck.js' {
  declare module.exports: $Exports<'mout/object/pluck'>;
}
declare module 'mout/object/reduce.js' {
  declare module.exports: $Exports<'mout/object/reduce'>;
}
declare module 'mout/object/reject.js' {
  declare module.exports: $Exports<'mout/object/reject'>;
}
declare module 'mout/object/result.js' {
  declare module.exports: $Exports<'mout/object/result'>;
}
declare module 'mout/object/set.js' {
  declare module.exports: $Exports<'mout/object/set'>;
}
declare module 'mout/object/size.js' {
  declare module.exports: $Exports<'mout/object/size'>;
}
declare module 'mout/object/some.js' {
  declare module.exports: $Exports<'mout/object/some'>;
}
declare module 'mout/object/unset.js' {
  declare module.exports: $Exports<'mout/object/unset'>;
}
declare module 'mout/object/values.js' {
  declare module.exports: $Exports<'mout/object/values'>;
}
declare module 'mout/queryString.js' {
  declare module.exports: $Exports<'mout/queryString'>;
}
declare module 'mout/queryString/contains.js' {
  declare module.exports: $Exports<'mout/queryString/contains'>;
}
declare module 'mout/queryString/decode.js' {
  declare module.exports: $Exports<'mout/queryString/decode'>;
}
declare module 'mout/queryString/encode.js' {
  declare module.exports: $Exports<'mout/queryString/encode'>;
}
declare module 'mout/queryString/getParam.js' {
  declare module.exports: $Exports<'mout/queryString/getParam'>;
}
declare module 'mout/queryString/getQuery.js' {
  declare module.exports: $Exports<'mout/queryString/getQuery'>;
}
declare module 'mout/queryString/parse.js' {
  declare module.exports: $Exports<'mout/queryString/parse'>;
}
declare module 'mout/queryString/setParam.js' {
  declare module.exports: $Exports<'mout/queryString/setParam'>;
}
declare module 'mout/random.js' {
  declare module.exports: $Exports<'mout/random'>;
}
declare module 'mout/random/choice.js' {
  declare module.exports: $Exports<'mout/random/choice'>;
}
declare module 'mout/random/guid.js' {
  declare module.exports: $Exports<'mout/random/guid'>;
}
declare module 'mout/random/rand.js' {
  declare module.exports: $Exports<'mout/random/rand'>;
}
declare module 'mout/random/randBit.js' {
  declare module.exports: $Exports<'mout/random/randBit'>;
}
declare module 'mout/random/randBool.js' {
  declare module.exports: $Exports<'mout/random/randBool'>;
}
declare module 'mout/random/randHex.js' {
  declare module.exports: $Exports<'mout/random/randHex'>;
}
declare module 'mout/random/randInt.js' {
  declare module.exports: $Exports<'mout/random/randInt'>;
}
declare module 'mout/random/randSign.js' {
  declare module.exports: $Exports<'mout/random/randSign'>;
}
declare module 'mout/random/randString.js' {
  declare module.exports: $Exports<'mout/random/randString'>;
}
declare module 'mout/random/random.js' {
  declare module.exports: $Exports<'mout/random/random'>;
}
declare module 'mout/src/array.js' {
  declare module.exports: $Exports<'mout/src/array'>;
}
declare module 'mout/src/array/append.js' {
  declare module.exports: $Exports<'mout/src/array/append'>;
}
declare module 'mout/src/array/collect.js' {
  declare module.exports: $Exports<'mout/src/array/collect'>;
}
declare module 'mout/src/array/combine.js' {
  declare module.exports: $Exports<'mout/src/array/combine'>;
}
declare module 'mout/src/array/compact.js' {
  declare module.exports: $Exports<'mout/src/array/compact'>;
}
declare module 'mout/src/array/contains.js' {
  declare module.exports: $Exports<'mout/src/array/contains'>;
}
declare module 'mout/src/array/difference.js' {
  declare module.exports: $Exports<'mout/src/array/difference'>;
}
declare module 'mout/src/array/equals.js' {
  declare module.exports: $Exports<'mout/src/array/equals'>;
}
declare module 'mout/src/array/every.js' {
  declare module.exports: $Exports<'mout/src/array/every'>;
}
declare module 'mout/src/array/filter.js' {
  declare module.exports: $Exports<'mout/src/array/filter'>;
}
declare module 'mout/src/array/find.js' {
  declare module.exports: $Exports<'mout/src/array/find'>;
}
declare module 'mout/src/array/findIndex.js' {
  declare module.exports: $Exports<'mout/src/array/findIndex'>;
}
declare module 'mout/src/array/findLast.js' {
  declare module.exports: $Exports<'mout/src/array/findLast'>;
}
declare module 'mout/src/array/findLastIndex.js' {
  declare module.exports: $Exports<'mout/src/array/findLastIndex'>;
}
declare module 'mout/src/array/flatten.js' {
  declare module.exports: $Exports<'mout/src/array/flatten'>;
}
declare module 'mout/src/array/forEach.js' {
  declare module.exports: $Exports<'mout/src/array/forEach'>;
}
declare module 'mout/src/array/groupBy.js' {
  declare module.exports: $Exports<'mout/src/array/groupBy'>;
}
declare module 'mout/src/array/indexOf.js' {
  declare module.exports: $Exports<'mout/src/array/indexOf'>;
}
declare module 'mout/src/array/indicesOf.js' {
  declare module.exports: $Exports<'mout/src/array/indicesOf'>;
}
declare module 'mout/src/array/insert.js' {
  declare module.exports: $Exports<'mout/src/array/insert'>;
}
declare module 'mout/src/array/intersection.js' {
  declare module.exports: $Exports<'mout/src/array/intersection'>;
}
declare module 'mout/src/array/invoke.js' {
  declare module.exports: $Exports<'mout/src/array/invoke'>;
}
declare module 'mout/src/array/join.js' {
  declare module.exports: $Exports<'mout/src/array/join'>;
}
declare module 'mout/src/array/last.js' {
  declare module.exports: $Exports<'mout/src/array/last'>;
}
declare module 'mout/src/array/lastIndexOf.js' {
  declare module.exports: $Exports<'mout/src/array/lastIndexOf'>;
}
declare module 'mout/src/array/map.js' {
  declare module.exports: $Exports<'mout/src/array/map'>;
}
declare module 'mout/src/array/max.js' {
  declare module.exports: $Exports<'mout/src/array/max'>;
}
declare module 'mout/src/array/min.js' {
  declare module.exports: $Exports<'mout/src/array/min'>;
}
declare module 'mout/src/array/pick.js' {
  declare module.exports: $Exports<'mout/src/array/pick'>;
}
declare module 'mout/src/array/pluck.js' {
  declare module.exports: $Exports<'mout/src/array/pluck'>;
}
declare module 'mout/src/array/range.js' {
  declare module.exports: $Exports<'mout/src/array/range'>;
}
declare module 'mout/src/array/reduce.js' {
  declare module.exports: $Exports<'mout/src/array/reduce'>;
}
declare module 'mout/src/array/reduceRight.js' {
  declare module.exports: $Exports<'mout/src/array/reduceRight'>;
}
declare module 'mout/src/array/reject.js' {
  declare module.exports: $Exports<'mout/src/array/reject'>;
}
declare module 'mout/src/array/remove.js' {
  declare module.exports: $Exports<'mout/src/array/remove'>;
}
declare module 'mout/src/array/removeAll.js' {
  declare module.exports: $Exports<'mout/src/array/removeAll'>;
}
declare module 'mout/src/array/reverse.js' {
  declare module.exports: $Exports<'mout/src/array/reverse'>;
}
declare module 'mout/src/array/shuffle.js' {
  declare module.exports: $Exports<'mout/src/array/shuffle'>;
}
declare module 'mout/src/array/slice.js' {
  declare module.exports: $Exports<'mout/src/array/slice'>;
}
declare module 'mout/src/array/some.js' {
  declare module.exports: $Exports<'mout/src/array/some'>;
}
declare module 'mout/src/array/sort.js' {
  declare module.exports: $Exports<'mout/src/array/sort'>;
}
declare module 'mout/src/array/sortBy.js' {
  declare module.exports: $Exports<'mout/src/array/sortBy'>;
}
declare module 'mout/src/array/split.js' {
  declare module.exports: $Exports<'mout/src/array/split'>;
}
declare module 'mout/src/array/take.js' {
  declare module.exports: $Exports<'mout/src/array/take'>;
}
declare module 'mout/src/array/toLookup.js' {
  declare module.exports: $Exports<'mout/src/array/toLookup'>;
}
declare module 'mout/src/array/union.js' {
  declare module.exports: $Exports<'mout/src/array/union'>;
}
declare module 'mout/src/array/unique.js' {
  declare module.exports: $Exports<'mout/src/array/unique'>;
}
declare module 'mout/src/array/xor.js' {
  declare module.exports: $Exports<'mout/src/array/xor'>;
}
declare module 'mout/src/array/zip.js' {
  declare module.exports: $Exports<'mout/src/array/zip'>;
}
declare module 'mout/src/collection.js' {
  declare module.exports: $Exports<'mout/src/collection'>;
}
declare module 'mout/src/collection/contains.js' {
  declare module.exports: $Exports<'mout/src/collection/contains'>;
}
declare module 'mout/src/collection/every.js' {
  declare module.exports: $Exports<'mout/src/collection/every'>;
}
declare module 'mout/src/collection/filter.js' {
  declare module.exports: $Exports<'mout/src/collection/filter'>;
}
declare module 'mout/src/collection/find.js' {
  declare module.exports: $Exports<'mout/src/collection/find'>;
}
declare module 'mout/src/collection/forEach.js' {
  declare module.exports: $Exports<'mout/src/collection/forEach'>;
}
declare module 'mout/src/collection/make_.js' {
  declare module.exports: $Exports<'mout/src/collection/make_'>;
}
declare module 'mout/src/collection/map.js' {
  declare module.exports: $Exports<'mout/src/collection/map'>;
}
declare module 'mout/src/collection/max.js' {
  declare module.exports: $Exports<'mout/src/collection/max'>;
}
declare module 'mout/src/collection/min.js' {
  declare module.exports: $Exports<'mout/src/collection/min'>;
}
declare module 'mout/src/collection/pluck.js' {
  declare module.exports: $Exports<'mout/src/collection/pluck'>;
}
declare module 'mout/src/collection/reduce.js' {
  declare module.exports: $Exports<'mout/src/collection/reduce'>;
}
declare module 'mout/src/collection/reject.js' {
  declare module.exports: $Exports<'mout/src/collection/reject'>;
}
declare module 'mout/src/collection/size.js' {
  declare module.exports: $Exports<'mout/src/collection/size'>;
}
declare module 'mout/src/collection/some.js' {
  declare module.exports: $Exports<'mout/src/collection/some'>;
}
declare module 'mout/src/date.js' {
  declare module.exports: $Exports<'mout/src/date'>;
}
declare module 'mout/src/date/dayOfTheYear.js' {
  declare module.exports: $Exports<'mout/src/date/dayOfTheYear'>;
}
declare module 'mout/src/date/diff.js' {
  declare module.exports: $Exports<'mout/src/date/diff'>;
}
declare module 'mout/src/date/i18n/de-DE.js' {
  declare module.exports: $Exports<'mout/src/date/i18n/de-DE'>;
}
declare module 'mout/src/date/i18n/en-US.js' {
  declare module.exports: $Exports<'mout/src/date/i18n/en-US'>;
}
declare module 'mout/src/date/i18n/pt-BR.js' {
  declare module.exports: $Exports<'mout/src/date/i18n/pt-BR'>;
}
declare module 'mout/src/date/i18n_.js' {
  declare module.exports: $Exports<'mout/src/date/i18n_'>;
}
declare module 'mout/src/date/isLeapYear.js' {
  declare module.exports: $Exports<'mout/src/date/isLeapYear'>;
}
declare module 'mout/src/date/isSame.js' {
  declare module.exports: $Exports<'mout/src/date/isSame'>;
}
declare module 'mout/src/date/parseIso.js' {
  declare module.exports: $Exports<'mout/src/date/parseIso'>;
}
declare module 'mout/src/date/quarter.js' {
  declare module.exports: $Exports<'mout/src/date/quarter'>;
}
declare module 'mout/src/date/startOf.js' {
  declare module.exports: $Exports<'mout/src/date/startOf'>;
}
declare module 'mout/src/date/strftime.js' {
  declare module.exports: $Exports<'mout/src/date/strftime'>;
}
declare module 'mout/src/date/timezoneAbbr.js' {
  declare module.exports: $Exports<'mout/src/date/timezoneAbbr'>;
}
declare module 'mout/src/date/timezoneOffset.js' {
  declare module.exports: $Exports<'mout/src/date/timezoneOffset'>;
}
declare module 'mout/src/date/totalDaysInMonth.js' {
  declare module.exports: $Exports<'mout/src/date/totalDaysInMonth'>;
}
declare module 'mout/src/date/totalDaysInYear.js' {
  declare module.exports: $Exports<'mout/src/date/totalDaysInYear'>;
}
declare module 'mout/src/date/weekOfTheYear.js' {
  declare module.exports: $Exports<'mout/src/date/weekOfTheYear'>;
}
declare module 'mout/src/function.js' {
  declare module.exports: $Exports<'mout/src/function'>;
}
declare module 'mout/src/function/after.js' {
  declare module.exports: $Exports<'mout/src/function/after'>;
}
declare module 'mout/src/function/awaitDelay.js' {
  declare module.exports: $Exports<'mout/src/function/awaitDelay'>;
}
declare module 'mout/src/function/bind.js' {
  declare module.exports: $Exports<'mout/src/function/bind'>;
}
declare module 'mout/src/function/compose.js' {
  declare module.exports: $Exports<'mout/src/function/compose'>;
}
declare module 'mout/src/function/constant.js' {
  declare module.exports: $Exports<'mout/src/function/constant'>;
}
declare module 'mout/src/function/debounce.js' {
  declare module.exports: $Exports<'mout/src/function/debounce'>;
}
declare module 'mout/src/function/func.js' {
  declare module.exports: $Exports<'mout/src/function/func'>;
}
declare module 'mout/src/function/identity.js' {
  declare module.exports: $Exports<'mout/src/function/identity'>;
}
declare module 'mout/src/function/makeIterator_.js' {
  declare module.exports: $Exports<'mout/src/function/makeIterator_'>;
}
declare module 'mout/src/function/memoize.js' {
  declare module.exports: $Exports<'mout/src/function/memoize'>;
}
declare module 'mout/src/function/partial.js' {
  declare module.exports: $Exports<'mout/src/function/partial'>;
}
declare module 'mout/src/function/prop.js' {
  declare module.exports: $Exports<'mout/src/function/prop'>;
}
declare module 'mout/src/function/series.js' {
  declare module.exports: $Exports<'mout/src/function/series'>;
}
declare module 'mout/src/function/throttle.js' {
  declare module.exports: $Exports<'mout/src/function/throttle'>;
}
declare module 'mout/src/function/timeout.js' {
  declare module.exports: $Exports<'mout/src/function/timeout'>;
}
declare module 'mout/src/function/times.js' {
  declare module.exports: $Exports<'mout/src/function/times'>;
}
declare module 'mout/src/function/wrap.js' {
  declare module.exports: $Exports<'mout/src/function/wrap'>;
}
declare module 'mout/src/index.js' {
  declare module.exports: $Exports<'mout/src/index'>;
}
declare module 'mout/src/lang.js' {
  declare module.exports: $Exports<'mout/src/lang'>;
}
declare module 'mout/src/lang/GLOBAL.js' {
  declare module.exports: $Exports<'mout/src/lang/GLOBAL'>;
}
declare module 'mout/src/lang/clone.js' {
  declare module.exports: $Exports<'mout/src/lang/clone'>;
}
declare module 'mout/src/lang/createObject.js' {
  declare module.exports: $Exports<'mout/src/lang/createObject'>;
}
declare module 'mout/src/lang/ctorApply.js' {
  declare module.exports: $Exports<'mout/src/lang/ctorApply'>;
}
declare module 'mout/src/lang/deepClone.js' {
  declare module.exports: $Exports<'mout/src/lang/deepClone'>;
}
declare module 'mout/src/lang/deepEquals.js' {
  declare module.exports: $Exports<'mout/src/lang/deepEquals'>;
}
declare module 'mout/src/lang/defaults.js' {
  declare module.exports: $Exports<'mout/src/lang/defaults'>;
}
declare module 'mout/src/lang/inheritPrototype.js' {
  declare module.exports: $Exports<'mout/src/lang/inheritPrototype'>;
}
declare module 'mout/src/lang/is.js' {
  declare module.exports: $Exports<'mout/src/lang/is'>;
}
declare module 'mout/src/lang/isArguments.js' {
  declare module.exports: $Exports<'mout/src/lang/isArguments'>;
}
declare module 'mout/src/lang/isArray.js' {
  declare module.exports: $Exports<'mout/src/lang/isArray'>;
}
declare module 'mout/src/lang/isBoolean.js' {
  declare module.exports: $Exports<'mout/src/lang/isBoolean'>;
}
declare module 'mout/src/lang/isDate.js' {
  declare module.exports: $Exports<'mout/src/lang/isDate'>;
}
declare module 'mout/src/lang/isEmpty.js' {
  declare module.exports: $Exports<'mout/src/lang/isEmpty'>;
}
declare module 'mout/src/lang/isFinite.js' {
  declare module.exports: $Exports<'mout/src/lang/isFinite'>;
}
declare module 'mout/src/lang/isFunction.js' {
  declare module.exports: $Exports<'mout/src/lang/isFunction'>;
}
declare module 'mout/src/lang/isInteger.js' {
  declare module.exports: $Exports<'mout/src/lang/isInteger'>;
}
declare module 'mout/src/lang/isKind.js' {
  declare module.exports: $Exports<'mout/src/lang/isKind'>;
}
declare module 'mout/src/lang/isNaN.js' {
  declare module.exports: $Exports<'mout/src/lang/isNaN'>;
}
declare module 'mout/src/lang/isNull.js' {
  declare module.exports: $Exports<'mout/src/lang/isNull'>;
}
declare module 'mout/src/lang/isNumber.js' {
  declare module.exports: $Exports<'mout/src/lang/isNumber'>;
}
declare module 'mout/src/lang/isObject.js' {
  declare module.exports: $Exports<'mout/src/lang/isObject'>;
}
declare module 'mout/src/lang/isPlainObject.js' {
  declare module.exports: $Exports<'mout/src/lang/isPlainObject'>;
}
declare module 'mout/src/lang/isPrimitive.js' {
  declare module.exports: $Exports<'mout/src/lang/isPrimitive'>;
}
declare module 'mout/src/lang/isRegExp.js' {
  declare module.exports: $Exports<'mout/src/lang/isRegExp'>;
}
declare module 'mout/src/lang/isString.js' {
  declare module.exports: $Exports<'mout/src/lang/isString'>;
}
declare module 'mout/src/lang/isUndefined.js' {
  declare module.exports: $Exports<'mout/src/lang/isUndefined'>;
}
declare module 'mout/src/lang/isnt.js' {
  declare module.exports: $Exports<'mout/src/lang/isnt'>;
}
declare module 'mout/src/lang/kindOf.js' {
  declare module.exports: $Exports<'mout/src/lang/kindOf'>;
}
declare module 'mout/src/lang/toArray.js' {
  declare module.exports: $Exports<'mout/src/lang/toArray'>;
}
declare module 'mout/src/lang/toNumber.js' {
  declare module.exports: $Exports<'mout/src/lang/toNumber'>;
}
declare module 'mout/src/lang/toString.js' {
  declare module.exports: $Exports<'mout/src/lang/toString'>;
}
declare module 'mout/src/math.js' {
  declare module.exports: $Exports<'mout/src/math'>;
}
declare module 'mout/src/math/ceil.js' {
  declare module.exports: $Exports<'mout/src/math/ceil'>;
}
declare module 'mout/src/math/clamp.js' {
  declare module.exports: $Exports<'mout/src/math/clamp'>;
}
declare module 'mout/src/math/countSteps.js' {
  declare module.exports: $Exports<'mout/src/math/countSteps'>;
}
declare module 'mout/src/math/floor.js' {
  declare module.exports: $Exports<'mout/src/math/floor'>;
}
declare module 'mout/src/math/inRange.js' {
  declare module.exports: $Exports<'mout/src/math/inRange'>;
}
declare module 'mout/src/math/isNear.js' {
  declare module.exports: $Exports<'mout/src/math/isNear'>;
}
declare module 'mout/src/math/lerp.js' {
  declare module.exports: $Exports<'mout/src/math/lerp'>;
}
declare module 'mout/src/math/loop.js' {
  declare module.exports: $Exports<'mout/src/math/loop'>;
}
declare module 'mout/src/math/map.js' {
  declare module.exports: $Exports<'mout/src/math/map'>;
}
declare module 'mout/src/math/norm.js' {
  declare module.exports: $Exports<'mout/src/math/norm'>;
}
declare module 'mout/src/math/overflow.js' {
  declare module.exports: $Exports<'mout/src/math/overflow'>;
}
declare module 'mout/src/math/round.js' {
  declare module.exports: $Exports<'mout/src/math/round'>;
}
declare module 'mout/src/number.js' {
  declare module.exports: $Exports<'mout/src/number'>;
}
declare module 'mout/src/number/MAX_INT.js' {
  declare module.exports: $Exports<'mout/src/number/MAX_INT'>;
}
declare module 'mout/src/number/MAX_SAFE_INTEGER.js' {
  declare module.exports: $Exports<'mout/src/number/MAX_SAFE_INTEGER'>;
}
declare module 'mout/src/number/MAX_UINT.js' {
  declare module.exports: $Exports<'mout/src/number/MAX_UINT'>;
}
declare module 'mout/src/number/MIN_INT.js' {
  declare module.exports: $Exports<'mout/src/number/MIN_INT'>;
}
declare module 'mout/src/number/abbreviate.js' {
  declare module.exports: $Exports<'mout/src/number/abbreviate'>;
}
declare module 'mout/src/number/currencyFormat.js' {
  declare module.exports: $Exports<'mout/src/number/currencyFormat'>;
}
declare module 'mout/src/number/enforcePrecision.js' {
  declare module.exports: $Exports<'mout/src/number/enforcePrecision'>;
}
declare module 'mout/src/number/isNaN.js' {
  declare module.exports: $Exports<'mout/src/number/isNaN'>;
}
declare module 'mout/src/number/nth.js' {
  declare module.exports: $Exports<'mout/src/number/nth'>;
}
declare module 'mout/src/number/ordinal.js' {
  declare module.exports: $Exports<'mout/src/number/ordinal'>;
}
declare module 'mout/src/number/pad.js' {
  declare module.exports: $Exports<'mout/src/number/pad'>;
}
declare module 'mout/src/number/rol.js' {
  declare module.exports: $Exports<'mout/src/number/rol'>;
}
declare module 'mout/src/number/ror.js' {
  declare module.exports: $Exports<'mout/src/number/ror'>;
}
declare module 'mout/src/number/sign.js' {
  declare module.exports: $Exports<'mout/src/number/sign'>;
}
declare module 'mout/src/number/toInt.js' {
  declare module.exports: $Exports<'mout/src/number/toInt'>;
}
declare module 'mout/src/number/toUInt.js' {
  declare module.exports: $Exports<'mout/src/number/toUInt'>;
}
declare module 'mout/src/number/toUInt31.js' {
  declare module.exports: $Exports<'mout/src/number/toUInt31'>;
}
declare module 'mout/src/object.js' {
  declare module.exports: $Exports<'mout/src/object'>;
}
declare module 'mout/src/object/bindAll.js' {
  declare module.exports: $Exports<'mout/src/object/bindAll'>;
}
declare module 'mout/src/object/contains.js' {
  declare module.exports: $Exports<'mout/src/object/contains'>;
}
declare module 'mout/src/object/deepFillIn.js' {
  declare module.exports: $Exports<'mout/src/object/deepFillIn'>;
}
declare module 'mout/src/object/deepMatches.js' {
  declare module.exports: $Exports<'mout/src/object/deepMatches'>;
}
declare module 'mout/src/object/deepMixIn.js' {
  declare module.exports: $Exports<'mout/src/object/deepMixIn'>;
}
declare module 'mout/src/object/equals.js' {
  declare module.exports: $Exports<'mout/src/object/equals'>;
}
declare module 'mout/src/object/every.js' {
  declare module.exports: $Exports<'mout/src/object/every'>;
}
declare module 'mout/src/object/fillIn.js' {
  declare module.exports: $Exports<'mout/src/object/fillIn'>;
}
declare module 'mout/src/object/filter.js' {
  declare module.exports: $Exports<'mout/src/object/filter'>;
}
declare module 'mout/src/object/find.js' {
  declare module.exports: $Exports<'mout/src/object/find'>;
}
declare module 'mout/src/object/flatten.js' {
  declare module.exports: $Exports<'mout/src/object/flatten'>;
}
declare module 'mout/src/object/forIn.js' {
  declare module.exports: $Exports<'mout/src/object/forIn'>;
}
declare module 'mout/src/object/forOwn.js' {
  declare module.exports: $Exports<'mout/src/object/forOwn'>;
}
declare module 'mout/src/object/functions.js' {
  declare module.exports: $Exports<'mout/src/object/functions'>;
}
declare module 'mout/src/object/get.js' {
  declare module.exports: $Exports<'mout/src/object/get'>;
}
declare module 'mout/src/object/has.js' {
  declare module.exports: $Exports<'mout/src/object/has'>;
}
declare module 'mout/src/object/hasOwn.js' {
  declare module.exports: $Exports<'mout/src/object/hasOwn'>;
}
declare module 'mout/src/object/keys.js' {
  declare module.exports: $Exports<'mout/src/object/keys'>;
}
declare module 'mout/src/object/map.js' {
  declare module.exports: $Exports<'mout/src/object/map'>;
}
declare module 'mout/src/object/matches.js' {
  declare module.exports: $Exports<'mout/src/object/matches'>;
}
declare module 'mout/src/object/max.js' {
  declare module.exports: $Exports<'mout/src/object/max'>;
}
declare module 'mout/src/object/merge.js' {
  declare module.exports: $Exports<'mout/src/object/merge'>;
}
declare module 'mout/src/object/min.js' {
  declare module.exports: $Exports<'mout/src/object/min'>;
}
declare module 'mout/src/object/mixIn.js' {
  declare module.exports: $Exports<'mout/src/object/mixIn'>;
}
declare module 'mout/src/object/namespace.js' {
  declare module.exports: $Exports<'mout/src/object/namespace'>;
}
declare module 'mout/src/object/omit.js' {
  declare module.exports: $Exports<'mout/src/object/omit'>;
}
declare module 'mout/src/object/pick.js' {
  declare module.exports: $Exports<'mout/src/object/pick'>;
}
declare module 'mout/src/object/pluck.js' {
  declare module.exports: $Exports<'mout/src/object/pluck'>;
}
declare module 'mout/src/object/reduce.js' {
  declare module.exports: $Exports<'mout/src/object/reduce'>;
}
declare module 'mout/src/object/reject.js' {
  declare module.exports: $Exports<'mout/src/object/reject'>;
}
declare module 'mout/src/object/result.js' {
  declare module.exports: $Exports<'mout/src/object/result'>;
}
declare module 'mout/src/object/set.js' {
  declare module.exports: $Exports<'mout/src/object/set'>;
}
declare module 'mout/src/object/size.js' {
  declare module.exports: $Exports<'mout/src/object/size'>;
}
declare module 'mout/src/object/some.js' {
  declare module.exports: $Exports<'mout/src/object/some'>;
}
declare module 'mout/src/object/unset.js' {
  declare module.exports: $Exports<'mout/src/object/unset'>;
}
declare module 'mout/src/object/values.js' {
  declare module.exports: $Exports<'mout/src/object/values'>;
}
declare module 'mout/src/queryString.js' {
  declare module.exports: $Exports<'mout/src/queryString'>;
}
declare module 'mout/src/queryString/contains.js' {
  declare module.exports: $Exports<'mout/src/queryString/contains'>;
}
declare module 'mout/src/queryString/decode.js' {
  declare module.exports: $Exports<'mout/src/queryString/decode'>;
}
declare module 'mout/src/queryString/encode.js' {
  declare module.exports: $Exports<'mout/src/queryString/encode'>;
}
declare module 'mout/src/queryString/getParam.js' {
  declare module.exports: $Exports<'mout/src/queryString/getParam'>;
}
declare module 'mout/src/queryString/getQuery.js' {
  declare module.exports: $Exports<'mout/src/queryString/getQuery'>;
}
declare module 'mout/src/queryString/parse.js' {
  declare module.exports: $Exports<'mout/src/queryString/parse'>;
}
declare module 'mout/src/queryString/setParam.js' {
  declare module.exports: $Exports<'mout/src/queryString/setParam'>;
}
declare module 'mout/src/random.js' {
  declare module.exports: $Exports<'mout/src/random'>;
}
declare module 'mout/src/random/choice.js' {
  declare module.exports: $Exports<'mout/src/random/choice'>;
}
declare module 'mout/src/random/guid.js' {
  declare module.exports: $Exports<'mout/src/random/guid'>;
}
declare module 'mout/src/random/rand.js' {
  declare module.exports: $Exports<'mout/src/random/rand'>;
}
declare module 'mout/src/random/randBit.js' {
  declare module.exports: $Exports<'mout/src/random/randBit'>;
}
declare module 'mout/src/random/randBool.js' {
  declare module.exports: $Exports<'mout/src/random/randBool'>;
}
declare module 'mout/src/random/randHex.js' {
  declare module.exports: $Exports<'mout/src/random/randHex'>;
}
declare module 'mout/src/random/randInt.js' {
  declare module.exports: $Exports<'mout/src/random/randInt'>;
}
declare module 'mout/src/random/randSign.js' {
  declare module.exports: $Exports<'mout/src/random/randSign'>;
}
declare module 'mout/src/random/randString.js' {
  declare module.exports: $Exports<'mout/src/random/randString'>;
}
declare module 'mout/src/random/random.js' {
  declare module.exports: $Exports<'mout/src/random/random'>;
}
declare module 'mout/src/string.js' {
  declare module.exports: $Exports<'mout/src/string'>;
}
declare module 'mout/src/string/WHITE_SPACES.js' {
  declare module.exports: $Exports<'mout/src/string/WHITE_SPACES'>;
}
declare module 'mout/src/string/camelCase.js' {
  declare module.exports: $Exports<'mout/src/string/camelCase'>;
}
declare module 'mout/src/string/contains.js' {
  declare module.exports: $Exports<'mout/src/string/contains'>;
}
declare module 'mout/src/string/crop.js' {
  declare module.exports: $Exports<'mout/src/string/crop'>;
}
declare module 'mout/src/string/endsWith.js' {
  declare module.exports: $Exports<'mout/src/string/endsWith'>;
}
declare module 'mout/src/string/escapeHtml.js' {
  declare module.exports: $Exports<'mout/src/string/escapeHtml'>;
}
declare module 'mout/src/string/escapeRegExp.js' {
  declare module.exports: $Exports<'mout/src/string/escapeRegExp'>;
}
declare module 'mout/src/string/escapeUnicode.js' {
  declare module.exports: $Exports<'mout/src/string/escapeUnicode'>;
}
declare module 'mout/src/string/hyphenate.js' {
  declare module.exports: $Exports<'mout/src/string/hyphenate'>;
}
declare module 'mout/src/string/insert.js' {
  declare module.exports: $Exports<'mout/src/string/insert'>;
}
declare module 'mout/src/string/interpolate.js' {
  declare module.exports: $Exports<'mout/src/string/interpolate'>;
}
declare module 'mout/src/string/lowerCase.js' {
  declare module.exports: $Exports<'mout/src/string/lowerCase'>;
}
declare module 'mout/src/string/lpad.js' {
  declare module.exports: $Exports<'mout/src/string/lpad'>;
}
declare module 'mout/src/string/ltrim.js' {
  declare module.exports: $Exports<'mout/src/string/ltrim'>;
}
declare module 'mout/src/string/makePath.js' {
  declare module.exports: $Exports<'mout/src/string/makePath'>;
}
declare module 'mout/src/string/normalizeLineBreaks.js' {
  declare module.exports: $Exports<'mout/src/string/normalizeLineBreaks'>;
}
declare module 'mout/src/string/pascalCase.js' {
  declare module.exports: $Exports<'mout/src/string/pascalCase'>;
}
declare module 'mout/src/string/properCase.js' {
  declare module.exports: $Exports<'mout/src/string/properCase'>;
}
declare module 'mout/src/string/removeNonASCII.js' {
  declare module.exports: $Exports<'mout/src/string/removeNonASCII'>;
}
declare module 'mout/src/string/removeNonWord.js' {
  declare module.exports: $Exports<'mout/src/string/removeNonWord'>;
}
declare module 'mout/src/string/repeat.js' {
  declare module.exports: $Exports<'mout/src/string/repeat'>;
}
declare module 'mout/src/string/replace.js' {
  declare module.exports: $Exports<'mout/src/string/replace'>;
}
declare module 'mout/src/string/replaceAccents.js' {
  declare module.exports: $Exports<'mout/src/string/replaceAccents'>;
}
declare module 'mout/src/string/rpad.js' {
  declare module.exports: $Exports<'mout/src/string/rpad'>;
}
declare module 'mout/src/string/rtrim.js' {
  declare module.exports: $Exports<'mout/src/string/rtrim'>;
}
declare module 'mout/src/string/sentenceCase.js' {
  declare module.exports: $Exports<'mout/src/string/sentenceCase'>;
}
declare module 'mout/src/string/slugify.js' {
  declare module.exports: $Exports<'mout/src/string/slugify'>;
}
declare module 'mout/src/string/startsWith.js' {
  declare module.exports: $Exports<'mout/src/string/startsWith'>;
}
declare module 'mout/src/string/stripHtmlTags.js' {
  declare module.exports: $Exports<'mout/src/string/stripHtmlTags'>;
}
declare module 'mout/src/string/trim.js' {
  declare module.exports: $Exports<'mout/src/string/trim'>;
}
declare module 'mout/src/string/truncate.js' {
  declare module.exports: $Exports<'mout/src/string/truncate'>;
}
declare module 'mout/src/string/typecast.js' {
  declare module.exports: $Exports<'mout/src/string/typecast'>;
}
declare module 'mout/src/string/unCamelCase.js' {
  declare module.exports: $Exports<'mout/src/string/unCamelCase'>;
}
declare module 'mout/src/string/underscore.js' {
  declare module.exports: $Exports<'mout/src/string/underscore'>;
}
declare module 'mout/src/string/unescapeHtml.js' {
  declare module.exports: $Exports<'mout/src/string/unescapeHtml'>;
}
declare module 'mout/src/string/unescapeUnicode.js' {
  declare module.exports: $Exports<'mout/src/string/unescapeUnicode'>;
}
declare module 'mout/src/string/unhyphenate.js' {
  declare module.exports: $Exports<'mout/src/string/unhyphenate'>;
}
declare module 'mout/src/string/upperCase.js' {
  declare module.exports: $Exports<'mout/src/string/upperCase'>;
}
declare module 'mout/src/time.js' {
  declare module.exports: $Exports<'mout/src/time'>;
}
declare module 'mout/src/time/convert.js' {
  declare module.exports: $Exports<'mout/src/time/convert'>;
}
declare module 'mout/src/time/now.js' {
  declare module.exports: $Exports<'mout/src/time/now'>;
}
declare module 'mout/src/time/parseMs.js' {
  declare module.exports: $Exports<'mout/src/time/parseMs'>;
}
declare module 'mout/src/time/toTimeString.js' {
  declare module.exports: $Exports<'mout/src/time/toTimeString'>;
}
declare module 'mout/string.js' {
  declare module.exports: $Exports<'mout/string'>;
}
declare module 'mout/string/WHITE_SPACES.js' {
  declare module.exports: $Exports<'mout/string/WHITE_SPACES'>;
}
declare module 'mout/string/camelCase.js' {
  declare module.exports: $Exports<'mout/string/camelCase'>;
}
declare module 'mout/string/contains.js' {
  declare module.exports: $Exports<'mout/string/contains'>;
}
declare module 'mout/string/crop.js' {
  declare module.exports: $Exports<'mout/string/crop'>;
}
declare module 'mout/string/endsWith.js' {
  declare module.exports: $Exports<'mout/string/endsWith'>;
}
declare module 'mout/string/escapeHtml.js' {
  declare module.exports: $Exports<'mout/string/escapeHtml'>;
}
declare module 'mout/string/escapeRegExp.js' {
  declare module.exports: $Exports<'mout/string/escapeRegExp'>;
}
declare module 'mout/string/escapeUnicode.js' {
  declare module.exports: $Exports<'mout/string/escapeUnicode'>;
}
declare module 'mout/string/hyphenate.js' {
  declare module.exports: $Exports<'mout/string/hyphenate'>;
}
declare module 'mout/string/insert.js' {
  declare module.exports: $Exports<'mout/string/insert'>;
}
declare module 'mout/string/interpolate.js' {
  declare module.exports: $Exports<'mout/string/interpolate'>;
}
declare module 'mout/string/lowerCase.js' {
  declare module.exports: $Exports<'mout/string/lowerCase'>;
}
declare module 'mout/string/lpad.js' {
  declare module.exports: $Exports<'mout/string/lpad'>;
}
declare module 'mout/string/ltrim.js' {
  declare module.exports: $Exports<'mout/string/ltrim'>;
}
declare module 'mout/string/makePath.js' {
  declare module.exports: $Exports<'mout/string/makePath'>;
}
declare module 'mout/string/normalizeLineBreaks.js' {
  declare module.exports: $Exports<'mout/string/normalizeLineBreaks'>;
}
declare module 'mout/string/pascalCase.js' {
  declare module.exports: $Exports<'mout/string/pascalCase'>;
}
declare module 'mout/string/properCase.js' {
  declare module.exports: $Exports<'mout/string/properCase'>;
}
declare module 'mout/string/removeNonASCII.js' {
  declare module.exports: $Exports<'mout/string/removeNonASCII'>;
}
declare module 'mout/string/removeNonWord.js' {
  declare module.exports: $Exports<'mout/string/removeNonWord'>;
}
declare module 'mout/string/repeat.js' {
  declare module.exports: $Exports<'mout/string/repeat'>;
}
declare module 'mout/string/replace.js' {
  declare module.exports: $Exports<'mout/string/replace'>;
}
declare module 'mout/string/replaceAccents.js' {
  declare module.exports: $Exports<'mout/string/replaceAccents'>;
}
declare module 'mout/string/rpad.js' {
  declare module.exports: $Exports<'mout/string/rpad'>;
}
declare module 'mout/string/rtrim.js' {
  declare module.exports: $Exports<'mout/string/rtrim'>;
}
declare module 'mout/string/sentenceCase.js' {
  declare module.exports: $Exports<'mout/string/sentenceCase'>;
}
declare module 'mout/string/slugify.js' {
  declare module.exports: $Exports<'mout/string/slugify'>;
}
declare module 'mout/string/startsWith.js' {
  declare module.exports: $Exports<'mout/string/startsWith'>;
}
declare module 'mout/string/stripHtmlTags.js' {
  declare module.exports: $Exports<'mout/string/stripHtmlTags'>;
}
declare module 'mout/string/trim.js' {
  declare module.exports: $Exports<'mout/string/trim'>;
}
declare module 'mout/string/truncate.js' {
  declare module.exports: $Exports<'mout/string/truncate'>;
}
declare module 'mout/string/typecast.js' {
  declare module.exports: $Exports<'mout/string/typecast'>;
}
declare module 'mout/string/unCamelCase.js' {
  declare module.exports: $Exports<'mout/string/unCamelCase'>;
}
declare module 'mout/string/underscore.js' {
  declare module.exports: $Exports<'mout/string/underscore'>;
}
declare module 'mout/string/unescapeHtml.js' {
  declare module.exports: $Exports<'mout/string/unescapeHtml'>;
}
declare module 'mout/string/unescapeUnicode.js' {
  declare module.exports: $Exports<'mout/string/unescapeUnicode'>;
}
declare module 'mout/string/unhyphenate.js' {
  declare module.exports: $Exports<'mout/string/unhyphenate'>;
}
declare module 'mout/string/upperCase.js' {
  declare module.exports: $Exports<'mout/string/upperCase'>;
}
declare module 'mout/time.js' {
  declare module.exports: $Exports<'mout/time'>;
}
declare module 'mout/time/convert.js' {
  declare module.exports: $Exports<'mout/time/convert'>;
}
declare module 'mout/time/now.js' {
  declare module.exports: $Exports<'mout/time/now'>;
}
declare module 'mout/time/parseMs.js' {
  declare module.exports: $Exports<'mout/time/parseMs'>;
}
declare module 'mout/time/toTimeString.js' {
  declare module.exports: $Exports<'mout/time/toTimeString'>;
}
