// flow-typed signature: dcfecd411a7af8e8960e9431a6839867
// flow-typed version: <<STUB>>/ng-annotate-loader_v0.2.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ng-annotate-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ng-annotate-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ng-annotate-loader/cases/babel/file-to-annotate' {
  declare module.exports: any;
}

declare module 'ng-annotate-loader/cases/babel/reference/build' {
  declare module.exports: any;
}

declare module 'ng-annotate-loader/cases/babel/reference/sourcemap-checkpoints' {
  declare module.exports: any;
}

declare module 'ng-annotate-loader/cases/babel/to-import' {
  declare module.exports: any;
}

declare module 'ng-annotate-loader/cases/babel/webpack.config' {
  declare module.exports: any;
}

declare module 'ng-annotate-loader/cases/simple/file-to-annotate' {
  declare module.exports: any;
}

declare module 'ng-annotate-loader/cases/simple/reference/build' {
  declare module.exports: any;
}

declare module 'ng-annotate-loader/cases/simple/reference/sourcemap-checkpoints' {
  declare module.exports: any;
}

declare module 'ng-annotate-loader/cases/simple/webpack.config' {
  declare module.exports: any;
}

declare module 'ng-annotate-loader/cases/typescript/reference/build' {
  declare module.exports: any;
}

declare module 'ng-annotate-loader/cases/typescript/reference/sourcemap-checkpoints' {
  declare module.exports: any;
}

declare module 'ng-annotate-loader/cases/typescript/webpack.config' {
  declare module.exports: any;
}

declare module 'ng-annotate-loader/cases/uglifyjs/reference/build' {
  declare module.exports: any;
}

declare module 'ng-annotate-loader/cases/uglifyjs/reference/sourcemap-checkpoints' {
  declare module.exports: any;
}

declare module 'ng-annotate-loader/cases/uglifyjs/webpack.config' {
  declare module.exports: any;
}

declare module 'ng-annotate-loader/loader' {
  declare module.exports: any;
}

declare module 'ng-annotate-loader/run-tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ng-annotate-loader/cases/babel/file-to-annotate.js' {
  declare module.exports: $Exports<'ng-annotate-loader/cases/babel/file-to-annotate'>;
}
declare module 'ng-annotate-loader/cases/babel/reference/build.js' {
  declare module.exports: $Exports<'ng-annotate-loader/cases/babel/reference/build'>;
}
declare module 'ng-annotate-loader/cases/babel/reference/sourcemap-checkpoints.js' {
  declare module.exports: $Exports<'ng-annotate-loader/cases/babel/reference/sourcemap-checkpoints'>;
}
declare module 'ng-annotate-loader/cases/babel/to-import.js' {
  declare module.exports: $Exports<'ng-annotate-loader/cases/babel/to-import'>;
}
declare module 'ng-annotate-loader/cases/babel/webpack.config.js' {
  declare module.exports: $Exports<'ng-annotate-loader/cases/babel/webpack.config'>;
}
declare module 'ng-annotate-loader/cases/simple/file-to-annotate.js' {
  declare module.exports: $Exports<'ng-annotate-loader/cases/simple/file-to-annotate'>;
}
declare module 'ng-annotate-loader/cases/simple/reference/build.js' {
  declare module.exports: $Exports<'ng-annotate-loader/cases/simple/reference/build'>;
}
declare module 'ng-annotate-loader/cases/simple/reference/sourcemap-checkpoints.js' {
  declare module.exports: $Exports<'ng-annotate-loader/cases/simple/reference/sourcemap-checkpoints'>;
}
declare module 'ng-annotate-loader/cases/simple/webpack.config.js' {
  declare module.exports: $Exports<'ng-annotate-loader/cases/simple/webpack.config'>;
}
declare module 'ng-annotate-loader/cases/typescript/reference/build.js' {
  declare module.exports: $Exports<'ng-annotate-loader/cases/typescript/reference/build'>;
}
declare module 'ng-annotate-loader/cases/typescript/reference/sourcemap-checkpoints.js' {
  declare module.exports: $Exports<'ng-annotate-loader/cases/typescript/reference/sourcemap-checkpoints'>;
}
declare module 'ng-annotate-loader/cases/typescript/webpack.config.js' {
  declare module.exports: $Exports<'ng-annotate-loader/cases/typescript/webpack.config'>;
}
declare module 'ng-annotate-loader/cases/uglifyjs/reference/build.js' {
  declare module.exports: $Exports<'ng-annotate-loader/cases/uglifyjs/reference/build'>;
}
declare module 'ng-annotate-loader/cases/uglifyjs/reference/sourcemap-checkpoints.js' {
  declare module.exports: $Exports<'ng-annotate-loader/cases/uglifyjs/reference/sourcemap-checkpoints'>;
}
declare module 'ng-annotate-loader/cases/uglifyjs/webpack.config.js' {
  declare module.exports: $Exports<'ng-annotate-loader/cases/uglifyjs/webpack.config'>;
}
declare module 'ng-annotate-loader/loader.js' {
  declare module.exports: $Exports<'ng-annotate-loader/loader'>;
}
declare module 'ng-annotate-loader/run-tests.js' {
  declare module.exports: $Exports<'ng-annotate-loader/run-tests'>;
}
