// flow-typed signature: 7ddb84c5f72e16b2ef7bdce604445780
// flow-typed version: <<STUB>>/null-loader_v0.1.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'null-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'null-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'null-loader/index' {
  declare module.exports: $Exports<'null-loader'>;
}
declare module 'null-loader/index.js' {
  declare module.exports: $Exports<'null-loader'>;
}
