// flow-typed signature: d367859e076d4ff502403eb8f7d9e449
// flow-typed version: <<STUB>>/postcss-modules-values-replace_v1.0.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-modules-values-replace'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-modules-values-replace' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-modules-values-replace/index' {
  declare module.exports: $Exports<'postcss-modules-values-replace'>;
}
declare module 'postcss-modules-values-replace/index.js' {
  declare module.exports: $Exports<'postcss-modules-values-replace'>;
}
