// flow-typed signature: c5b790e55835053525417431dac23114
// flow-typed version: <<STUB>>/prop-types_v15.5.8/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prop-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'prop-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prop-types/checkPropTypes' {
  declare module.exports: any;
}

declare module 'prop-types/factory' {
  declare module.exports: any;
}

declare module 'prop-types/factoryWithThrowingShims' {
  declare module.exports: any;
}

declare module 'prop-types/factoryWithTypeCheckers' {
  declare module.exports: any;
}

declare module 'prop-types/lib/ReactPropTypesSecret' {
  declare module.exports: any;
}

declare module 'prop-types/prop-types' {
  declare module.exports: any;
}

declare module 'prop-types/prop-types.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prop-types/checkPropTypes.js' {
  declare module.exports: $Exports<'prop-types/checkPropTypes'>;
}
declare module 'prop-types/factory.js' {
  declare module.exports: $Exports<'prop-types/factory'>;
}
declare module 'prop-types/factoryWithThrowingShims.js' {
  declare module.exports: $Exports<'prop-types/factoryWithThrowingShims'>;
}
declare module 'prop-types/factoryWithTypeCheckers.js' {
  declare module.exports: $Exports<'prop-types/factoryWithTypeCheckers'>;
}
declare module 'prop-types/index' {
  declare module.exports: $Exports<'prop-types'>;
}
declare module 'prop-types/index.js' {
  declare module.exports: $Exports<'prop-types'>;
}
declare module 'prop-types/lib/ReactPropTypesSecret.js' {
  declare module.exports: $Exports<'prop-types/lib/ReactPropTypesSecret'>;
}
declare module 'prop-types/prop-types.js' {
  declare module.exports: $Exports<'prop-types/prop-types'>;
}
declare module 'prop-types/prop-types.min.js' {
  declare module.exports: $Exports<'prop-types/prop-types.min'>;
}
