// flow-typed signature: 5b77befca452e87937f944735c458f59
// flow-typed version: <<STUB>>/react-waypoint_v6.0.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-waypoint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-waypoint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-waypoint/build/computeOffsetPixels' {
  declare module.exports: any;
}

declare module 'react-waypoint/build/constants' {
  declare module.exports: any;
}

declare module 'react-waypoint/build/debugLog' {
  declare module.exports: any;
}

declare module 'react-waypoint/build/ensureChildrenIsSingleDOMElement' {
  declare module.exports: any;
}

declare module 'react-waypoint/build/getCurrentPosition' {
  declare module.exports: any;
}

declare module 'react-waypoint/build/isDOMElement' {
  declare module.exports: any;
}

declare module 'react-waypoint/build/parseOffsetAsPercentage' {
  declare module.exports: any;
}

declare module 'react-waypoint/build/parseOffsetAsPixels' {
  declare module.exports: any;
}

declare module 'react-waypoint/build/resolveScrollableAncestorProp' {
  declare module.exports: any;
}

declare module 'react-waypoint/build/waypoint' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-waypoint/build/computeOffsetPixels.js' {
  declare module.exports: $Exports<'react-waypoint/build/computeOffsetPixels'>;
}
declare module 'react-waypoint/build/constants.js' {
  declare module.exports: $Exports<'react-waypoint/build/constants'>;
}
declare module 'react-waypoint/build/debugLog.js' {
  declare module.exports: $Exports<'react-waypoint/build/debugLog'>;
}
declare module 'react-waypoint/build/ensureChildrenIsSingleDOMElement.js' {
  declare module.exports: $Exports<'react-waypoint/build/ensureChildrenIsSingleDOMElement'>;
}
declare module 'react-waypoint/build/getCurrentPosition.js' {
  declare module.exports: $Exports<'react-waypoint/build/getCurrentPosition'>;
}
declare module 'react-waypoint/build/isDOMElement.js' {
  declare module.exports: $Exports<'react-waypoint/build/isDOMElement'>;
}
declare module 'react-waypoint/build/parseOffsetAsPercentage.js' {
  declare module.exports: $Exports<'react-waypoint/build/parseOffsetAsPercentage'>;
}
declare module 'react-waypoint/build/parseOffsetAsPixels.js' {
  declare module.exports: $Exports<'react-waypoint/build/parseOffsetAsPixels'>;
}
declare module 'react-waypoint/build/resolveScrollableAncestorProp.js' {
  declare module.exports: $Exports<'react-waypoint/build/resolveScrollableAncestorProp'>;
}
declare module 'react-waypoint/build/waypoint.js' {
  declare module.exports: $Exports<'react-waypoint/build/waypoint'>;
}
