// flow-typed signature: f78e3dfaff0deb94e38a79b31754cade
// flow-typed version: <<STUB>>/react-markdown_v2.5.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-markdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-markdown/demo/dist/js/codemirror' {
  declare module.exports: any;
}

declare module 'react-markdown/demo/dist/js/demo' {
  declare module.exports: any;
}

declare module 'react-markdown/demo/src/code-block' {
  declare module.exports: any;
}

declare module 'react-markdown/demo/src/demo' {
  declare module.exports: any;
}

declare module 'react-markdown/demo/src/editor' {
  declare module.exports: any;
}

declare module 'react-markdown/demo/src/markdown-controls' {
  declare module.exports: any;
}

declare module 'react-markdown/src/react-markdown' {
  declare module.exports: any;
}

declare module 'react-markdown/umd/react-markdown' {
  declare module.exports: any;
}

declare module 'react-markdown/webpack.config.demo' {
  declare module.exports: any;
}

declare module 'react-markdown/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-markdown/demo/dist/js/codemirror.js' {
  declare module.exports: $Exports<'react-markdown/demo/dist/js/codemirror'>;
}
declare module 'react-markdown/demo/dist/js/demo.js' {
  declare module.exports: $Exports<'react-markdown/demo/dist/js/demo'>;
}
declare module 'react-markdown/demo/src/code-block.js' {
  declare module.exports: $Exports<'react-markdown/demo/src/code-block'>;
}
declare module 'react-markdown/demo/src/demo.js' {
  declare module.exports: $Exports<'react-markdown/demo/src/demo'>;
}
declare module 'react-markdown/demo/src/editor.js' {
  declare module.exports: $Exports<'react-markdown/demo/src/editor'>;
}
declare module 'react-markdown/demo/src/markdown-controls.js' {
  declare module.exports: $Exports<'react-markdown/demo/src/markdown-controls'>;
}
declare module 'react-markdown/src/react-markdown.js' {
  declare module.exports: $Exports<'react-markdown/src/react-markdown'>;
}
declare module 'react-markdown/umd/react-markdown.js' {
  declare module.exports: $Exports<'react-markdown/umd/react-markdown'>;
}
declare module 'react-markdown/webpack.config.demo.js' {
  declare module.exports: $Exports<'react-markdown/webpack.config.demo'>;
}
declare module 'react-markdown/webpack.config.js' {
  declare module.exports: $Exports<'react-markdown/webpack.config'>;
}
