// flow-typed signature: cca43b437dd969b79160f1e11a4af26c
// flow-typed version: <<STUB>>/simply-uuid_v1.0.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'simply-uuid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'simply-uuid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'simply-uuid/lib/uuid-node' {
  declare module.exports: any;
}

declare module 'simply-uuid/test/uuid' {
  declare module.exports: any;
}

declare module 'simply-uuid/uuid' {
  declare module.exports: any;
}

// Filename aliases
declare module 'simply-uuid/index' {
  declare module.exports: $Exports<'simply-uuid'>;
}
declare module 'simply-uuid/index.js' {
  declare module.exports: $Exports<'simply-uuid'>;
}
declare module 'simply-uuid/lib/uuid-node.js' {
  declare module.exports: $Exports<'simply-uuid/lib/uuid-node'>;
}
declare module 'simply-uuid/test/uuid.js' {
  declare module.exports: $Exports<'simply-uuid/test/uuid'>;
}
declare module 'simply-uuid/uuid.js' {
  declare module.exports: $Exports<'simply-uuid/uuid'>;
}
