// flow-typed signature: c201230a971ccf8d01c2444291a4f298
// flow-typed version: <<STUB>>/sniffr_v1.1.4/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sniffr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'sniffr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sniffr/src/sniffr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sniffr/src/sniffr.js' {
  declare module.exports: $Exports<'sniffr/src/sniffr'>;
}
