// flow-typed signature: b76229a1de73e5868a8c42f35a7402f0
// flow-typed version: <<STUB>>/storage-mock_v1.0.3/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storage-mock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'storage-mock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storage-mock/event' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storage-mock/event.js' {
  declare module.exports: $Exports<'storage-mock/event'>;
}
declare module 'storage-mock/index' {
  declare module.exports: $Exports<'storage-mock'>;
}
declare module 'storage-mock/index.js' {
  declare module.exports: $Exports<'storage-mock'>;
}
