// flow-typed signature: 9adb717fd507e05a854d2a6d74182104
// flow-typed version: <<STUB>>/update-version_v1.0.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'update-version'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'update-version' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'update-version/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'update-version/cli.js' {
  declare module.exports: $Exports<'update-version/cli'>;
}
declare module 'update-version/index' {
  declare module.exports: $Exports<'update-version'>;
}
declare module 'update-version/index.js' {
  declare module.exports: $Exports<'update-version'>;
}
