// flow-typed signature: e1549e9b8c53f31d419f2ceeb3ba453b
// flow-typed version: <<STUB>>/wallaby-webpack_v0.0.38/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wallaby-webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'wallaby-webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wallaby-webpack/lib/WallabyInputFileSystem' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wallaby-webpack/index' {
  declare module.exports: $Exports<'wallaby-webpack'>;
}
declare module 'wallaby-webpack/index.js' {
  declare module.exports: $Exports<'wallaby-webpack'>;
}
declare module 'wallaby-webpack/lib/WallabyInputFileSystem.js' {
  declare module.exports: $Exports<'wallaby-webpack/lib/WallabyInputFileSystem'>;
}
