// flow-typed signature: 00c0937c018cc08d83d2202a2eb33eb4
// flow-typed version: <<STUB>>/whatwg-fetch_v1.0.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'whatwg-fetch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'whatwg-fetch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'whatwg-fetch/fetch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'whatwg-fetch/fetch.js' {
  declare module.exports: $Exports<'whatwg-fetch/fetch'>;
}
