// flow-typed signature: 80d8c7efd1cba30e634f3da1b69a1364
// flow-typed version: <<STUB>>/yo_v1.8.5/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'yo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'yo/lib/cli' {
  declare module.exports: any;
}

declare module 'yo/lib/completion/completer' {
  declare module.exports: any;
}

declare module 'yo/lib/completion/index' {
  declare module.exports: any;
}

declare module 'yo/lib/router' {
  declare module.exports: any;
}

declare module 'yo/lib/routes/clear-config' {
  declare module.exports: any;
}

declare module 'yo/lib/routes/exit' {
  declare module.exports: any;
}

declare module 'yo/lib/routes/help' {
  declare module.exports: any;
}

declare module 'yo/lib/routes/home' {
  declare module.exports: any;
}

declare module 'yo/lib/routes/install' {
  declare module.exports: any;
}

declare module 'yo/lib/routes/run' {
  declare module.exports: any;
}

declare module 'yo/lib/routes/update' {
  declare module.exports: any;
}

declare module 'yo/lib/utils/global-config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'yo/lib/cli.js' {
  declare module.exports: $Exports<'yo/lib/cli'>;
}
declare module 'yo/lib/completion/completer.js' {
  declare module.exports: $Exports<'yo/lib/completion/completer'>;
}
declare module 'yo/lib/completion/index.js' {
  declare module.exports: $Exports<'yo/lib/completion/index'>;
}
declare module 'yo/lib/router.js' {
  declare module.exports: $Exports<'yo/lib/router'>;
}
declare module 'yo/lib/routes/clear-config.js' {
  declare module.exports: $Exports<'yo/lib/routes/clear-config'>;
}
declare module 'yo/lib/routes/exit.js' {
  declare module.exports: $Exports<'yo/lib/routes/exit'>;
}
declare module 'yo/lib/routes/help.js' {
  declare module.exports: $Exports<'yo/lib/routes/help'>;
}
declare module 'yo/lib/routes/home.js' {
  declare module.exports: $Exports<'yo/lib/routes/home'>;
}
declare module 'yo/lib/routes/install.js' {
  declare module.exports: $Exports<'yo/lib/routes/install'>;
}
declare module 'yo/lib/routes/run.js' {
  declare module.exports: $Exports<'yo/lib/routes/run'>;
}
declare module 'yo/lib/routes/update.js' {
  declare module.exports: $Exports<'yo/lib/routes/update'>;
}
declare module 'yo/lib/utils/global-config.js' {
  declare module.exports: $Exports<'yo/lib/utils/global-config'>;
}
