package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.slackConnection
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            slackConnection {
                id = "PROJECT_EXT_271"
                displayName = "Slack Ring UI Notifier"
                botToken = "credentialsJSON:c9217053-7225-4fcf-899e-58b897fe1aba"
                clientId = "2280447103.10029068672503"
                clientSecret = "credentialsJSON:9567123a-a39a-4f83-befa-8a28810d8819"
            }
        }
    }
}
