export default [
  'd M',
  'dd M',
  'dd MM',
  'd-M',
  'dd-M',
  'dd-MM',
  'd.M',
  'dd.M',
  'dd.MM',
  'd\\M',
  'dd\\M',
  'dd\\MM',
  'd/M',
  'dd/M',
  'dd/MM',
  'd M yy',
  'dd M yy',
  'dd MM yy',
  'd M yyyy',
  'dd M yyyy',
  'dd MM yyyy',
  'd-M-yy',
  'dd-M-yy',
  'dd-MM-yy',
  'd-M-yyyy',
  'dd-M-yyyy',
  'dd-MM-yyyy',
  'd.M.yy',
  'dd.M.yy',
  'dd.MM.yy',
  'd.M.yyyy',
  'dd.M.yyyy',
  'dd.MM.yyyy',
  'd\\M\\yy',
  'dd\\M\\yy',
  'dd\\MM\\yy',
  'd\\M\\yyyy',
  'dd\\M\\yyyy',
  'dd\\MM\\yyyy',
  'd/M/yy',
  'dd/M/yy',
  'dd/MM/yy',
  'd/M/yyyy',
  'dd/M/yyyy',
  'dd/MM/yyyy',
  'd M yy',
  'dd M yy',
  'dd MM yy',
  'd M yyyy',
  'dd M yyyy',
  'dd MM yyyy',
  'd-M-yy',
  'dd-M-yy',
  'dd-MM-yy',
  'd-M-yyyy',
  'dd-M-yyyy',
  'dd-MM-yyyy',
  'd.M.yy',
  'dd.M.yy',
  'dd.MM.yy',
  'd.M.yyyy',
  'dd.M.yyyy',
  'dd.MM.yyyy',
  'd\\M\\yy',
  'dd\\M\\yy',
  'dd\\MM\\yy',
  'd\\M\\yyyy',
  'dd\\M\\yyyy',
  'dd\\MM\\yyyy',
  'd/M/yy',
  'dd/M/yy',
  'dd/MM/yy',
  'd/M/yyyy',
  'dd/M/yyyy',
  'dd/MM/yyyy',
  'yy M d',
  'yy M dd',
  'yy MM dd',
  'yyyy M d',
  'yyyy M dd',
  'yyyy MM dd',
  'yy-M-d',
  'yy-M-dd',
  'yy-MM-dd',
  'yyyy-M-d',
  'yyyy-M-dd',
  'yyyy-MM-dd',
  'yy.M.d',
  'yy.M.dd',
  'yy.MM.dd',
  'yyyy.M.d',
  'yyyy.M.dd',
  'yyyy.MM.dd',
  'yy\\M\\d',
  'yy\\M\\dd',
  'yy\\MM\\dd',
  'yyyy\\M\\d',
  'yyyy\\M\\dd',
  'yyyy\\MM\\dd',
  'yy/M/d',
  'yy/M/dd',
  'yy/MM/dd',
  'yyyy/M/d',
  'yyyy/M/dd',
  'yyyy/MM/dd',
  'yy d M',
  'yy dd M',
  'yy dd MM',
  'yyyy d M',
  'yyyy dd MM',
  'yyyy dd MM',
  'yy-d-M',
  'yy-dd-M',
  'yy-dd-MM',
  'yyyy-d-M',
  'yyyy-dd-MM',
  'yyyy-dd-MM',
  'yy.d.M',
  'yy.dd.M',
  'yy.dd.MM',
  'yyyy.d.M',
  'yyyy.dd.MM',
  'yyyy.dd.MM',
  'yy\\d\\M',
  'yy\\dd\\M',
  'yy\\dd\\MM',
  'yyyy\\d\\M',
  'yyyy\\dd\\MM',
  'yyyy\\dd\\MM',
  'yy/d/M',
  'yy/dd/M',
  'yy/dd/MM',
  'yyyy/d/M',
  'yyyy/dd/MM',
  'yyyy/dd/MM',
  'd MMM',
  'd MMMM',
  'dd MMM',
  'dd MMMM',
  'd M HH:mm',
  'd M, HH:mm',
  'dd M HH:mm',
  'dd M, HH:mm',
  'dd MM HH:mm',
  'dd MM, HH:mm',
  'd-M HH:mm',
  'd-M, HH:mm',
  'dd-M HH:mm',
  'dd-M, HH:mm',
  'dd-MM HH:mm',
  'dd-MM, HH:mm',
  'd.M HH:mm',
  'd.M, HH:mm',
  'dd.M HH:mm',
  'dd.M, HH:mm',
  'dd.MM HH:mm',
  'dd.MM, HH:mm',
  'd\\M HH:mm',
  'd\\M, HH:mm',
  'dd\\M HH:mm',
  'dd\\M, HH:mm',
  'dd\\MM HH:mm',
  'dd\\MM, HH:mm',
  'd/M HH:mm',
  'd/M, HH:mm',
  'dd/M HH:mm',
  'dd/M, HH:mm',
  'dd/MM HH:mm',
  'dd/MM, HH:mm',
  'd M yy HH:mm',
  'd M yy, HH:mm',
  'dd M yy HH:mm',
  'dd M yy, HH:mm',
  'dd MM yy HH:mm',
  'dd MM yy, HH:mm',
  'd M yyyy HH:mm',
  'd M yyyy, HH:mm',
  'dd M yyyy HH:mm',
  'dd M yyyy, HH:mm',
  'dd MM yyyy HH:mm',
  'dd MM yyyy, HH:mm',
  'd-M-yy HH:mm',
  'd-M-yy, HH:mm',
  'dd-M-yy HH:mm',
  'dd-M-yy, HH:mm',
  'dd-MM-yy HH:mm',
  'dd-MM-yy, HH:mm',
  'd-M-yyyy HH:mm',
  'd-M-yyyy, HH:mm',
  'dd-M-yyyy HH:mm',
  'dd-M-yyyy, HH:mm',
  'dd-MM-yyyy HH:mm',
  'dd-MM-yyyy, HH:mm',
  'd.M.yy HH:mm',
  'd.M.yy, HH:mm',
  'dd.M.yy HH:mm',
  'dd.M.yy, HH:mm',
  'dd.MM.yy HH:mm',
  'dd.MM.yy, HH:mm',
  'd.M.yyyy HH:mm',
  'd.M.yyyy, HH:mm',
  'dd.M.yyyy HH:mm',
  'dd.M.yyyy, HH:mm',
  'dd.MM.yyyy HH:mm',
  'dd.MM.yyyy, HH:mm',
  'd\\M\\yy HH:mm',
  'd\\M\\yy, HH:mm',
  'dd\\M\\yy HH:mm',
  'dd\\M\\yy, HH:mm',
  'dd\\MM\\yy HH:mm',
  'dd\\MM\\yy, HH:mm',
  'd\\M\\yyyy HH:mm',
  'd\\M\\yyyy, HH:mm',
  'dd\\M\\yyyy HH:mm',
  'dd\\M\\yyyy, HH:mm',
  'dd\\MM\\yyyy HH:mm',
  'dd\\MM\\yyyy, HH:mm',
  'd/M/yy HH:mm',
  'd/M/yy, HH:mm',
  'dd/M/yy HH:mm',
  'dd/M/yy, HH:mm',
  'dd/MM/yy HH:mm',
  'dd/MM/yy, HH:mm',
  'd/M/yyyy HH:mm',
  'd/M/yyyy, HH:mm',
  'dd/M/yyyy HH:mm',
  'dd/M/yyyy, HH:mm',
  'dd/MM/yyyy HH:mm',
  'dd/MM/yyyy, HH:mm',
  'd M yy HH:mm',
  'd M yy, HH:mm',
  'dd M yy HH:mm',
  'dd M yy, HH:mm',
  'dd MM yy HH:mm',
  'dd MM yy, HH:mm',
  'd M yyyy HH:mm',
  'd M yyyy, HH:mm',
  'dd M yyyy HH:mm',
  'dd M yyyy, HH:mm',
  'dd MM yyyy HH:mm',
  'dd MM yyyy, HH:mm',
  'd-M-yy HH:mm',
  'd-M-yy, HH:mm',
  'dd-M-yy HH:mm',
  'dd-M-yy, HH:mm',
  'dd-MM-yy HH:mm',
  'dd-MM-yy, HH:mm',
  'd-M-yyyy HH:mm',
  'd-M-yyyy, HH:mm',
  'dd-M-yyyy HH:mm',
  'dd-M-yyyy, HH:mm',
  'dd-MM-yyyy HH:mm',
  'dd-MM-yyyy, HH:mm',
  'd.M.yy HH:mm',
  'd.M.yy, HH:mm',
  'dd.M.yy HH:mm',
  'dd.M.yy, HH:mm',
  'dd.MM.yy HH:mm',
  'dd.MM.yy, HH:mm',
  'd.M.yyyy HH:mm',
  'd.M.yyyy, HH:mm',
  'dd.M.yyyy HH:mm',
  'dd.M.yyyy, HH:mm',
  'dd.MM.yyyy HH:mm',
  'dd.MM.yyyy, HH:mm',
  'd\\M\\yy HH:mm',
  'd\\M\\yy, HH:mm',
  'dd\\M\\yy HH:mm',
  'dd\\M\\yy, HH:mm',
  'dd\\MM\\yy HH:mm',
  'dd\\MM\\yy, HH:mm',
  'd\\M\\yyyy HH:mm',
  'd\\M\\yyyy, HH:mm',
  'dd\\M\\yyyy HH:mm',
  'dd\\M\\yyyy, HH:mm',
  'dd\\MM\\yyyy HH:mm',
  'dd\\MM\\yyyy, HH:mm',
  'd/M/yy HH:mm',
  'd/M/yy, HH:mm',
  'dd/M/yy HH:mm',
  'dd/M/yy, HH:mm',
  'dd/MM/yy HH:mm',
  'dd/MM/yy, HH:mm',
  'd/M/yyyy HH:mm',
  'd/M/yyyy, HH:mm',
  'dd/M/yyyy HH:mm',
  'dd/M/yyyy, HH:mm',
  'dd/MM/yyyy HH:mm',
  'dd/MM/yyyy, HH:mm',
  'yy M d HH:mm',
  'yy M d, HH:mm',
  'yy M dd HH:mm',
  'yy M dd, HH:mm',
  'yy MM dd HH:mm',
  'yy MM dd, HH:mm',
  'yyyy M d HH:mm',
  'yyyy M d, HH:mm',
  'yyyy M dd HH:mm',
  'yyyy M dd, HH:mm',
  'yyyy MM dd HH:mm',
  'yyyy MM dd, HH:mm',
  'yy-M-d HH:mm',
  'yy-M-d, HH:mm',
  'yy-M-dd HH:mm',
  'yy-M-dd, HH:mm',
  'yy-MM-dd HH:mm',
  'yy-MM-dd, HH:mm',
  'yyyy-M-d HH:mm',
  'yyyy-M-d, HH:mm',
  'yyyy-M-dd HH:mm',
  'yyyy-M-dd, HH:mm',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd, HH:mm',
  'yy.M.d HH:mm',
  'yy.M.d, HH:mm',
  'yy.M.dd HH:mm',
  'yy.M.dd, HH:mm',
  'yy.MM.dd HH:mm',
  'yy.MM.dd, HH:mm',
  'yyyy.M.d HH:mm',
  'yyyy.M.d, HH:mm',
  'yyyy.M.dd HH:mm',
  'yyyy.M.dd, HH:mm',
  'yyyy.MM.dd HH:mm',
  'yyyy.MM.dd, HH:mm',
  'yy\\M\\d HH:mm',
  'yy\\M\\d, HH:mm',
  'yy\\M\\dd HH:mm',
  'yy\\M\\dd, HH:mm',
  'yy\\MM\\dd HH:mm',
  'yy\\MM\\dd, HH:mm',
  'yyyy\\M\\d HH:mm',
  'yyyy\\M\\d, HH:mm',
  'yyyy\\M\\dd HH:mm',
  'yyyy\\M\\dd, HH:mm',
  'yyyy\\MM\\dd HH:mm',
  'yyyy\\MM\\dd, HH:mm',
  'yy/M/d HH:mm',
  'yy/M/d, HH:mm',
  'yy/M/dd HH:mm',
  'yy/M/dd, HH:mm',
  'yy/MM/dd HH:mm',
  'yy/MM/dd, HH:mm',
  'yyyy/M/d HH:mm',
  'yyyy/M/d, HH:mm',
  'yyyy/M/dd HH:mm',
  'yyyy/M/dd, HH:mm',
  'yyyy/MM/dd HH:mm',
  'yyyy/MM/dd, HH:mm',
  'yy d M HH:mm',
  'yy d M, HH:mm',
  'yy dd M HH:mm',
  'yy dd M, HH:mm',
  'yy dd MM HH:mm',
  'yy dd MM, HH:mm',
  'yyyy d M HH:mm',
  'yyyy d M, HH:mm',
  'yyyy dd MM HH:mm',
  'yyyy dd MM, HH:mm',
  'yyyy dd MM HH:mm',
  'yyyy dd MM, HH:mm',
  'yy-d-M HH:mm',
  'yy-d-M, HH:mm',
  'yy-dd-M HH:mm',
  'yy-dd-M, HH:mm',
  'yy-dd-MM HH:mm',
  'yy-dd-MM, HH:mm',
  'yyyy-d-M HH:mm',
  'yyyy-d-M, HH:mm',
  'yyyy-dd-MM HH:mm',
  'yyyy-dd-MM, HH:mm',
  'yyyy-dd-MM HH:mm',
  'yyyy-dd-MM, HH:mm',
  'yy.d.M HH:mm',
  'yy.d.M, HH:mm',
  'yy.dd.M HH:mm',
  'yy.dd.M, HH:mm',
  'yy.dd.MM HH:mm',
  'yy.dd.MM, HH:mm',
  'yyyy.d.M HH:mm',
  'yyyy.d.M, HH:mm',
  'yyyy.dd.MM HH:mm',
  'yyyy.dd.MM, HH:mm',
  'yyyy.dd.MM HH:mm',
  'yyyy.dd.MM, HH:mm',
  'yy\\d\\M HH:mm',
  'yy\\d\\M, HH:mm',
  'yy\\dd\\M HH:mm',
  'yy\\dd\\M, HH:mm',
  'yy\\dd\\MM HH:mm',
  'yy\\dd\\MM, HH:mm',
  'yyyy\\d\\M HH:mm',
  'yyyy\\d\\M, HH:mm',
  'yyyy\\dd\\MM HH:mm',
  'yyyy\\dd\\MM, HH:mm',
  'yyyy\\dd\\MM HH:mm',
  'yyyy\\dd\\MM, HH:mm',
  'yy/d/M HH:mm',
  'yy/d/M, HH:mm',
  'yy/dd/M HH:mm',
  'yy/dd/M, HH:mm',
  'yy/dd/MM HH:mm',
  'yy/dd/MM, HH:mm',
  'yyyy/d/M HH:mm',
  'yyyy/d/M, HH:mm',
  'yyyy/dd/MM HH:mm',
  'yyyy/dd/MM, HH:mm',
  'yyyy/dd/MM HH:mm',
  'yyyy/dd/MM, HH:mm',
  'd MMM HH:mm',
  'd MMM, HH:mm',
  'd MMMM HH:mm',
  'd MMMM, HH:mm',
  'dd MMM HH:mm',
  'dd MMM, HH:mm',
  'dd MMMM HH:mm',
  'dd MMMM, HH:mm',
  'yyyy MMM d',
  'yyyy MMMM d',
  'yyyy MMM dd',
  'yyyy MMMM dd',
  'yyyy d MMM',
  'yyyy d MMMM',
  'yyyy dd MMM',
  'yyyy dd MMMM',
  'd MMM yy',
  'd MMMM yy',
  'dd MMM yy',
  'dd MMMM yy',
  'd MMM yyyy',
  'd MMMM yyyy',
  'dd MMM yyyy',
  'dd MMMM yyyy',
  'd MMM yy',
  'd MMMM yy',
  'dd MMM yy',
  'dd MMMM yy',
  'd MMM yyyy',
  'd MMMM yyyy',
  'dd MMM yyyy',
  'dd MMMM yyyy',
  'MMM d yyyy',
  'MMMM d yyyy',
  'MMM dd yyyy',
  'MMMM dd yyyy',
  'yy MMM d',
  'yy MMMM d',
  'yy MMM dd',
  'yy MMMM dd',
  'yy d MMM',
  'yy d MMMM',
  'yy dd MMM',
  'yy dd MMMM',
  'd MMM',
  'd MMMM',
  'dd MMM',
  'dd MMMM',
  'yyyy MMM d HH:mm',
  'yyyy MMM d, HH:mm',
  'yyyy MMMM d HH:mm',
  'yyyy MMMM d, HH:mm',
  'yyyy MMM dd HH:mm',
  'yyyy MMM dd, HH:mm',
  'yyyy MMMM dd HH:mm',
  'yyyy MMMM dd, HH:mm',
  'yyyy d MMM HH:mm',
  'yyyy d MMM, HH:mm',
  'yyyy d MMMM HH:mm',
  'yyyy d MMMM, HH:mm',
  'yyyy dd MMM HH:mm',
  'yyyy dd MMM, HH:mm',
  'yyyy dd MMMM HH:mm',
  'yyyy dd MMMM, HH:mm',
  'd MMM yy HH:mm',
  'd MMM yy, HH:mm',
  'd MMMM yy HH:mm',
  'd MMMM yy, HH:mm',
  'dd MMM yy HH:mm',
  'dd MMM yy, HH:mm',
  'dd MMMM yy HH:mm',
  'dd MMMM yy, HH:mm',
  'd MMM yyyy HH:mm',
  'd MMM yyyy, HH:mm',
  'd MMMM yyyy HH:mm',
  'd MMMM yyyy, HH:mm',
  'dd MMM yyyy HH:mm',
  'dd MMM yyyy, HH:mm',
  'dd MMMM yyyy HH:mm',
  'dd MMMM yyyy, HH:mm',
  'd MMM yy HH:mm',
  'd MMM yy, HH:mm',
  'd MMMM yy HH:mm',
  'd MMMM yy, HH:mm',
  'dd MMM yy HH:mm',
  'dd MMM yy, HH:mm',
  'dd MMMM yy HH:mm',
  'dd MMMM yy, HH:mm',
  'd MMM yyyy HH:mm',
  'd MMM yyyy, HH:mm',
  'd MMMM yyyy HH:mm',
  'd MMMM yyyy, HH:mm',
  'dd MMM yyyy HH:mm',
  'dd MMM yyyy, HH:mm',
  'dd MMMM yyyy HH:mm',
  'dd MMMM yyyy, HH:mm',
  'MMM d yyyy HH:mm',
  'MMM d yyyy, HH:mm',
  'MMMM d yyyy HH:mm',
  'MMMM d yyyy, HH:mm',
  'MMM dd yyyy HH:mm',
  'MMM dd yyyy, HH:mm',
  'MMMM dd yyyy HH:mm',
  'MMMM dd yyyy, HH:mm',
  'yy MMM d HH:mm',
  'yy MMM d, HH:mm',
  'yy MMMM d HH:mm',
  'yy MMMM d, HH:mm',
  'yy MMM dd HH:mm',
  'yy MMM dd, HH:mm',
  'yy MMMM dd HH:mm',
  'yy MMMM dd, HH:mm',
  'yy d MMM HH:mm',
  'yy d MMM, HH:mm',
  'yy d MMMM HH:mm',
  'yy d MMMM, HH:mm',
  'yy dd MMM HH:mm',
  'yy dd MMM, HH:mm',
  'yy dd MMMM HH:mm',
  'yy dd MMMM, HH:mm',
  'd MMM HH:mm',
  'd MMM, HH:mm',
  'd MMMM HH:mm',
  'd MMMM, HH:mm',
  'dd MMM HH:mm',
  'dd MMM, HH:mm',
  'dd MMMM HH:mm',
  'dd MMMM, HH:mm',
  'yyyy MMM d',
  'yyyy MMMM d',
  'yyyy MMM dd',
  'yyyy MMMM dd',
  'yyyy d MMM',
  'yyyy d MMMM',
  'yyyy dd MMM',
  'yyyy dd MMMM',
  'd MMM yy',
  'd MMMM yy',
  'dd MMM yy',
  'dd MMMM yy',
  'd MMM yyyy',
  'd MMMM yyyy',
  'dd MMM yyyy',
  'dd MMMM yyyy',
  'd MMM yy',
  'd MMMM yy',
  'dd MMM yy',
  'dd MMMM yy',
  'd MMM yyyy',
  'd MMMM yyyy',
  'dd MMM yyyy',
  'dd MMMM yyyy',
  'MMM d yyyy',
  'MMMM d yyyy',
  'MMM dd yyyy',
  'MMMM dd yyyy',
  'yy MMM d',
  'yy MMMM d',
  'yy MMM dd',
  'yy MMMM dd',
  'yy d MMM',
  'yy d MMMM',
  'yy dd MMM',
  'yy dd MMMM',
  'yyyy MMM d HH:mm',
  'yyyy MMM d, HH:mm',
  'yyyy MMMM d HH:mm',
  'yyyy MMMM d, HH:mm',
  'yyyy MMM dd HH:mm',
  'yyyy MMM dd, HH:mm',
  'yyyy MMMM dd HH:mm',
  'yyyy MMMM dd, HH:mm',
  'yyyy d MMM HH:mm',
  'yyyy d MMM, HH:mm',
  'yyyy d MMMM HH:mm',
  'yyyy d MMMM, HH:mm',
  'yyyy dd MMM HH:mm',
  'yyyy dd MMM, HH:mm',
  'yyyy dd MMMM HH:mm',
  'yyyy dd MMMM, HH:mm',
  'd MMM yy HH:mm',
  'd MMM yy, HH:mm',
  'd MMMM yy HH:mm',
  'd MMMM yy, HH:mm',
  'dd MMM yy HH:mm',
  'dd MMM yy, HH:mm',
  'dd MMMM yy HH:mm',
  'dd MMMM yy, HH:mm',
  'd MMM yyyy HH:mm',
  'd MMM yyyy, HH:mm',
  'd MMMM yyyy HH:mm',
  'd MMMM yyyy, HH:mm',
  'dd MMM yyyy HH:mm',
  'dd MMM yyyy, HH:mm',
  'dd MMMM yyyy HH:mm',
  'dd MMMM yyyy, HH:mm',
  'd MMM yy HH:mm',
  'd MMM yy, HH:mm',
  'd MMMM yy HH:mm',
  'd MMMM yy, HH:mm',
  'dd MMM yy HH:mm',
  'dd MMM yy, HH:mm',
  'dd MMMM yy HH:mm',
  'dd MMMM yy, HH:mm',
  'd MMM yyyy HH:mm',
  'd MMM yyyy, HH:mm',
  'd MMMM yyyy HH:mm',
  'd MMMM yyyy, HH:mm',
  'dd MMM yyyy HH:mm',
  'dd MMM yyyy, HH:mm',
  'dd MMMM yyyy HH:mm',
  'dd MMMM yyyy, HH:mm',
  'MMM d yyyy HH:mm',
  'MMM d yyyy, HH:mm',
  'MMMM d yyyy HH:mm',
  'MMMM d yyyy, HH:mm',
  'MMM dd yyyy HH:mm',
  'MMM dd yyyy, HH:mm',
  'MMMM dd yyyy HH:mm',
  'MMMM dd yyyy, HH:mm',
  'yy MMM d HH:mm',
  'yy MMM d, HH:mm',
  'yy MMMM d HH:mm',
  'yy MMMM d, HH:mm',
  'yy MMM dd HH:mm',
  'yy MMM dd, HH:mm',
  'yy MMMM dd HH:mm',
  'yy MMMM dd, HH:mm',
  'yy d MMM HH:mm',
  'yy d MMM, HH:mm',
  'yy d MMMM HH:mm',
  'yy d MMMM, HH:mm',
  'yy dd MMM HH:mm',
  'yy dd MMM, HH:mm',
  'yy dd MMMM HH:mm',
  'yy dd MMMM, HH:mm',
];
