package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'JetBrainsHubAuth'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("JetBrainsHubAuth")
    name = "JetBrains/hub-auth"
    pollInterval = 300
    url = "git@github.com:JetBrains/hub-auth.git"
    branch = "refs/heads/main"
    branchSpec = "%vcs.branch.spec%"
    authMethod = uploadedKey {
        uploadedKey = "GitHub hub-auth"
    }
}))

