// flow-typed signature: fc23872356c79e801a173fbdeef9f961
// flow-typed version: <<STUB>>/@hypnosphi/react-portal_v3.1.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@hypnosphi/react-portal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@hypnosphi/react-portal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@hypnosphi/react-portal/build/portal' {
  declare module.exports: any;
}

declare module '@hypnosphi/react-portal/build/portaltarget' {
  declare module.exports: any;
}

declare module '@hypnosphi/react-portal/lib/portal' {
  declare module.exports: any;
}

declare module '@hypnosphi/react-portal/lib/portaltarget' {
  declare module.exports: any;
}

// Filename aliases
declare module '@hypnosphi/react-portal/build/portal.js' {
  declare module.exports: $Exports<'@hypnosphi/react-portal/build/portal'>;
}
declare module '@hypnosphi/react-portal/build/portaltarget.js' {
  declare module.exports: $Exports<'@hypnosphi/react-portal/build/portaltarget'>;
}
declare module '@hypnosphi/react-portal/lib/portal.js' {
  declare module.exports: $Exports<'@hypnosphi/react-portal/lib/portal'>;
}
declare module '@hypnosphi/react-portal/lib/portaltarget.js' {
  declare module.exports: $Exports<'@hypnosphi/react-portal/lib/portaltarget'>;
}
