/**
 * NB! This file is autogenerated by ```gulp sprite``` command which is executed
 * while application is being built. Do not change contents of this file manually
 * because it'll be overwritten when you run application server, test or execute
 * sprite generation manually.
 * @fileoverview SVG icons template.
 * @author igor.alexeenko@jetbrains.com (Igor Alekseenko)
 */

module.exports = '{#svg}<symbol id="{name}" viewBox="{viewBox}">{raw|s}</symbol>{/svg}';
