export default {
  '--ring-line-color': '#475159',
  '--ring-borders-color': '#406380',
  '--ring-icon-color': '#80929d',
  '--ring-icon-secondary-color': '#80929d',
  '--ring-border-disabled-color': '#475159',
  '--ring-border-hover-color': '#70b1e6',
  '--ring-icon-error-color': '#c22731',
  '--ring-icon-warning-color': '#cc8b00',
  '--ring-icon-success-color': '#1c8c32',
  '--ring-popup-border-components': '0, 42, 76',
  '--ring-popup-border-color': 'rgba(var(--ring-popup-border-components), 0.1)',
  '--ring-popup-shadow-color': 'rgba(var(--ring-popup-border-components), 0.15)',
  '--ring-message-shadow-color': 'rgba(var(--ring-popup-border-components), 0.3)',

  /* Text */
  '--ring-hint-color': '#80929d',
  '--ring-link-color': '#70b1e6',
  '--ring-error-color': '#db5860',
  '--ring-warning-color': '#eda200',
  '--ring-success-color': '#59a869',
  '--ring-text-color': '#bbb',
  '--ring-heading-color': '#fff',
  '--ring-secondary-color': '#80929d',
  '--ring-disabled-color': '#80929d',

  /* Background */
  '--ring-content-background-color': '#23272b',
  '--ring-popup-background-color': '#111314',
  '--ring-sidebar-background-color': '#28343d',
  '--ring-selected-background-color': '#062640',
  '--ring-hover-background-color': '#0b1a26',
  '--ring-message-background-color': 'var(--ring-popup-background-color)',
  '--ring-navigation-background-color': '#111314',
  '--ring-tag-background-color': '#3e4d59',
  '--ring-removed-background-color': '#8f5247',
  '--ring-warning-background-color': '#593d01',
  '--ring-added-background-color': '#294436',

  /* Code */
  '--ring-code-background-color': '#2b2b2b',
  '--ring-code-color': '#a9b7c6',
  '--ring-code-meta-color': '#bbb529',
  '--ring-code-keyword-color': '#cc7832',
  '--ring-code-tag-background-color': '#2b2b2b',
  '--ring-code-tag-color': '#e8BF6a',
  '--ring-code-tag-font-weight': 'normal',
  '--ring-code-field-color': '#9876aa',
  '--ring-code-attribute-color': '#bababa',
  '--ring-code-number-color': '#6897bb',
  '--ring-code-string-color': '#6a8759',
  '--ring-code-addition-color': '#447152',
  '--ring-code-deletion-color': '#656e76'
};
